/** @type {import('next').NextConfig} */
const nextConfig = {
  // ✅ CORE SETTINGS
  trailingSlash: false,
  reactStrictMode: false,

  // ⚡ OPTIMIZED: Image settings with modern formats
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'image.tmdb.org',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'm.media-amazon.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'via.placeholder.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'www.themoviedb.org',
        pathname: '/**',
      },
      // ✅ ADDED UNSPLASH HERE TO FIX THE ERROR
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        pathname: '/**',
      },
    ],
    // ⚡ NEW: Modern image formats (AVIF/WebP save 50%+ bandwidth)
    formats: ['image/avif', 'image/webp'],
    // ⚡ NEW: Cache images for 30 days (faster repeat visits)
    minimumCacheTTL: 60 * 60 * 24 * 30,
    // ⚡ NEW: Optimized device sizes
    deviceSizes: [640, 768, 1024, 1280, 1536],
    // ⚡ NEW: Optimized image sizes (matches your actual usage)
    imageSizes: [150, 185, 200, 250, 300],
    // 🔥 FIX: Added qualities to stop the "quality 65 is not configured" terminal warnings
    qualities: [25, 50, 65, 75, 85, 100],
  },

  // ✅ ENVIRONMENT VARIABLES
  env: {
    NEXT_PUBLIC_TMDB_API_KEY: process.env.NEXT_PUBLIC_TMDB_API_KEY,
  },

  // ✅ PERFORMANCE SETTINGS
  generateEtags: true, 
  poweredByHeader: false,
  compress: true,

  // ✅ REDIRECTS
  async redirects() {
    return [
      // Essential redirects
      { source: '/contact', destination: '/contact-us', permanent: true },

      // 🚀 MASTER SEO REDIRECTS (Catches ALL old collection duplicates!)
      { source: '/movies/:collection/tt0109830', destination: '/movie/forrest-gump', permanent: true },
      { source: '/movies/:collection/tt0169547', destination: '/movie/american-beauty', permanent: true },
      { source: '/movies/:collection/tt0078788', destination: '/movie/apocalypse-now', permanent: true },
      { source: '/movies/:collection/tt0105695', destination: '/movie/unforgiven', permanent: true },
      { source: '/movies/:collection/tt0338013', destination: '/movie/eternal-sunshine-of-the-spotless-mind', permanent: true },
      { source: '/movies/:collection/tt0062622', destination: '/movie/2001-a-space-odyssey', permanent: true },
      { source: '/movies/:collection/tt0114746', destination: '/movie/12-monkeys', permanent: true },
      { source: '/movies/:collection/tt0088846', destination: '/movie/brazil', permanent: true },
      { source: '/movies/:collection/tt0120586', destination: '/movie/american-history-x', permanent: true },
      { source: '/movies/:collection/tt0407304', destination: '/movie/war-of-the-worlds', permanent: true },
      { source: '/movies/:collection/tt0209144', destination: '/movie/memento', permanent: true },
      { source: '/movies/:collection/tt0082971', destination: '/movie/raiders-of-the-lost-ark', permanent: true },
      { source: '/movies/:collection/tt0172495', destination: '/movie/gladiator', permanent: true },
      { source: '/movies/:collection/tt0075314', destination: '/movie/taxi-driver', permanent: true },
      { source: '/movies/:collection/tt0088763', destination: '/movie/back-to-the-future', permanent: true },
      { source: '/movies/:collection/tt0093773', destination: '/movie/predator', permanent: true },
      { source: '/movies/:collection/tt0086250', destination: '/movie/scarface', permanent: true },
      { source: '/movies/:collection/tt0167260', destination: '/movie/the-lord-of-the-rings-the-return-of-the-king', permanent: true },
      { source: '/movies/:collection/tt0245429', destination: '/movie/spirited-away', permanent: true },
      { source: '/movies/:collection/tt0190590', destination: '/movie/o-brother-where-art-thou', permanent: true },
      { source: '/movies/:collection/tt0107048', destination: '/movie/groundhog-day', permanent: true },
      { source: '/movies/:collection/tt0246578', destination: '/movie/donnie-darko', permanent: true },
      { source: '/movies/:collection/tt0388795', destination: '/movie/brokeback-mountain', permanent: true },
      { source: '/movies/:collection/tt0190332', destination: '/movie/crouching-tiger-hidden-dragon', permanent: true },
      { source: '/movies/:collection/tt0084726', destination: '/movie/star-trek-ii-the-wrath-of-khan', permanent: true },
      { source: '/movies/:collection/tt0468569', destination: '/movie/the-dark-knight', permanent: true },
      { source: '/movies/:collection/tt0240772', destination: '/movie/oceans-eleven', permanent: true },
      { source: '/movies/:collection/tt0054698', destination: '/movie/breakfast-at-tiffanys', permanent: true },
      { source: '/movies/:collection/tt0181689', destination: '/movie/minority-report', permanent: true },
      { source: '/movies/:collection/tt0066921', destination: '/movie/a-clockwork-orange', permanent: true },
      { source: '/movies/:collection/tt0401792', destination: '/movie/sin-city', permanent: true },
      { source: '/movies/:collection/tt0112573', destination: '/movie/braveheart', permanent: true },
      { source: '/movies/:collection/tt0097165', destination: '/movie/dead-poets-society', permanent: true },
      { source: '/movies/:collection/tt0071141', destination: '/movie/ali-fear-eats-the-soul', permanent: true },
      { source: '/movies/:collection/tt0088247', destination: '/movie/the-terminator', permanent: true },
      { source: '/movies/:collection/tt0068646', destination: '/movie/the-godfather', permanent: true },
      { source: '/movies/:collection/tt0071562', destination: '/movie/the-godfather-part-ii', permanent: true },
      { source: '/movies/:collection/tt0099653', destination: '/movie/ghost', permanent: true },
      { source: '/movies/:collection/tt0102926', destination: '/movie/the-silence-of-the-lambs', permanent: true },
      { source: '/movies/:collection/tt0116282', destination: '/movie/fargo', permanent: true },
      { source: '/movies/:collection/tt0111161', destination: '/movie/the-shawshank-redemption', permanent: true },
      { source: '/movies/:collection/tt0103064', destination: '/movie/terminator-2-judgment-day', permanent: true },
      { source: '/movies/:collection/tt0034583', destination: '/movie/casablanca', permanent: true },
      { source: '/movies/:collection/tt0087843', destination: '/movie/once-upon-a-time-in-america', permanent: true },
      { source: '/movies/:collection/tt0327056', destination: '/movie/mystic-river', permanent: true },
      { source: '/movies/:collection/tt0120663', destination: '/movie/eyes-wide-shut', permanent: true },
      { source: '/movies/:collection/tt0047478', destination: '/movie/seven-samurai', permanent: true },
      { source: '/movies/:collection/tt0095953', destination: '/movie/rain-man', permanent: true },
      { source: '/movies/:collection/tt0082096', destination: '/movie/das-boot', permanent: true },
      { source: '/movies/:collection/tt0454848', destination: '/movie/inside-man', permanent: true },
      { source: '/movies/:collection/tt0050083', destination: '/movie/12-angry-men', permanent: true },
      { source: '/movies/:collection/tt0378194', destination: '/movie/kill-bill-vol-2', permanent: true },
      { source: '/movies/:collection/tt0103772', destination: '/movie/basic-instinct', permanent: true },
      { source: '/movies/:collection/tt0166896', destination: '/movie/the-straight-story', permanent: true },
      { source: '/movies/:collection/tt0116209', destination: '/movie/the-english-patient', permanent: true },
      { source: '/movies/:collection/tt0253474', destination: '/movie/the-pianist', permanent: true },
      { source: '/movies/:collection/tt0108052', destination: '/movie/schindlers-list', permanent: true },
      { source: '/movies/:collection/tt0120601', destination: '/movie/being-john-malkovich', permanent: true },
      { source: '/movies/:collection/tt0443453', destination: '/movie/borat', permanent: true },
      { source: '/movies/:collection/tt0120689', destination: '/movie/the-green-mile', permanent: true },
      { source: '/movies/:collection/tt0105236', destination: '/movie/reservoir-dogs', permanent: true },
      { source: '/movies/:collection/tt0125439', destination: '/movie/notting-hill', permanent: true },
      { source: '/movies/:collection/tt0073486', destination: '/movie/one-flew-over-the-cuckoos-nest', permanent: true },
      { source: '/movies/:collection/tt0112641', destination: '/movie/casino', permanent: true },
      { source: '/movies/:collection/tt0129387', destination: '/movie/theres-something-about-mary', permanent: true },
      { source: '/movies/:collection/tt0137523', destination: '/movie/fight-club', permanent: true },
      { source: '/movies/:collection/tt0095016', destination: '/movie/die-hard', permanent: true },
      { source: '/movies/:collection/tt0069293', destination: '/movie/solaris', permanent: true },
      { source: '/movies/:collection/tt0120338', destination: '/movie/titanic', permanent: true },
      { source: '/movies/:collection/tt0317248', destination: '/movie/city-of-god', permanent: true },
      { source: '/movies/:collection/tt0043014', destination: '/movie/sunset-boulevard', permanent: true },
      { source: '/movies/:collection/tt0093058', destination: '/movie/full-metal-jacket', permanent: true },
      { source: '/movies/:collection/tt0120890', destination: '/movie/wild-things', permanent: true },
      { source: '/movies/:collection/tt0142688', destination: '/movie/the-ninth-gate', permanent: true },
      { source: '/movies/:collection/tt0064276', destination: '/movie/easy-rider', permanent: true },
      { source: '/movies/:collection/tt0117951', destination: '/movie/trainspotting', permanent: true },
      { source: '/movies/:collection/tt0114369', destination: '/movie/the-usual-suspects', permanent: true },
      { source: '/movies/:collection/tt0032138', destination: '/movie/the-wizard-of-oz', permanent: true },
      { source: '/movies/:collection/tt0116922', destination: '/movie/lost-highway', permanent: true },
      { source: '/movies/:collection/tt0098635', destination: '/movie/when-harry-met-sally', permanent: true },
      { source: '/movies/:collection/tt0264464', destination: '/movie/catch-me-if-you-can', permanent: true },
      { source: '/movies/:collection/tt0180093', destination: '/movie/requiem-for-a-dream', permanent: true },
      { source: '/movies/:collection/tt0212720', destination: '/movie/ai-artificial-intelligence', permanent: true },
      { source: '/movies/:collection/tt0087884', destination: '/movie/paris-texas', permanent: true },
      { source: '/movies/:collection/tt0364569', destination: '/movie/oldboy', permanent: true },
      { source: '/movies/:collection/tt0241527', destination: '/movie/harry-potter-and-the-sorcerers-stone', permanent: true },
      { source: '/movies/:collection/tt0304141', destination: '/movie/harry-potter-and-the-prisoner-of-azkaban', permanent: true },
      { source: '/movies/:collection/tt0090605', destination: '/movie/aliens', permanent: true },
      { source: '/movies/:collection/tt0110912', destination: '/movie/pulp-fiction', permanent: true },
      { source: '/movies/:collection/tt0118884', destination: '/movie/contact', permanent: true },
      { source: '/movies/:collection/tt0112818', destination: '/movie/dead-man-walking', permanent: true },
      { source: '/movies/:collection/tt0081505', destination: '/movie/the-shining', permanent: true },
      { source: '/movies/:collection/tt0058182', destination: '/movie/a-hard-days-night', permanent: true },
      { source: '/movies/:collection/tt0167404', destination: '/movie/the-sixth-sense', permanent: true },
      { source: '/movies/:collection/tt0434409', destination: '/movie/v-for-vendetta', permanent: true },
      { source: '/movies/:collection/tt0119094', destination: '/movie/faceoff', permanent: true },
      { source: '/movies/:collection/tt0071853', destination: '/movie/monty-python-and-the-holy-grail', permanent: true },
      { source: '/movies/:collection/tt0099685', destination: '/movie/goodfellas', permanent: true },
      { source: '/movies/:collection/tt0031381', destination: '/movie/gone-with-the-wind', permanent: true },
      { source: '/movies/:collection/tt0449059', destination: '/movie/little-miss-sunshine', permanent: true },
      { source: '/movies/:collection/tt0091763', destination: '/movie/platoon', permanent: true },
      { source: '/movies/:collection/tt0090756', destination: '/movie/blue-velvet', permanent: true },
      { source: '/movies/:collection/tt0063522', destination: '/movie/rosemarys-baby', permanent: true },
      { source: '/movies/:collection/tt0114369', destination: '/movie/se7en', permanent: true },
      { source: '/movies/:collection/tt0126029', destination: '/movie/shrek', permanent: true },
      { source: '/movies/:collection/tt0298148', destination: '/movie/shrek-2', permanent: true },
      { source: '/movies/:collection/tt0071315', destination: '/movie/chinatown', permanent: true },
      { source: '/movies/:collection/tt0118694', destination: '/movie/in-the-mood-for-love', permanent: true },
      { source: '/movies/:collection/tt0085334', destination: '/movie/a-christmas-story', permanent: true },
      { source: '/movies/:collection/tt0120815', destination: '/movie/saving-private-ryan', permanent: true },
      { source: '/movies/:collection/tt0100802', destination: '/movie/total-recall', permanent: true },
      { source: '/movies/:collection/tt0045152', destination: '/movie/singin-in-the-rain', permanent: true },
      { source: '/movies/:collection/tt0088939', destination: '/movie/the-color-purple', permanent: true },
      { source: '/movies/:collection/tt0021749', destination: '/movie/city-lights', permanent: true },
      { source: '/movies/:collection/tt0032553', destination: '/movie/the-great-dictator', permanent: true },
      { source: '/movies/:collection/tt0057012', destination: '/movie/dr-strangelove', permanent: true },
      { source: '/movies/:collection/tt0056172', destination: '/movie/lawrence-of-arabia', permanent: true },
      { source: '/movies/:collection/tt0113277', destination: '/movie/heat', permanent: true },
      { source: '/movies/:collection/tt0072890', destination: '/movie/dog-day-afternoon', permanent: true },
      { source: '/movies/:collection/tt0050825', destination: '/movie/paths-of-glory', permanent: true },
      { source: '/movies/:collection/tt0166924', destination: '/movie/mulholland-drive', permanent: true },
      { source: '/movies/:collection/tt0102685', destination: '/movie/point-break', permanent: true },
      { source: '/movies/:collection/tt0139809', destination: '/movie/the-thirteenth-floor', permanent: true },
      { source: '/movies/:collection/tt0482571', destination: '/movie/the-prestige', permanent: true },
      { source: '/movies/:collection/tt0134119', destination: '/movie/the-talented-mr-ripley', permanent: true },
      { source: '/movies/:collection/tt0448134', destination: '/movie/sunshine', permanent: true },
      { source: '/movies/:collection/tt0309987', destination: '/movie/the-dreamers', permanent: true },
      { source: '/movies/:collection/tt0144084', destination: '/movie/american-psycho', permanent: true },
      { source: '/movies/:collection/tt0414993', destination: '/movie/the-fountain', permanent: true },
      { source: '/movies/:collection/tt0245574', destination: '/movie/y-tu-mam-tambin', permanent: true },
      { source: '/movies/:collection/tt0079944', destination: '/movie/stalker', permanent: true },
      { source: '/movies/:collection/tt0015881', destination: '/movie/greed', permanent: true },
      { source: '/movies/:collection/tt0407887', destination: '/movie/the-departed', permanent: true },
      { source: '/movies/:collection/tt0443543', destination: '/movie/the-illusionist', permanent: true },
      { source: '/movies/:collection/tt0371746', destination: '/movie/collateral', permanent: true },
      { source: '/movies/:collection/tt0103074', destination: '/movie/thelma-louise', permanent: true },
      { source: '/movies/:collection/tt0151804', destination: '/movie/office-space', permanent: true },
      { source: '/movies/:collection/tt0472043', destination: '/movie/apocalypto', permanent: true },
      { source: '/movies/:collection/tt0332379', destination: '/movie/school-of-rock', permanent: true },
      { source: '/movies/:collection/tt0038650', destination: '/movie/its-a-wonderful-life', permanent: true },
      { source: '/movies/:collection/tt0117381', destination: '/movie/primal-fear', permanent: true },
      { source: '/movies/:collection/tt0477347', destination: '/movie/night-at-the-museum', permanent: true },
      { source: '/movies/:collection/tt0086465', destination: '/movie/trading-places', permanent: true },
      { source: '/movies/:collection/tt0070849', destination: '/movie/last-tango-in-paris', permanent: true },
      { source: '/movies/:collection/tt0318462', destination: '/movie/the-motorcycle-diaries', permanent: true },
      { source: '/movies/:collection/tt0254686', destination: '/movie/the-piano-teacher', permanent: true },
      { source: '/movies/:collection/tt0343660', destination: '/movie/50-first-dates', permanent: true },
      { source: '/movies/:collection/tt0070334', destination: '/movie/the-long-goodbye', permanent: true },
      { source: '/movies/:collection/tt0418279', destination: '/movie/transformers', permanent: true },
      { source: '/movies/:collection/tt0125659', destination: '/movie/open-your-eyes', permanent: true },
      { source: '/movies/:collection/tt0138097', destination: '/movie/shakespeare-in-love', permanent: true },
      { source: '/movies/:collection/tt0120907', destination: '/movie/existenz', permanent: true },
      { source: '/movies/:collection/tt0443706', destination: '/movie/zodiac', permanent: true },
      { source: '/movies/:collection/tt0289879', destination: '/movie/the-butterfly-effect', permanent: true },
      { source: '/movies/:collection/tt0139654', destination: '/movie/training-day', permanent: true },
      { source: '/movies/:collection/tt0163651', destination: '/movie/american-pie', permanent: true },
      { source: '/movies/:collection/tt0119488', destination: '/movie/la-confidential', permanent: true },
      { source: '/movies/:collection/tt0250797', destination: '/movie/unfaithful', permanent: true },
      { source: '/movies/:collection/tt0765443', destination: '/movie/eastern-promises', permanent: true },
      { source: '/movies/:collection/tt0094737', destination: '/movie/big', permanent: true },
      { source: '/movies/:collection/tt0099871', destination: '/movie/jacobs-ladder', permanent: true },
      { source: '/movies/:collection/tt0093748', destination: '/movie/planes-trains-and-automobiles', permanent: true },
      { source: '/movies/:collection/tt0119174', destination: '/movie/the-game', permanent: true },
      { source: '/movies/:collection/tt0118929', destination: '/movie/dark-city', permanent: true },
      { source: '/movies/:collection/tt0096754', destination: '/movie/the-abyss', permanent: true },
      { source: '/movies/:collection/tt0268126', destination: '/movie/adaptation', permanent: true },
      { source: '/movies/:collection/tt0134847', destination: '/movie/pitch-black', permanent: true },
      { source: '/movies/:collection/tt0119177', destination: '/movie/identity', permanent: true },
      { source: '/movies/:collection/tt0040897', destination: '/movie/the-treasure-of-the-sierra-madre', permanent: true },
      { source: '/movies/:collection/tt0217505', destination: '/movie/gangs-of-new-york', permanent: true },
      { source: '/movies/:collection/tt0465602', destination: '/movie/shoot-em-up', permanent: true },
      { source: '/movies/:collection/tt0959337', destination: '/movie/revolutionary-road', permanent: true },
      { source: '/movies/:collection/tt0175142', destination: '/movie/scary-movie', permanent: true },
      { source: '/movies/:collection/tt0414387', destination: '/movie/pride-prejudice', permanent: true },
      { source: '/movies/:collection/tt0107211', destination: '/movie/indecent-proposal', permanent: true },
      { source: '/movies/:collection/tt0451094', destination: '/movie/lady-vengeance', permanent: true },
      { source: '/movies/:collection/tt0361862', destination: '/movie/the-machinist', permanent: true },
      { source: '/movies/:collection/tt0808357', destination: '/movie/lust-caution', permanent: true },
      { source: '/movies/:collection/tt0310775', destination: '/movie/sympathy-for-mr-vengeance', permanent: true },
      { source: '/movies/:collection/tt0452623', destination: '/movie/gone-baby-gone', permanent: true },
      { source: '/movies/:collection/tt0421715', destination: '/movie/the-curious-case-of-benjamin-button', permanent: true },
      { source: '/movies/:collection/tt0887883', destination: '/movie/burn-after-reading', permanent: true },
      { source: '/movies/:collection/tt0383028', destination: '/movie/synecdoche-new-york', permanent: true },
      { source: '/movies/:collection/tt0106977', destination: '/movie/the-fugitive', permanent: true },
      { source: '/movies/:collection/tt0062229', destination: '/movie/le-samoura', permanent: true },
      { source: '/movies/:collection/tt0758758', destination: '/movie/into-the-wild', permanent: true },
      { source: '/movies/:collection/tt0237572', destination: '/movie/the-pledge', permanent: true },
      { source: '/movies/:collection/tt0343135', destination: '/movie/along-came-polly', permanent: true },
      { source: '/movies/:collection/tt0106519', destination: '/movie/carlitos-way', permanent: true },
      { source: '/movies/:collection/tt0425061', destination: '/movie/the-40-year-old-virgin', permanent: true },
      { source: '/movies/:collection/tt0477348', destination: '/movie/no-country-for-old-men', permanent: true },
      { source: '/movies/:collection/tt0469494', destination: '/movie/there-will-be-blood', permanent: true },
      { source: '/movies/:collection/tt0942385', destination: '/movie/tropic-thunder', permanent: true },
      { source: '/movies/:collection/tt0387808', destination: '/movie/idiocracy', permanent: true },
      { source: '/movies/:collection/tt0292963', destination: '/movie/before-the-devil-knows-youre-dead', permanent: true },
      { source: '/movies/:collection/tt0091203', destination: '/movie/highlander', permanent: true },
      { source: '/movies/:collection/tt0976051', destination: '/movie/the-reader', permanent: true },
      { source: '/movies/:collection/tt0134273', destination: '/movie/8mm', permanent: true },
      { source: '/movies/:collection/tt0780536', destination: '/movie/in-bruges', permanent: true },
      { source: '/movies/:collection/tt0162222', destination: '/movie/cast-away', permanent: true },
      { source: '/movies/:collection/tt0829482', destination: '/movie/superbad', permanent: true },
      { source: '/movies/:collection/tt0144117', destination: '/movie/the-boondock-saints', permanent: true },
      { source: '/movies/:collection/tt0119081', destination: '/movie/event-horizon', permanent: true },
      { source: '/movies/:collection/tt0119167', destination: '/movie/funny-games', permanent: true },
      { source: '/movies/:collection/tt0357413', destination: '/movie/anchorman-the-legend-of-ron-burgundy', permanent: true },
      { source: '/movies/:collection/tt0096163', destination: '/movie/the-vanishing', permanent: true },
      { source: '/movies/:collection/tt0200465', destination: '/movie/the-bank-job', permanent: true },
      { source: '/movies/:collection/tt0105793', destination: '/movie/waynes-world', permanent: true },
      { source: '/movies/:collection/tt0215129', destination: '/movie/road-trip', permanent: true },
      { source: '/movies/:collection/tt0115736', destination: '/movie/bound', permanent: true },
      { source: '/movies/:collection/tt0356150', destination: '/movie/eurotrip', permanent: true },
      { source: '/movies/:collection/tt0119008', destination: '/movie/donnie-brasco', permanent: true },
      { source: '/movies/:collection/tt0190138', destination: '/movie/zoolander', permanent: true },
      { source: '/movies/:collection/tt0126886', destination: '/movie/election', permanent: true },
      { source: '/movies/:collection/tt0441773', destination: '/movie/kung-fu-panda', permanent: true },
      { source: '/movies/:collection/tt0328107', destination: '/movie/man-on-fire', permanent: true },
      { source: '/movies/:collection/tt0396269', destination: '/movie/wedding-crashers', permanent: true },
      { source: '/movies/:collection/tt0112697', destination: '/movie/clueless', permanent: true },
      { source: '/movies/:collection/tt0116483', destination: '/movie/happy-gilmore', permanent: true },
      { source: '/movies/:collection/tt0317740', destination: '/movie/the-italian-job', permanent: true },
      { source: '/movies/:collection/tt0366627', destination: '/movie/the-jacket', permanent: true },
      { source: '/movies/:collection/tt0375063', destination: '/movie/sideways', permanent: true },
      { source: '/movies/:collection/tt0206634', destination: '/movie/children-of-men', permanent: true },
      { source: '/movies/:collection/tt0090180', destination: '/movie/to-live-and-die-in-la', permanent: true },
      { source: '/movies/:collection/tt0251127', destination: '/movie/how-to-lose-a-guy-in-10-days', permanent: true },
      { source: '/movies/:collection/tt0337563', destination: '/movie/13-going-on-30', permanent: true },
      { source: '/movies/:collection/tt0892769', destination: '/movie/how-to-train-your-dragon', permanent: true },
      { source: '/movies/:collection/tt0120324', destination: '/movie/a-simple-plan', permanent: true },
      { source: '/movies/:collection/tt0104952', destination: '/movie/my-cousin-vinny', permanent: true },
      { source: '/movies/:collection/tt0156887', destination: '/movie/perfect-blue', permanent: true },
      { source: '/movies/:collection/tt0094291', destination: '/movie/wall-street', permanent: true },
      { source: '/movies/:collection/tt0074958', destination: '/movie/network', permanent: true },
      { source: '/movies/:collection/tt0088680', destination: '/movie/after-hours', permanent: true },
      { source: '/movies/:collection/tt0093010', destination: '/movie/fatal-attraction', permanent: true },
      { source: '/movies/:collection/tt0274812', destination: '/movie/secretary', permanent: true },
      { source: '/movies/:collection/tt0088258', destination: '/movie/this-is-spinal-tap', permanent: true },
      { source: '/movies/:collection/tt0071230', destination: '/movie/blazing-saddles', permanent: true },
      { source: '/movies/:collection/tt0085995', destination: '/movie/national-lampoons-vacation', permanent: true },
      { source: '/movies/:collection/tt0366551', destination: '/movie/harold-kumar-go-to-white-castle', permanent: true },
      { source: '/movies/:collection/tt1130884', destination: '/movie/shutter-island', permanent: true },
      { source: '/movies/:collection/tt0456912', destination: '/movie/a-bittersweet-life', permanent: true },
      { source: '/movies/:collection/tt0245844', destination: '/movie/the-count-of-monte-cristo', permanent: true },
      { source: '/movies/:collection/tt0353969', destination: '/movie/memories-of-murder', permanent: true },
      { source: '/movies/:collection/tt0091474', destination: '/movie/manhunter', permanent: true },
      { source: '/movies/:collection/tt0083190', destination: '/movie/thief', permanent: true },
      { source: '/movies/:collection/tt0104684', destination: '/movie/hard-boiled', permanent: true },
      { source: '/movies/:collection/tt0082846', destination: '/movie/on-golden-pond', permanent: true },
      { source: '/movies/:collection/tt0345950', destination: '/movie/the-spongebob-squarepants-movie', permanent: true },
      { source: '/movies/:collection/tt0096997', destination: '/movie/the-burbs', permanent: true },
      { source: '/movies/:collection/tt0079417', destination: '/movie/kramer-vs-kramer', permanent: true },
      { source: '/movies/:collection/tt1125849', destination: '/movie/the-wrestler', permanent: true },
      { source: '/movies/:collection/tt0094336', destination: '/movie/withnail-and-i', permanent: true },
      { source: '/movies/:collection/tt1190539', destination: '/movie/the-chaser', permanent: true },
      { source: '/movies/:collection/tt1024715', destination: '/movie/choke', permanent: true },
      { source: '/movies/:collection/tt0480669', destination: '/movie/timecrimes', permanent: true },
      { source: '/movies/:collection/tt0390384', destination: '/movie/primer', permanent: true },
      { source: '/movies/:collection/tt0082089', destination: '/movie/body-heat', permanent: true },
      { source: '/movies/:collection/tt1220719', destination: '/movie/ip-man', permanent: true },
      { source: '/movies/:collection/tt0106364', destination: '/movie/batman-mask-of-the-phantasm', permanent: true },
      { source: '/movies/:collection/tt0084707', destination: '/movie/sophies-choice', permanent: true },
      { source: '/movies/:collection/tt0412922', destination: '/movie/little-manhattan', permanent: true },
      { source: '/movies/:collection/tt0097814', destination: '/movie/kikis-delivery-service', permanent: true },
      { source: '/movies/:collection/tt0058946', destination: '/movie/the-battle-of-algiers', permanent: true },
      { source: '/movies/:collection/tt1182345', destination: '/movie/moon', permanent: true },
      { source: '/movies/:collection/tt1119646', destination: '/movie/the-hangover', permanent: true },
      { source: '/movies/:collection/tt0040725', destination: '/movie/the-red-shoes', permanent: true },
      { source: '/movies/:collection/tt1323594', destination: '/movie/despicable-me', permanent: true },
      { source: '/movies/:collection/tt0098354', destination: '/movie/society', permanent: true },
      { source: '/movies/:collection/tt1197624', destination: '/movie/law-abiding-citizen', permanent: true },
      { source: '/movies/:collection/tt0840361', destination: '/movie/the-town', permanent: true },
      { source: '/movies/:collection/tt1263670', destination: '/movie/crazy-heart', permanent: true },
      { source: '/movies/:collection/tt0091251', destination: '/movie/come-and-see', permanent: true },
      { source: '/movies/:collection/tt0110308', destination: '/movie/the-last-seduction', permanent: true },
      { source: '/movies/:collection/tt1305806', destination: '/movie/the-secret-in-their-eyes', permanent: true },
      { source: '/movies/:collection/tt0306805', destination: '/movie/deliver-us-from-eva', permanent: true },
      { source: '/movies/:collection/tt1187064', destination: '/movie/triangle', permanent: true },
      { source: '/movies/:collection/tt1375666', destination: '/movie/inception', permanent: true },
      { source: '/movies/:collection/tt1386588', destination: '/movie/the-other-guys', permanent: true },
      { source: '/movies/:collection/tt0120265', destination: '/movie/taste-of-cherry', permanent: true },
      { source: '/movies/:collection/tt0485947', destination: '/movie/mr-nobody', permanent: true },
      { source: '/movies/:collection/tt0123948', destination: '/movie/cure', permanent: true },
      { source: '/movies/:collection/tt0106856', destination: '/movie/falling-down', permanent: true },
      { source: '/movies/:collection/tt0095705', destination: '/movie/the-naked-gun-from-the-files-of-police-squad', permanent: true },
      { source: '/movies/:collection/tt0120382', destination: '/movie/the-truman-show', permanent: true },
      { source: '/movies/:collection/tt0115940', destination: '/movie/a-summers-tale', permanent: true },
      { source: '/movies/:collection/tt0113824', destination: '/movie/whisper-of-the-heart', permanent: true },
      { source: '/movies/:collection/tt1285016', destination: '/movie/the-social-network', permanent: true },
      { source: '/movies/:collection/tt0078444', destination: '/movie/an-unmarried-woman', permanent: true },
      { source: '/movies/:collection/tt0247745', destination: '/movie/super-troopers', permanent: true },
      { source: '/movies/:collection/tt1306980', destination: '/movie/5050', permanent: true },
      { source: '/movies/:collection/tt0150980', destination: '/movie/the-housemaid', permanent: true },
      { source: '/movies/:collection/tt0477080', destination: '/movie/unstoppable', permanent: true },
      { source: '/movies/:collection/tt1542344', destination: '/movie/127-hours', permanent: true },
      { source: '/movies/:collection/tt0947798', destination: '/movie/black-swan', permanent: true },
      { source: '/movies/:collection/tt1216496', destination: '/movie/mother', permanent: true },
      { source: '/movies/:collection/tt1192628', destination: '/movie/rango', permanent: true },
      { source: '/movies/:collection/tt0945513', destination: '/movie/source-code', permanent: true },
      { source: '/movies/:collection/tt1120985', destination: '/movie/blue-valentine', permanent: true },
      { source: '/movies/:collection/tt1255953', destination: '/movie/incendies', permanent: true },
      { source: '/movies/:collection/tt1591095', destination: '/movie/insidious', permanent: true },
      { source: '/movies/:collection/tt1454468', destination: '/movie/gravity', permanent: true },
      { source: '/movies/:collection/tt1588170', destination: '/movie/i-saw-the-devil', permanent: true },
      { source: '/movies/:collection/tt1570728', destination: '/movie/crazy-stupid-love', permanent: true },
      { source: '/movies/:collection/tt1527788', destination: '/movie/the-man-from-nowhere', permanent: true },
      { source: '/movies/:collection/tt1563738', destination: '/movie/one-day', permanent: true },
      { source: '/movies/:collection/tt1219289', destination: '/movie/limitless', permanent: true },
      { source: '/movies/:collection/tt1408101', destination: '/movie/star-trek-into-darkness', permanent: true },
      { source: '/movies/:collection/tt1590089', destination: '/movie/confessions', permanent: true },
      { source: '/movies/:collection/tt1478338', destination: '/movie/bridesmaids', permanent: true },
      { source: '/movies/:collection/tt1229238', destination: '/movie/mission-impossible-ghost-protocol', permanent: true },
      { source: '/movies/:collection/tt1832382', destination: '/movie/a-separation', permanent: true },
      { source: '/movies/:collection/tt1758692', destination: '/movie/like-crazy', permanent: true },
      { source: '/movies/:collection/tt1318514', destination: '/movie/rise-of-the-planet-of-the-apes', permanent: true },
      { source: '/movies/:collection/tt0780504', destination: '/movie/drive', permanent: true },
      { source: '/movies/:collection/tt1568346', destination: '/movie/the-girl-with-the-dragon-tattoo', permanent: true },
      { source: '/movies/:collection/tt1622029', destination: '/movie/oz-the-great-and-powerful', permanent: true },
      { source: '/movies/:collection/tt0816711', destination: '/movie/world-war-z', permanent: true },
      { source: '/movies/:collection/tt1670345', destination: '/movie/now-you-see-me', permanent: true },
      { source: '/movies/:collection/tt0790724', destination: '/movie/jack-reacher', permanent: true },
      { source: '/movies/:collection/tt1723811', destination: '/movie/shame', permanent: true },
      { source: '/movies/:collection/tt2024544', destination: '/movie/12-years-a-slave', permanent: true },
      { source: '/movies/:collection/tt1392190', destination: '/movie/mad-max-fury-road', permanent: true },
      { source: '/movies/:collection/tt0837562', destination: '/movie/hotel-transylvania', permanent: true },
      { source: '/movies/:collection/tt1649419', destination: '/movie/the-impossible', permanent: true },
      { source: '/movies/:collection/tt1922777', destination: '/movie/sinister', permanent: true },
      { source: '/movies/:collection/tt1646971', destination: '/movie/how-to-train-your-dragon-2', permanent: true },
      { source: '/movies/:collection/tt1659337', destination: '/movie/the-perks-of-being-a-wallflower', permanent: true },
      { source: '/movies/:collection/tt1065073', destination: '/movie/boyhood', permanent: true },
      { source: '/movies/:collection/tt1450321', destination: '/movie/filth', permanent: true },
      { source: '/movies/:collection/tt2226417', destination: '/movie/insidious-chapter-2', permanent: true },
      { source: '/movies/:collection/tt1979320', destination: '/movie/rush', permanent: true },
      { source: '/movies/:collection/tt1441395', destination: '/movie/under-the-skin', permanent: true },
      { source: '/movies/:collection/tt1959490', destination: '/movie/the-hunger-games-catching-fire', permanent: true },
      { source: '/movies/:collection/tt0993846', destination: '/movie/the-wolf-of-wall-street', permanent: true },
      { source: '/movies/:collection/tt1706620', destination: '/movie/snowpiercer', permanent: true },
      { source: '/movies/:collection/tt2103281', destination: '/movie/dawn-of-the-planet-of-the-apes', permanent: true },
      { source: '/movies/:collection/tt2194499', destination: '/movie/about-time', permanent: true },
      { source: '/movies/:collection/tt2209418', destination: '/movie/before-midnight', permanent: true },
      { source: '/movies/:collection/tt0070644', destination: '/movie/scenes-from-a-marriage', permanent: true },
      { source: '/movies/:collection/tt1631867', destination: '/movie/edge-of-tomorrow', permanent: true },
      { source: '/movies/:collection/tt1457767', destination: '/movie/the-conjuring', permanent: true },
      { source: '/movies/:collection/tt1825157', destination: '/movie/the-double', permanent: true },
      { source: '/movies/:collection/tt1392214', destination: '/movie/prisoners', permanent: true },
      { source: '/movies/:collection/tt0790636', destination: '/movie/dallas-buyers-club', permanent: true },
      { source: '/movies/:collection/tt2278871', destination: '/movie/blue-is-the-warmest-color', permanent: true },
      { source: '/movies/:collection/tt0455944', destination: '/movie/the-equalizer', permanent: true },
      { source: '/movies/:collection/tt0816692', destination: '/movie/interstellar', permanent: true },
      { source: '/movies/:collection/tt2510894', destination: '/movie/hotel-transylvania-2', permanent: true },
      { source: '/movies/:collection/tt2386490', destination: '/movie/how-to-train-your-dragon-the-hidden-world', permanent: true },
      { source: '/movies/:collection/tt2381111', destination: '/movie/brooklyn', permanent: true },
      { source: '/movies/:collection/tt2265171', destination: '/movie/the-raid-2', permanent: true },
      { source: '/movies/:collection/tt2316411', destination: '/movie/enemy', permanent: true },
      { source: '/movies/:collection/tt2820466', destination: '/movie/justice-league-the-flashpoint-paradox', permanent: true },
      { source: '/movies/:collection/tt2562232', destination: '/movie/birdman', permanent: true },
      { source: '/movies/:collection/tt2397535', destination: '/movie/predestination', permanent: true },
      { source: '/movies/:collection/tt2802144', destination: '/movie/kingsman-the-secret-service', permanent: true },
      { source: '/movies/:collection/tt2267998', destination: '/movie/gone-girl', permanent: true },
      { source: '/movies/:collection/tt2322441', destination: '/movie/fifty-shades-of-grey', permanent: true },
      { source: '/movies/:collection/tt2866360', destination: '/movie/coherence', permanent: true },
      { source: '/movies/:collection/tt1809398', destination: '/movie/unbroken', permanent: true },
      { source: '/movies/:collection/tt3253930', destination: '/movie/marshland', permanent: true },
      { source: '/movies/:collection/tt2321549', destination: '/movie/the-babadook', permanent: true },
      { source: '/movies/:collection/tt2872718', destination: '/movie/nightcrawler', permanent: true },
      { source: '/movies/:collection/tt3398268', destination: '/movie/when-marnie-was-there', permanent: true },
      { source: '/movies/:collection/tt2582802', destination: '/movie/whiplash', permanent: true },
      { source: '/movies/:collection/tt2911666', destination: '/movie/john-wick', permanent: true },
      { source: '/movies/:collection/tt3416742', destination: '/movie/what-we-do-in-the-shadows', permanent: true },
      { source: '/movies/:collection/tt3464902', destination: '/movie/the-lobster', permanent: true },
      { source: '/movies/:collection/tt2402927', destination: '/movie/carol', permanent: true },
      { source: '/movies/:collection/tt3065204', destination: '/movie/the-conjuring-2', permanent: true },
      { source: '/movies/:collection/tt3315342', destination: '/movie/logan', permanent: true },
      { source: '/movies/:collection/tt3170832', destination: '/movie/room', permanent: true },
      { source: '/movies/:collection/tt0470752', destination: '/movie/ex-machina', permanent: true },
      { source: '/movies/:collection/tt3397884', destination: '/movie/sicario', permanent: true },
      { source: '/movies/:collection/tt1020072', destination: '/movie/selma', permanent: true },
      { source: '/movies/:collection/tt3450958', destination: '/movie/war-for-the-planet-of-the-apes', permanent: true },
      { source: '/movies/:collection/tt1663202', destination: '/movie/the-revenant', permanent: true },
      { source: '/movies/:collection/tt3659388', destination: '/movie/the-martian', permanent: true },
      { source: '/movies/:collection/tt4016934', destination: '/movie/the-handmaiden', permanent: true },
      { source: '/movies/:collection/tt1655441', destination: '/movie/the-age-of-adaline', permanent: true },
      { source: '/movies/:collection/tt2798920', destination: '/movie/annihilation', permanent: true },
      { source: '/movies/:collection/tt4160708', destination: '/movie/dont-breathe', permanent: true },
      { source: '/movies/:collection/tt4263482', destination: '/movie/the-witch', permanent: true },
      { source: '/movies/:collection/tt3915174', destination: '/movie/puss-in-boots-the-last-wish', permanent: true },
      { source: '/movies/:collection/tt1596363', destination: '/movie/the-big-short', permanent: true },
      { source: '/movies/:collection/tt2119532', destination: '/movie/hacksaw-ridge', permanent: true },
      { source: '/movies/:collection/tt4116284', destination: '/movie/the-lego-batman-movie', permanent: true },
      { source: '/movies/:collection/tt5715874', destination: '/movie/the-killing-of-a-sacred-deer', permanent: true },
      { source: '/movies/:collection/tt2543164', destination: '/movie/arrival', permanent: true },
      { source: '/movies/:collection/tt1179933', destination: '/movie/10-cloverfield-lane', permanent: true },
      { source: '/movies/:collection/tt1856101', destination: '/movie/blade-runner-2049', permanent: true },
      { source: '/movies/:collection/tt4465566', destination: '/movie/fifty-shades-freed', permanent: true },
      { source: '/movies/:collection/tt2582782', destination: '/movie/hell-or-high-water', permanent: true },
      { source: '/movies/:collection/tt3890160', destination: '/movie/baby-driver', permanent: true },
      { source: '/movies/:collection/tt4465564', destination: '/movie/fifty-shades-darker', permanent: true },
      { source: '/movies/:collection/tt1396484', destination: '/movie/it', permanent: true },
      { source: '/movies/:collection/tt1517268', destination: '/movie/barbie', permanent: true },
      { source: '/movies/:collection/tt4912910', destination: '/movie/mission-impossible-fallout', permanent: true },
      { source: '/movies/:collection/tt1034415', destination: '/movie/suspiria', permanent: true },
      { source: '/movies/:collection/tt1745960', destination: '/movie/top-gun-maverick', permanent: true },
      { source: '/movies/:collection/tt1213641', destination: '/movie/first-man', permanent: true },
      { source: '/movies/:collection/tt5168192', destination: '/movie/i-daniel-blake', permanent: true },
      { source: '/movies/:collection/tt5083738', destination: '/movie/the-favourite', permanent: true },
      { source: '/movies/:collection/tt4975722', destination: '/movie/moonlight', permanent: true },
      { source: '/movies/:collection/tt4972582', destination: '/movie/split', permanent: true },
      { source: '/movies/:collection/tt3758172', destination: '/movie/jungle', permanent: true },
      { source: '/movies/:collection/tt4925292', destination: '/movie/lady-bird', permanent: true },
      { source: '/movies/:collection/tt2671706', destination: '/movie/fences', permanent: true },
      { source: '/movies/:collection/tt5649144', destination: '/movie/the-florida-project', permanent: true },
      { source: '/movies/:collection/tt5362988', destination: '/movie/wind-river', permanent: true },
      { source: '/movies/:collection/tt5140878', destination: '/movie/annabelle-creation', permanent: true },
      { source: '/movies/:collection/tt3289956', destination: '/movie/the-autopsy-of-jane-doe', permanent: true },
      { source: '/movies/:collection/tt4003440', destination: '/movie/the-house-that-jack-built', permanent: true },
      { source: '/movies/:collection/tt5726616', destination: '/movie/call-me-by-your-name', permanent: true },
      { source: '/movies/:collection/tt5715874', destination: '/movie/the-killing-of-a-sacred-deer', permanent: true },
      { source: '/movies/:collection/tt4686844', destination: '/movie/the-death-of-stalin', permanent: true },
      { source: '/movies/:collection/tt4857264', destination: '/movie/the-invisible-guest', permanent: true },
      { source: '/movies/:collection/tt1877830', destination: '/movie/the-batman', permanent: true },
      { source: '/movies/:collection/tt5052448', destination: '/movie/get-out', permanent: true },
      { source: '/movies/:collection/tt2935510', destination: '/movie/ad-astra', permanent: true },
      { source: '/movies/:collection/tt4846232', destination: '/movie/good-time', permanent: true },
      { source: '/movies/:collection/tt3986820', destination: '/movie/the-endless', permanent: true },
      { source: '/movies/:collection/tt6324278', destination: '/movie/abominable', permanent: true },
      { source: '/movies/:collection/tt5672290', destination: '/movie/the-first-omen', permanent: true },
      { source: '/movies/:collection/tt1160419', destination: '/movie/dune', permanent: true },
      { source: '/movies/:collection/tt5257726', destination: '/movie/hey-arnold-the-jungle-movie', permanent: true },
      { source: '/movies/:collection/tt5814060', destination: '/movie/the-nun', permanent: true },
      { source: '/movies/:collection/tt6644200', destination: '/movie/a-quiet-place', permanent: true },
      { source: '/movies/:collection/tt3794354', destination: '/movie/sonic-the-hedgehog', permanent: true },
      { source: '/movies/:collection/tt7160372', destination: '/movie/the-zone-of-interest', permanent: true },
      { source: '/movies/:collection/tt5727208', destination: '/movie/uncut-gems', permanent: true },
      { source: '/movies/:collection/tt7286456', destination: '/movie/joker', permanent: true },
      { source: '/movies/:collection/tt7339248', destination: '/movie/the-art-of-self-defense', permanent: true },
      { source: '/movies/:collection/tt7282468', destination: '/movie/burning', permanent: true },
      { source: '/movies/:collection/tt7653254', destination: '/movie/marriage-story', permanent: true },
      { source: '/movies/:collection/tt7784604', destination: '/movie/hereditary', permanent: true },
      { source: '/movies/:collection/tt6751668', destination: '/movie/parasite', permanent: true },
      { source: '/movies/:collection/tt7547410', destination: '/movie/dora-and-the-lost-city-of-gold', permanent: true },
      { source: '/movies/:collection/tt6499752', destination: '/movie/upgrade', permanent: true },
      { source: '/movies/:collection/tt7984734', destination: '/movie/the-lighthouse', permanent: true },
      { source: '/movies/:collection/tt8075192', destination: '/movie/shoplifters', permanent: true },
      { source: '/movies/:collection/tt9066658', destination: '/movie/boss-level', permanent: true },
      { source: '/movies/:collection/tt5867314', destination: '/movie/the-empty-man', permanent: true },
      { source: '/movies/:collection/tt8350360', destination: '/movie/annabelle-comes-home', permanent: true },
      { source: '/movies/:collection/tt8772262', destination: '/movie/midsommar', permanent: true },
      { source: '/movies/:collection/tt8579674', destination: '/movie/1917', permanent: true },
      { source: '/movies/:collection/tt8760708', destination: '/movie/m3gan', permanent: true },
      { source: '/movies/:collection/tt10515852', destination: '/movie/steven-universe-the-movie', permanent: true },
      { source: '/movies/:collection/tt8781414', destination: '/movie/freaks', permanent: true },
      { source: '/movies/:collection/tt6710474', destination: '/movie/everything-everywhere-all-at-once', permanent: true },
      { source: '/movies/:collection/tt8999762', destination: '/movie/the-brutalist', permanent: true },
      { source: '/movies/:collection/tt9362722', destination: '/movie/spider-man-across-the-spider-verse', permanent: true },
      { source: '/movies/:collection/tt9484998', destination: '/movie/palm-springs', permanent: true },
      { source: '/movies/:collection/tt7798646', destination: '/movie/the-photograph', permanent: true },
      { source: '/movies/:collection/tt8963708', destination: '/movie/and-then-we-danced', permanent: true },
      { source: '/movies/:collection/tt10272386', destination: '/movie/the-father', permanent: true },
      { source: '/movies/:collection/tt8589698', destination: '/movie/tmnt-mutant-mayhem', permanent: true },
      { source: '/movies/:collection/tt8228288', destination: '/movie/the-platform', permanent: true },
      { source: '/movies/:collection/tt10886166', destination: '/movie/365-days', permanent: true },
      { source: '/movies/:collection/tt13238346', destination: '/movie/past-lives', permanent: true },
      { source: '/movies/:collection/tt11813216', destination: '/movie/the-banshees-of-inisherin', permanent: true },
      { source: '/movies/:collection/tt12412888', destination: '/movie/sonic-the-hedgehog-2', permanent: true },
      { source: '/movies/:collection/tt11832046', destination: '/movie/paw-patrol-the-movie', permanent: true },
      { source: '/movies/:collection/tt10473036', destination: '/movie/the-amazing-maurice', permanent: true },
      { source: '/movies/:collection/tt15239678', destination: '/movie/dune-part-two', permanent: true },
      { source: '/movies/:collection/tt12299608', destination: '/movie/mickey-17', permanent: true },
      { source: '/movies/:collection/tt12262116', destination: '/movie/13-lives', permanent: true },
      { source: '/movies/:collection/tt12300742', destination: '/movie/bugonia', permanent: true },
      { source: '/movies/:collection/tt12477480', destination: '/movie/decision-to-leave', permanent: true },
      { source: '/movies/:collection/tt13345606', destination: '/movie/evil-dead-rise', permanent: true },
      { source: '/movies/:collection/tt6689876', destination: '/movie/twisters', permanent: true },
      { source: '/movies/:collection/tt12593682', destination: '/movie/bullet-train', permanent: true },
      { source: '/movies/:collection/tt16300962', destination: '/movie/when-evil-lurks', permanent: true },
      { source: '/movies/:collection/tt1684562', destination: '/movie/the-fall-guy', permanent: true },
      { source: '/movies/:collection/tt13374522', destination: '/movie/mrs-harris-goes-to-paris', permanent: true },
      { source: '/movies/:collection/tt7144666', destination: '/movie/the-black-phone', permanent: true },
      { source: '/movies/:collection/tt13352968', destination: '/movie/good-luck-to-you-leo-grande', permanent: true },
      { source: '/movies/:collection/tt11851548', destination: '/movie/orphan-first-kill', permanent: true },
      { source: '/movies/:collection/tt22357594', destination: '/movie/a-quiet-place-day-one', permanent: true },
      { source: '/movies/:collection/tt10954984', destination: '/movie/nope', permanent: true },
      { source: '/movies/:collection/tt11866324', destination: '/movie/prey', permanent: true },
      { source: '/movies/:collection/tt13650540', destination: '/movie/if-you-were-the-last', permanent: true },
      { source: '/movies/:collection/tt10696784', destination: '/movie/fireheart', permanent: true },
      { source: '/movies/:collection/tt13833688', destination: '/movie/the-whale', permanent: true },
      { source: '/movies/:collection/tt12037194', destination: '/movie/furiosa-a-mad-max-saga', permanent: true },
      { source: '/movies/:collection/tt13403046', destination: '/movie/fresh', permanent: true },
      { source: '/movies/:collection/tt12361974', destination: '/movie/zack-snyders-justice-league', permanent: true },
      { source: '/movies/:collection/tt14230458', destination: '/movie/poor-things', permanent: true },
      { source: '/movies/:collection/tt14208870', destination: '/movie/the-fabelmans', permanent: true },
      { source: '/movies/:collection/tt14369780', destination: '/movie/lady-chatterleys-lover', permanent: true },
      { source: '/movies/:collection/tt16537332', destination: '/movie/no-one-will-save-you', permanent: true },
      { source: '/movies/:collection/tt4772188', destination: '/movie/flow', permanent: true },
      { source: '/movies/:collection/tt14807308', destination: '/movie/she-said', permanent: true },
      { source: '/movies/:collection/tt13429870', destination: '/movie/robot-dreams', permanent: true },
      { source: '/movies/:collection/tt21064584', destination: '/movie/the-iron-claw', permanent: true },
      { source: '/movies/:collection/tt13423600', destination: '/movie/a-thousand-and-one', permanent: true },
      { source: '/movies/:collection/tt15398776', destination: '/movie/oppenheimer', permanent: true },
      { source: '/movies/:collection/tt15474916', destination: '/movie/smile', permanent: true },
      { source: '/movies/:collection/tt15837338', destination: '/movie/paw-patrol-the-mighty-movie', permanent: true },
      { source: '/movies/:collection/tt9660502', destination: '/movie/close', permanent: true },
      { source: '/movies/:collection/tt16277242', destination: '/movie/society-of-the-snow', permanent: true },
      { source: '/movies/:collection/tt15791034', destination: '/movie/barbarian', permanent: true },
      { source: '/movies/:collection/tt17009710', destination: '/movie/anatomy-of-a-fall', permanent: true },
      { source: '/movies/:collection/tt18550182', destination: '/movie/rmn', permanent: true },
      { source: '/movies/:collection/tt17351924', destination: '/movie/saltburn', permanent: true },
      { source: '/movies/:collection/tt16426418', destination: '/movie/challengers', permanent: true },
      { source: '/movies/:collection/tt14966898', destination: '/movie/late-night-with-the-devil', permanent: true },
      { source: '/movies/:collection/tt18259086', destination: '/movie/sonic-the-hedgehog-3', permanent: true },
      { source: '/movies/:collection/tt19770238', destination: '/movie/aftersun', permanent: true },
      { source: '/movies/:collection/tt27503384', destination: '/movie/perfect-days', permanent: true },
      { source: '/movies/:collection/tt21376880', destination: '/movie/theater-camp', permanent: true },
      { source: '/movies/:collection/tt21192142', destination: '/movie/all-of-us-strangers', permanent: true },
      { source: '/movies/:collection/tt13097932', destination: '/movie/one-life', permanent: true },
      { source: '/movies/:collection/tt21440780', destination: '/movie/how-to-blow-up-a-pipeline', permanent: true },
      { source: '/movies/:collection/tt21823606', destination: '/movie/a-real-pain', permanent: true },
      { source: '/movies/:collection/tt21867434', destination: '/movie/blackberry', permanent: true },
      { source: '/movies/:collection/tt22375054', destination: '/movie/strange-darling', permanent: true },
      { source: '/movies/:collection/tt15893750', destination: '/movie/rye-lane', permanent: true },
      { source: '/movies/:collection/tt23561236', destination: '/movie/american-fiction', permanent: true },
      { source: '/movies/:collection/tt28607951', destination: '/movie/anora', permanent: true },
      { source: '/movies/:collection/tt30144839', destination: '/movie/one-battle-after-another', permanent: true },
      { source: '/movies/:collection/tt29268110', destination: '/movie/smile-2', permanent: true },
      { source: '/movies/:collection/tt27196021', destination: '/movie/small-things-like-these', permanent: true },
      { source: '/movies/:collection/tt28479262', destination: '/movie/sing-sing', permanent: true },
      { source: '/movies/:collection/tt28323620', destination: '/movie/ddi', permanent: true },
      { source: '/movies/:collection/tt27553096', destination: '/movie/my-friend-the-penguin', permanent: true },
      { source: '/movies/:collection/tt30321095', destination: '/movie/ghostlight', permanent: true },
      { source: '/movies/:collection/tt26470109', destination: '/movie/oddity', permanent: true },
      { source: '/movies/:collection/tt23468450', destination: '/movie/longlegs', permanent: true },
      { source: '/movies/:collection/tt31193180', destination: '/movie/sinners', permanent: true },
      { source: '/movies/:collection/tt31322753', destination: '/movie/twinless', permanent: true },
      { source: '/movies/:collection/tt32768323', destination: '/movie/the-assessment', permanent: true },
      { source: '/movies/:collection/tt32916440', destination: '/movie/marty-supreme', permanent: true },
      { source: '/movies/:collection/tt36463894', destination: '/movie/predator-killer-of-killers', permanent: true }
    ];
  },

  // ✅ BUILD CACHE
  onDemandEntries: {
    maxInactiveAge: 60 * 1000,
    pagesBufferLength: 5,
  },
};

module.exports = nextConfig;