

export const metadata = {
  
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '../styles/globals.css'

import './globals.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
