// src/utils/bannedHorrorMoodData.js
export const bannedHorrorMoodData = {
    73861: { color: "#ff4d4d", data: [ { time: 10, intensity: 30, label: "Initial Setup", mood: "dialogue" }, { time: 40, intensity: 80, label: "The Performance Begins", mood: "tense" }, { time: 60, intensity: 100, label: "Extreme Violence", mood: "climax" }, { time: 90, intensity: 95, label: "Final Act", mood: "twist" } ]},
    8689: { color: "#ff4d4d", data: [ { time: 20, intensity: 40, label: "Found Footage", mood: "tense" }, { time: 50, intensity: 90, label: "Real Animal Harm", mood: "action" }, { time: 70, intensity: 100, label: "Cannibal Encounter", mood: "climax" } ]},
    5336: { color: "#ff4d4d", data: [ { time: 30, intensity: 50, label: "The Setup", mood: "dialogue" }, { time: 60, intensity: 85, label: "Circle of Manias", mood: "tense" }, { time: 90, intensity: 100, label: "Extreme Sadism", mood: "climax" }, { time: 110, intensity: 70, label: "Ending", mood: "twist" } ]},
    74997: { color: "#ff4d4d", data: [ { time: 15, intensity: 50, label: "The Abduction", mood: "tense" }, { time: 45, intensity: 95, label: "The 'Procedure'", mood: "climax" }, { time: 70, intensity: 100, label: "Full Sequence", mood: "action" } ]},
    9539: { color: "#ff4d4d", data: [ { time: 20, intensity: 60, label: "The Escape Attempt", mood: "action" }, { time: 50, intensity: 90, label: "Systematic Torture", mood: "tense" }, { time: 80, intensity: 100, label: "The Final Stage", mood: "climax" }, { time: 90, intensity: 80, label: "Transcendence", mood: "twist" } ]},
   25998: { color: "#ff4d4d", data: [ { time: 10, intensity: 40, label: "Historical Context", mood: "dialogue" }, { time: 40, intensity: 90, label: "Human Experiments", mood: "climax" }, { time: 70, intensity: 100, label: "Autopsy Scene", mood: "action" } ]},
    84520: { color: "#ff4d4d", data: [ { time: 10, intensity: 50, label: "The Abduction", mood: "tense" }, { time: 30, intensity: 80, label: "Psychological Games", mood: "conflict" }, { time: 60, intensity: 100, label: "The Climax", mood: "climax" } ]},
 27297: { color: "#ff4d4d", data: [ { time: 5, intensity: 60, label: "The Kidnapping", mood: "tense" }, { time: 30, intensity: 95, label: "Prolonged Torture", mood: "climax" }, { time: 60, intensity: 80, label: "Escape Attempt", mood: "action" } ]},
    15516: { color: "#ff4d4d", data: [ { time: 20, intensity: 70, label: "The Attack", mood: "action" }, { time: 50, intensity: 85, label: "Humiliation", mood: "tense" }, { time: 70, intensity: 100, label: "Parental Revenge", mood: "climax" } ]},
    12237: { color: "#ff4d4d", data: [ { time: 10, intensity: 50, label: "Compilation Start", mood: "event" }, { time: 45, intensity: 80, label: "Graphic Footage", mood: "action" }, { time: 80, intensity: 70, label: "Staged vs. Real", mood: "tense" } ]},
};
