// utils/crimeThrillerMovieData.js - BEST CRIME THRILLER COLLECTION ✅

export const CRIME_THRILLER_MOVIES = [
  {
    imdbID: 'tt0113277',
    tmdbId: 949,
    title: 'Heat',
    director: 'Michael Mann',
    genre: 'Crime, Drama, Thriller',
    year: 1995,
    runtime: '170 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Al Pacino', 'Robert De Niro', 'Val Kilmer'],
    boxOffice: '$187.4 million',
    budget: '$60 million',
    synopsis: "Master thief Neil McCauley (Robert De Niro) and his crew pull off high-stakes heists with military precision, while obsessive LAPD detective Vincent Hanna (Al Pacino) tracks their every move. This is the ultimate cat-and-mouse crime epic featuring the iconic coffee shop confrontation between two legends. Mann's masterpiece explores the thin line between cop and criminal in LA's neon-lit underworld.",
    poster: '/path/to/heat-poster.jpg',
    backdrop: '/path/to/heat-backdrop.jpg',
    backdrop_path: '/path/to/heat-backdrop.jpg',
    poster_path: '/path/to/heat-poster.jpg',
    scenes: [
      { time: 38, intensity: 52, label: 'Coffee Shop Meeting', color: '#b91c1c' },
      { time: 87, intensity: 68, label: 'Bank Heist', color: '#f87171' },
      { time: 134, intensity: 88, label: 'Downtown Shootout', color: '#fbbf24' },
      { time: 152, intensity: 93, label: 'Final Chase', color: '#fde68a' },
      { time: 167, intensity: 96, label: 'Airport Showdown', color: '#dc2626' }
    ],
    suspenseIntensity: 96,
    dominantColor: '#1a2b3c',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0119488',
    tmdbId: 11632,
    title: 'L.A. Confidential',
    director: 'Curtis Hanson',
    genre: 'Crime, Drama, Mystery',
    year: 1997,
    runtime: '138 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Kevin Spacey', 'Russell Crowe', 'Guy Pearce'],
    boxOffice: '$126.2 million',
    budget: '$35 million',
    synopsis: "In 1950s Los Angeles, three very different LAPD officers—a celebrity cop, a brutal enforcer, and an ambitious detective—become entangled in a web of sex, corruption, and murder. This neo-noir masterpiece peels back the glamorous veneer of Hollywood's golden age to reveal the rot beneath.",
    poster: '/path/to/laconfidential-poster.jpg',
    backdrop: '/path/to/laconfidential-backdrop.jpg',
    backdrop_path: '/path/to/laconfidential-backdrop.jpg',
    poster_path: '/path/to/laconfidential-poster.jpg',
    scenes: [
      { time: 22, intensity: 48, label: 'Night Owl Massacre', color: '#b91c1c' },
      { time: 58, intensity: 62, label: 'Investigation Begins', color: '#f87171' },
      { time: 95, intensity: 75, label: 'Conspiracy Uncovered', color: '#fbbf24' },
      { time: 121, intensity: 86, label: 'Victory Motel', color: '#fde68a' },
      { time: 134, intensity: 94, label: 'Final Shootout', color: '#dc2626' }
    ],
    suspenseIntensity: 94,
    dominantColor: '#8b6914',
    dna: { Crime: 45, Mystery: 35, Drama: 20 },
    sensitiveScenes: [
      { start: "47:15", end: "47:45", description: "Nudity (woman)" },
      { start: "1:12:30", end: "1:13:10", description: "Sex scene" }
    ]
  },
  {
    imdbID: 'tt0477348',
    tmdbId: 6977,
    title: 'No Country for Old Men',
    director: 'Coen Brothers',
    genre: 'Crime, Drama, Thriller',
    year: 2007,
    runtime: '122 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'],
    boxOffice: '$171.6 million',
    budget: '$25 million',
    synopsis: "A hunter stumbles upon a drug deal gone wrong in the Texas desert and makes off with $2 million in cash. But his decision unleashes Anton Chigurh (Javier Bardem)—a remorseless, philosophizing hitman with a captive bolt pistol and a coin for making life-or-death decisions. This Coen Brothers masterpiece is a meditation on fate, violence, and the changing face of evil in modern America.",
    poster: '/path/to/nocountry-poster.jpg',
    backdrop: '/path/to/nocountry-backdrop.jpg',
    backdrop_path: '/path/to/nocountry-backdrop.jpg',
    poster_path: '/path/to/nocountry-poster.jpg',
    scenes: [
      { time: 15, intensity: 60, label: 'Coin Toss', color: '#b91c1c' },
      { time: 41, intensity: 73, label: 'Motel Shootout', color: '#f87171' },
      { time: 68, intensity: 82, label: 'Desert Standoff', color: '#fbbf24' },
      { time: 92, intensity: 89, label: 'The Decision', color: '#fde68a' },
      { time: 115, intensity: 95, label: 'Inevitable Fate', color: '#dc2626' }
    ],
    suspenseIntensity: 95,
    dominantColor: '#865c07',
    dna: { Thriller: 50, Crime: 35, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0443706',
    tmdbId: 1949,
    title: 'Zodiac',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 2007,
    runtime: '157 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.'],
    boxOffice: '$84.8 million',
    budget: '$65 million',
    synopsis: "San Francisco, late 1960s: A serial killer who calls himself Zodiac begins a reign of terror, sending cryptic letters and ciphers to newspapers. As the body count rises, a cartoonist (Jake Gyllenhaal), a journalist (Robert Downey Jr.), and detectives (Mark Ruffalo) become consumed by the obsessive hunt. Fincher's meticulous procedural explores the psychological toll of an unsolved case that haunts for decades.",
    poster: '/path/to/zodiac-poster.jpg',
    backdrop: '/path/to/zodiac-backdrop.jpg',
    backdrop_path: '/path/to/zodiac-backdrop.jpg',
    poster_path: '/path/to/zodiac-poster.jpg',
    scenes: [
      { time: 18, intensity: 45, label: 'First Murder', color: '#b91c1c' },
      { time: 52, intensity: 58, label: 'Cipher Decoded', color: '#f87171' },
      { time: 98, intensity: 71, label: 'Basement Scene', color: '#fbbf24' },
      { time: 132, intensity: 80, label: 'Lake Berryessa', color: '#fde68a' },
      { time: 149, intensity: 88, label: 'Hardware Store', color: '#dc2626' }
    ],
    suspenseIntensity: 88,
    dominantColor: '#2d3e50',
    dna: { Crime: 45, Mystery: 40, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1392214',
    tmdbId: 146233,
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    genre: 'Crime, Drama, Mystery',
    year: 2013,
    runtime: '153 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'],
    boxOffice: '$122.1 million',
    budget: '$46 million',
    synopsis: "When his six-year-old daughter vanishes, a desperate father (Hugh Jackman) takes the law into his own hands, kidnapping and torturing the man he believes is responsible. Meanwhile, a detective (Jake Gyllenhaal) races to solve the case before the father crosses a moral point of no return. This visceral thriller asks: How far would you go to protect your family?",
    poster: '/path/to/prisoners-poster.jpg',
    backdrop: '/path/to/prisoners-backdrop.jpg',
    backdrop_path: '/path/to/prisoners-backdrop.jpg',
    poster_path: '/path/to/prisoners-poster.jpg',
    scenes: [
      { time: 20, intensity: 58, label: 'Abduction', color: '#a11515' },
      { time: 49, intensity: 75, label: 'First Search', color: '#f87171' },
      { time: 93, intensity: 82, label: 'Torture', color: '#fbbf24' },
      { time: 120, intensity: 90, label: 'Maze Hints', color: '#fde68a' },
      { time: 145, intensity: 96, label: 'Buried Alive', color: '#dc2626' }
    ],
    suspenseIntensity: 96,
    dominantColor: '#042258',
    dna: { Crime: 45, Thriller: 40, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0114369',
    tmdbId: 807,
    title: 'The Usual Suspects',
    director: 'Bryan Singer',
    genre: 'Crime, Mystery, Thriller',
    year: 1995,
    runtime: '106 min',
    ageRating: 'R',
    rating: 8.5,
    cast: ['Kevin Spacey', 'Gabriel Byrne', 'Benicio Del Toro'],
    boxOffice: '$34.0 million',
    budget: '$6 million',
    synopsis: "A botched robbery leaves 27 dead and a ship in flames. Customs agent Dave Kujan interrogates the sole survivor, a crippled con man named Verbal Kint (Kevin Spacey), who spins an intricate tale of crime, betrayal, and a mythical crime lord named Keyser Söze. This neo-noir features one of cinema's most iconic twist endings.",
    poster: '/path/to/usualsuspects-poster.jpg',
    backdrop: '/path/to/usualsuspects-backdrop.jpg',
    backdrop_path: '/path/to/usualsuspects-backdrop.jpg',
    poster_path: '/path/to/usualsuspects-poster.jpg',
    scenes: [
      { time: 8, intensity: 38, label: 'Police Lineup', color: '#b91c1c' },
      { time: 34, intensity: 55, label: 'Heist Story', color: '#f87171' },
      { time: 62, intensity: 67, label: 'Keyser Söze', color: '#fbbf24' },
      { time: 89, intensity: 78, label: 'Ship Explosion', color: '#fde68a' },
      { time: 103, intensity: 97, label: 'The Greatest Trick', color: '#dc2626' }
    ],
    suspenseIntensity: 97,
    dominantColor: '#1f2d3d',
    dna: { Crime: 50, Mystery: 35, Thriller: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0327056',
    tmdbId: 322,
    title: 'Mystic River',
    director: 'Clint Eastwood',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '138 min',
    ageRating: 'R',
    rating: 7.9,
    cast: ['Sean Penn', 'Tim Robbins', 'Kevin Bacon'],
    boxOffice: '$156.6 million',
    budget: '$30 million',
    synopsis: "When the daughter of ex-con Jimmy Markum (Sean Penn) is murdered, three childhood friends are reunited—one a victim, one a detective (Kevin Bacon), one a suspect (Tim Robbins). A tragedy from their youth resurfaces as the murder investigation spirals into paranoia, guilt, and vengeance. Eastwood's dark drama is a devastating meditation on trauma and justice.",
    poster: '/path/to/mysticriver-poster.jpg',
    backdrop: '/path/to/mysticriver-backdrop.jpg',
    backdrop_path: '/path/to/mysticriver-backdrop.jpg',
    poster_path: '/path/to/mysticriver-poster.jpg',
    scenes: [
      { time: 12, intensity: 41, label: 'Abduction', color: '#b91c1c' },
      { time: 48, intensity: 60, label: 'Police Interrogation', color: '#f87171' },
      { time: 91, intensity: 72, label: 'Confession', color: '#fbbf24' },
      { time: 123, intensity: 84, label: 'Revelation', color: '#fde68a' },
      { time: 131, intensity: 91, label: 'Final Loss', color: '#dc2626' }
    ],
    suspenseIntensity: 91,
    dominantColor: '#152c48',
    dna: { Crime: 45, Drama: 40, Mystery: 15 },
    sensitiveScenes: [
      { start: "11:45", end: "12:16", description: "Kissing" },
      { start: "2:09:45", end: "2:10:16", description: "Passionate kissing" }
    ]
  },
  {
    imdbID: 'tt0353969',
    tmdbId: 11423,
    title: 'Memories of Murder',
    director: 'Bong Joon Ho',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '132 min',
    ageRating: 'NR',
    rating: 8.1,
    cast: ['Song Kang-ho', 'Kim Sang-kyung', 'Kim Roi-ha'],
    boxOffice: '$20.1 million',
    budget: '$2 million',
    synopsis: "1980s South Korea: Two detectives—one brutal and instinctual, the other methodical and precise—hunt the country's first confirmed serial killer. Based on true events, Bong Joon Ho's masterpiece captures the frustration and futility of chasing a ghost in a system unprepared for such evil. Dark, haunting, and unforgettable.",
    poster: '/path/to/memories-poster.jpg',
    backdrop: '/path/to/memories-backdrop.jpg',
    backdrop_path: '/path/to/memories-backdrop.jpg',
    poster_path: '/path/to/memories-poster.jpg',
    scenes: [
      { time: 18, intensity: 39, label: 'First Crime Scene', color: '#b91c1c' },
      { time: 50, intensity: 59, label: 'Railroad Interrogation', color: '#f87171' },
      { time: 87, intensity: 70, label: 'Suspect Hunt', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'The Confrontation', color: '#fde68a' },
      { time: 128, intensity: 93, label: 'Haunting End', color: '#dc2626' }
    ],
    suspenseIntensity: 93,
    dominantColor: '#313a35',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "9:58", end: "10:10", description: "Sex" },
      { start: "54:34", end: "54:55", description: "Nudity (men)" },
      { start: "1:01:12", end: "1:02:40", description: "Masturbating (man)" },
      { start: "1:25:12", end: "1:25:47", description: "Partial nudity (woman)" }
    ]
  },
  {
    imdbID: 'tt0407887',
    tmdbId: 1422,
    title: 'The Departed',
    director: 'Martin Scorsese',
    genre: 'Crime, Drama, Thriller',
    year: 2006,
    runtime: '151 min',
    ageRating: 'R',
    rating: 8.5,
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    boxOffice: '$291.5 million',
    budget: '$90 million',
    synopsis: "Boston: An undercover cop (Leonardo DiCaprio) infiltrates an Irish mob, while a mole (Matt Damon) inside the police feeds information to crime boss Frank Costello (Jack Nicholson). Both sides race to expose the other before their identities are revealed. Scorsese's Oscar-winning crime epic is a violent, relentless game of cat-and-mouse.",
    poster: '/path/to/departed-poster.jpg',
    backdrop: '/path/to/departed-backdrop.jpg',
    backdrop_path: '/path/to/departed-backdrop.jpg',
    poster_path: '/path/to/departed-poster.jpg',
    scenes: [
      { time: 20, intensity: 55, label: 'Undercover Initiation', color: '#b91c1c' },
      { time: 60, intensity: 73, label: 'First Betrayal', color: '#f87171' },
      { time: 102, intensity: 78, label: 'Roof Scene', color: '#fbbf24' },
      { time: 137, intensity: 82, label: 'Shootout', color: '#fde68a' },
      { time: 149, intensity: 90, label: 'Finale', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#b84f3a',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "1:13:18", end: "1:13:22", description: "Kissing" },
      { start: "1:21:50", end: "1:22:20", description: "Passionate kissing + Undressing" },
      { start: "1:24:40", end: "1:24:47", description: "Implied Sexual Gesture" }
    ]
  },
  {
    imdbID: 'tt0472043',
    tmdbId: 48395,
    title: 'Training Day',
    director: 'Antoine Fuqua',
    genre: 'Crime, Drama, Thriller',
    year: 2001,
    runtime: '122 min',
    ageRating: 'R',
    rating: 7.8,
    cast: ['Denzel Washington', 'Ethan Hawke', 'Scott Glenn'],
    boxOffice: '$104.9 million',
    budget: '$45 million',
    synopsis: "On his first day with the LAPD narcotics division, rookie cop Jake Hoyt (Ethan Hawke) rides with veteran detective Alonzo Harris (Denzel Washington). But as the day unfolds, Jake realizes Alonzo isn't just dirty—he's dangerously corrupt. Denzel won an Oscar for his charismatic, chilling performance as a cop who's become the very thing he's supposed to fight.",
    poster: '/path/to/trainingday-poster.jpg',
    backdrop: '/path/to/trainingday-backdrop.jpg',
    backdrop_path: '/path/to/trainingday-backdrop.jpg',
    poster_path: '/path/to/trainingday-poster.jpg',
    scenes: [
      { time: 15, intensity: 42, label: 'First Lesson', color: '#b91c1c' },
      { time: 48, intensity: 61, label: 'Forced Drug Use', color: '#f87171' },
      { time: 78, intensity: 74, label: 'The Game', color: '#fbbf24' },
      { time: 102, intensity: 83, label: 'Betrayal Revealed', color: '#fde68a' },
      { time: 118, intensity: 92, label: 'Final Showdown', color: '#dc2626' }
    ],
    suspenseIntensity: 92,
    dominantColor: '#3d2817',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "38:20", end: "38:45", description: "Drug use" }
    ]
  }
];


// Build object map by tmdbId
export const COMPLETE_CRIME_THRILLER_DATABASE = Object.fromEntries(
  CRIME_THRILLER_MOVIES.map(m => [m.tmdbId, m])
);


export default COMPLETE_CRIME_THRILLER_DATABASE;
