// utils/dramaMovieData.js - COMPLETE NETFLIX DRAMA COLLECTION WITH FIXED TMDB IDS ✅

export const DRAMA_MOVIES = [
  {
    tmdbId: 530915,
    imdbID: 'tt8579674',
    title: '1917',
    year: 2019,
    genre: 'War, Drama',
    runtime: 119,
    rating: 8.2,
    criticsScore: 89,
    audienceScore: 88,
    director: 'Sam Mendes',
    cast: ['George MacKay', 'Dean-Charles Chapman', 'Mark Strong', 'Andrew Scott', 'Benedict Cumberbatch'],
    boxOffice: '$384 million',
    budget: '$95 million',
    dna: { War: 50, Drama: 35, Tension: 15 },
    scenes: [
      { time: 15, intensity: 25, label: 'Mission Orders', color: '#dc2626' },
      { time: 40, intensity: 60, label: 'No Man\'s Land', color: '#ef4444' },
      { time: 70, intensity: 85, label: 'Bunker Explosion', color: '#f87171' },
      { time: 95, intensity: 92, label: 'River Escape', color: '#fca5a5' },
      { time: 115, intensity: 98, label: 'Final Sprint', color: '#fecaca' }
    ],
    synopsis: "Two British soldiers are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men from walking into a deadly trap.",
    themes: ['Courage', 'Sacrifice', 'Time Pressure', 'War Horror', 'Brotherhood'],
    awards: ['Academy Award Winner', 'Golden Globe Winner', 'BAFTA Winner'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/nv4Q83L1LnHG3i4zD8H2lGD8ToT.jpg',
    emotionalIntensity: 95,
    isRealStory: false,
    rank: 1
  },
  {
    tmdbId: 426426,  // ✅ FIXED - was 523619
    imdbID: 'tt6155172',
    title: 'Roma',
    year: 2018,
    genre: 'Drama',
    runtime: 135,
    rating: 7.7,
    criticsScore: 96,
    audienceScore: 79,
    director: 'Alfonso Cuarón',
    cast: ['Yalitza Aparicio', 'Marina de Tavira', 'Diego Cortina Autrey', 'Carlos Peralta'],
    boxOffice: '$8.2 million',
    budget: '$15 million',
    dna: { Drama: 70, Family: 20, Social: 10 },
    scenes: [
      { time: 20, intensity: 30, label: 'Daily Life', color: '#dc2626' },
      { time: 55, intensity: 55, label: 'City Riots', color: '#ef4444' },
      { time: 80, intensity: 75, label: 'Beach Scene', color: '#f87171' },
      { time: 110, intensity: 88, label: 'Water Rescue', color: '#fca5a5' },
      { time: 130, intensity: 85, label: 'Emotional Closure', color: '#fecaca' }
    ],
    synopsis: "A year in the life of a middle-class family's maid in Mexico City in the early 1970s, exploring class, family, and social upheaval.",
    themes: ['Class Division', 'Motherhood', 'Resilience', 'Family', 'Social Change'],
    awards: ['Academy Award Winner', 'Golden Globe Winner', 'Venice Film Festival Winner'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/jxJ32qv8LstYPYnpFmurZOXUZWw.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/4OdBLG7Y4zOLhFsyKmJTawzpL1o.jpg',
    emotionalIntensity: 88,
    isRealStory: false,
    rank: 2
  },
  {
    tmdbId: 573881,
    imdbID: 'tt1302006',
    title: 'The Irishman',
    year: 2019,
    genre: 'Crime, Drama',
    runtime: 209,
    rating: 7.8,
    criticsScore: 95,
    audienceScore: 86,
    director: 'Martin Scorsese',
    cast: ['Robert De Niro', 'Al Pacino', 'Joe Pesci', 'Harvey Keitel', 'Ray Romano'],
    boxOffice: '$9.5 million',
    budget: '$159 million',
    dna: { Crime: 50, Drama: 40, Historical: 10 },
    scenes: [
      { time: 30, intensity: 35, label: 'First Job', color: '#dc2626' },
      { time: 80, intensity: 65, label: 'Hoffa Meets Frank', color: '#ef4444' },
      { time: 130, intensity: 80, label: 'Hoffa Disappearance', color: '#f87171' },
      { time: 170, intensity: 70, label: 'Reflection & Regret', color: '#fca5a5' },
      { time: 205, intensity: 90, label: 'Final Confession', color: '#fecaca' }
    ],
    synopsis: "A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa, spanning decades of organized crime.",
    themes: ['Loyalty', 'Betrayal', 'Aging', 'Legacy', 'Regret'],
    awards: ['Academy Award Nominee', 'Golden Globe Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/bsYI3qxjQ3xPAPp7FxD7qLjZPZe.jpg',
    emotionalIntensity: 85,
    isRealStory: true,
    rank: 3
  },
  {
    tmdbId: 492188,
    imdbID: 'tt7653254',
    title: 'Marriage Story',
    year: 2019,
    genre: 'Drama, Romance',
    runtime: 137,
    rating: 7.9,
    criticsScore: 94,
    audienceScore: 82,
    director: 'Noah Baumbach',
    cast: ['Adam Driver', 'Scarlett Johansson', 'Laura Dern', 'Alan Alda', 'Ray Liotta'],
    boxOffice: '$2.3 million',
    budget: '$18 million',
    dna: { Drama: 60, Romance: 25, Family: 15 },
    scenes: [
      { time: 20, intensity: 30, label: 'Separation Decision', color: '#dc2626' },
      { time: 50, intensity: 55, label: 'Custody Talks', color: '#ef4444' },
      { time: 85, intensity: 80, label: 'The Fight Scene', color: '#f87171' },
      { time: 110, intensity: 88, label: 'Lawyer Confrontation', color: '#fca5a5' },
      { time: 132, intensity: 75, label: 'Final Goodbye', color: '#fecaca' }
    ],
    synopsis: "A stage director and his actor wife struggle through a grueling coast-to-coast divorce that pushes them to their personal and creative extremes.",
    themes: ['Love', 'Divorce', 'Parenthood', 'Identity', 'Communication'],
    awards: ['Academy Award Winner', 'Golden Globe Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/2JRyCKGWXDcBhsUY5XNLxtYNAoU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/fZYkxT3Pt5UnboHBhzh6KWqLuX5.jpg',
    emotionalIntensity: 92,
    isRealStory: false,
    rank: 4
  },
  {
    tmdbId: 37799,
    imdbID: 'tt1285016',
    title: 'The Social Network',
    year: 2010,
    genre: 'Biography, Drama',
    runtime: 120,
    rating: 7.8,
    criticsScore: 96,
    audienceScore: 94,
    director: 'David Fincher',
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake', 'Rooney Mara', 'Armie Hammer'],
    boxOffice: '$224 million',
    budget: '$40 million',
    dna: { Biography: 50, Drama: 40, Tech: 10 },
    scenes: [
      { time: 15, intensity: 35, label: 'Breakup & Blog', color: '#dc2626' },
      { time: 45, intensity: 55, label: 'Facebook Launch', color: '#ef4444' },
      { time: 75, intensity: 70, label: 'Betrayal Revealed', color: '#f87171' },
      { time: 95, intensity: 82, label: 'Legal Battles', color: '#fca5a5' },
      { time: 115, intensity: 78, label: 'Lonely Success', color: '#fecaca' }
    ],
    synopsis: "Harvard student Mark Zuckerberg creates a social networking site that eventually becomes Facebook, leading to legal battles and broken friendships.",
    themes: ['Ambition', 'Betrayal', 'Isolation', 'Innovation', 'Friendship'],
    awards: ['Academy Award Winner', 'Golden Globe Winner'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/kOMqjwqLy3fwHpIc6zy79FKFUcV.jpg',
    emotionalIntensity: 80,
    isRealStory: true,
    rank: 5
  },
  {
    tmdbId: 491480,  // ✅ FIXED - was 571451
    imdbID: 'tt7533152',
    title: 'The Boy Who Harnessed the Wind',
    year: 2019,
    genre: 'Drama, Biography',
    runtime: 113,
    rating: 7.6,
    criticsScore: 86,
    audienceScore: 92,
    director: 'Chiwetel Ejiofor',
    cast: ['Maxwell Simba', 'Chiwetel Ejiofor', 'Aïssa Maïga', 'Lily Banda'],
    boxOffice: 'N/A',
    budget: 'N/A',
    dna: { Drama: 60, Biography: 30, Inspiration: 10 },
    scenes: [
      { time: 20, intensity: 30, label: 'Drought Begins', color: '#dc2626' },
      { time: 50, intensity: 50, label: 'School Dropout', color: '#ef4444' },
      { time: 75, intensity: 65, label: 'Library Discovery', color: '#f87171' },
      { time: 95, intensity: 80, label: 'Building the Windmill', color: '#fca5a5' },
      { time: 110, intensity: 90, label: 'First Rain', color: '#fecaca' }
    ],
    synopsis: "A 13-year-old boy in Malawi invents an unconventional way to save his family and village from famine by building a wind turbine.",
    themes: ['Innovation', 'Hope', 'Education', 'Family', 'Perseverance'],
    awards: ['Sundance Film Festival Selection'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/n1kEoixlidwKzRS4kl0EwCXI9s8.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/r0Ar3FhKBjRAl4mPVDhBMgMTX37.jpg',
    emotionalIntensity: 82,
    isRealStory: true,
    rank: 6
  },
  {
    tmdbId: 600583,  // ✅ FIXED - was 840326
    imdbID: 'tt10293406',
    title: 'The Power of the Dog',
    year: 2021,
    genre: 'Western, Drama',
    runtime: 126,
    rating: 6.8,
    criticsScore: 94,
    audienceScore: 73,
    director: 'Jane Campion',
    cast: ['Benedict Cumberbatch', 'Kirsten Dunst', 'Jesse Plemons', 'Kodi Smit-McPhee'],
    boxOffice: '$1.2 million',
    budget: '$35 million',
    dna: { Western: 40, Drama: 40, Psychological: 20 },
    scenes: [
      { time: 20, intensity: 25, label: 'Ranch Tension', color: '#dc2626' },
      { time: 50, intensity: 45, label: 'New Marriage', color: '#ef4444' },
      { time: 80, intensity: 70, label: 'Manipulation Games', color: '#f87171' },
      { time: 105, intensity: 83, label: 'Hidden Desires', color: '#fca5a5' },
      { time: 122, intensity: 92, label: 'Final Revelation', color: '#fecaca' }
    ],
    synopsis: "A domineering rancher responds with mocking cruelty when his brother brings home a new wife and her son, until the unexpected comes to pass.",
    themes: ['Repression', 'Control', 'Masculinity', 'Desire', 'Revenge'],
    awards: ['Academy Award Winner', 'Golden Globe Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/vJ7Qy5SJlMBsDJEToQJDnKVpj7e.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/a7dL9c08M2k4u9MWEMlCqKXpZqC.jpg',
    emotionalIntensity: 88,
    isRealStory: false,
    rank: 7
  },
  {
    tmdbId: 414425,  // ✅ FIXED - was 429336
    imdbID: 'tt2396589',
    title: 'Mudbound',
    year: 2017,
    genre: 'Drama, War',
    runtime: 134,
    rating: 7.4,
    criticsScore: 97,
    audienceScore: 79,
    director: 'Dee Rees',
    cast: ['Carey Mulligan', 'Jason Mitchell', 'Mary J. Blige', 'Rob Morgan', 'Garrett Hedlund'],
    boxOffice: '$85,000',
    budget: '$12 million',
    dna: { Drama: 60, War: 25, Historical: 15 },
    scenes: [
      { time: 20, intensity: 30, label: 'Arrival at Farm', color: '#dc2626' },
      { time: 55, intensity: 55, label: 'WWII Service', color: '#ef4444' },
      { time: 85, intensity: 75, label: 'Return Home', color: '#f87171' },
      { time: 110, intensity: 90, label: 'Racial Violence', color: '#fca5a5' },
      { time: 130, intensity: 88, label: 'Aftermath', color: '#fecaca' }
    ],
    synopsis: "Two men return home from World War II to work on a farm in rural Mississippi, where they struggle to deal with racism and adjusting to life after war.",
    themes: ['Racism', 'War Trauma', 'Friendship', 'Family', 'Injustice'],
    awards: ['Academy Award Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/uuFjMFN1N4V5a4RbfXJ7IW5wlXo.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/34eeDBp4w7BpT4FiFHJHWfmJB5z.jpg',
    emotionalIntensity: 87,
    isRealStory: false,
    rank: 8
  },
  {
    tmdbId: 1402,
    imdbID: 'tt0454921',
    title: 'The Pursuit of Happyness',
    year: 2006,
    genre: 'Biography, Drama',
    runtime: 117,
    rating: 8.0,
    criticsScore: 67,
    audienceScore: 87,
    director: 'Gabriele Muccino',
    cast: ['Will Smith', 'Jaden Smith', 'Thandiwe Newton', 'Brian Howe'],
    boxOffice: '$307 million',
    budget: '$55 million',
    dna: { Biography: 50, Drama: 40, Family: 10 },
    scenes: [
      { time: 20, intensity: 35, label: 'Financial Struggles', color: '#dc2626' },
      { time: 50, intensity: 60, label: 'Homelessness', color: '#ef4444' },
      { time: 75, intensity: 75, label: 'Bathroom Scene', color: '#f87171' },
      { time: 95, intensity: 85, label: 'Internship Challenges', color: '#fca5a5' },
      { time: 113, intensity: 95, label: 'Job Offer', color: '#fecaca' }
    ],
    synopsis: "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
    themes: ['Perseverance', 'Fatherhood', 'Dreams', 'Poverty', 'Hope'],
    awards: ['Academy Award Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/pMzl7hG8l8wjqxrHHpNnLDDNTvy.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/aRkEWHC8dNRlw9w0HGYHsDHZvsR.jpg',
    emotionalIntensity: 93,
    isRealStory: true,
    rank: 9
  },
  {
    tmdbId: 615643,  // ✅ FIXED - was 615906
    imdbID: 'tt10633456',
    title: 'Minari',
    year: 2020,
    genre: 'Drama',
    runtime: 115,
    rating: 7.4,
    criticsScore: 98,
    audienceScore: 89,
    director: 'Lee Isaac Chung',
    cast: ['Steven Yeun', 'Han Ye-ri', 'Alan Kim', 'Noel Kate Cho', 'Youn Yuh-jung'],
    boxOffice: '$15.5 million',
    budget: '$2 million',
    dna: { Drama: 70, Family: 25, Cultural: 5 },
    scenes: [
      { time: 15, intensity: 25, label: 'Arrival in Arkansas', color: '#dc2626' },
      { time: 45, intensity: 50, label: 'Farm Challenges', color: '#ef4444' },
      { time: 70, intensity: 70, label: 'Health Crisis', color: '#f87171' },
      { time: 95, intensity: 85, label: 'Fire Disaster', color: '#fca5a5' },
      { time: 110, intensity: 80, label: 'New Beginnings', color: '#fecaca' }
    ],
    synopsis: "A Korean-American family moves to rural Arkansas in the 1980s to start a farm, facing new challenges while chasing the American Dream.",
    themes: ['Family', 'Immigration', 'Dreams', 'Resilience', 'Culture'],
    awards: ['Academy Award Winner', 'Golden Globe Nominee'],
    streamingPlatform: 'Netflix',
    poster: 'https://image.tmdb.org/t/p/w500/gGchyO1YpTg92M56bXzBiVViHFn.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w1280/2NJRynrD8dVlH5M6qGT1g0U0Z7v.jpg',
    emotionalIntensity: 84,
    isRealStory: true,
    rank: 10
  }
];

export default DRAMA_MOVIES;
