// utils/dramaMovieRoutes.js - COMPLETE NETFLIX DRAMA COLLECTION ✅ ALL REAL GENRES
export const DRAMA_MOVIES = [
  {
    imdbID: 'tt8579674',
    tmdbId: 530915,
    title: '1917',
    director: 'Sam Mendes',
    genre: 'War, Drama',
    year: 2019,
    runtime: '119 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['George MacKay', 'Dean-Charles Chapman', 'Mark Strong', 'Andrew Scott', 'Benedict Cumberbatch'],
    boxOffice: '$384 million',
    budget: '$95 million',
    synopsis: "Two soldiers race against time through the trenches of World War I on a mission that could change the course of battle—but only if they survive the journey. Shot in real-time with mind-bending cinematography, this is war stripped down to its rawest, most visceral form. One continuous shot. One impossible mission. One breath-taking experience.",
    poster: '/path/to/1917-poster.jpg',
    backdrop: '/path/to/1917-backdrop.jpg',
    backdrop_path: '/path/to/1917-backdrop.jpg',
    poster_path: '/path/to/1917-poster.jpg',
    scenes: [
      { time: 15, intensity: 25, label: 'Mission Orders', color: '#dc2626' },
      { time: 40, intensity: 60, label: "No Man's Land", color: '#ef4444' },
      { time: 70, intensity: 85, label: 'Bunker Explosion', color: '#f87171' },
      { time: 95, intensity: 92, label: 'River Escape', color: '#fca5a5' },
      { time: 115, intensity: 98, label: 'Final Sprint', color: '#fecaca' }
    ],
    emotionalIntensity: 98,
    dna: { War: 55, Drama: 35, Action: 10 },
    dominantColor: '#eab308',
    sensitiveScenes: []
  },
  {
    imdbID: 'tt6155172',
    tmdbId: 426426,
    title: 'Roma',
    director: 'Alfonso Cuarón',
    genre: 'Drama',
    year: 2018,
    runtime: '135 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Yalitza Aparicio', 'Marina de Tavira', 'Diego Cortina Autrey', 'Carlos Peralta'],
    boxOffice: '$8.2 million',
    budget: '$15 million',
    synopsis: "In 1970s Mexico City, a documentary-style masterpiece follows a domestic worker navigating family chaos, political upheaval, and quiet heartbreak. Alfonso Cuarón's intimate black-and-white meditation transforms everyday moments into poetry. It's memory captured—every frame feels lived in, every scene a photograph of the human condition.",
    poster: '/path/to/roma-poster.jpg',
    backdrop: '/path/to/roma-backdrop.jpg',
    backdrop_path: '/path/to/roma-backdrop.jpg',
    poster_path: '/path/to/roma-poster.jpg',
    scenes: [
      { time: 20, intensity: 30, label: 'Daily Life', color: '#dc2626' },
      { time: 55, intensity: 55, label: 'City Riots', color: '#ef4444' },
      { time: 80, intensity: 75, label: 'Beach Scene', color: '#f87171' },
      { time: 110, intensity: 88, label: 'Water Rescue', color: '#fca5a5' },
      { time: 130, intensity: 85, label: 'Emotional Closure', color: '#fecaca' }
    ],
    emotionalIntensity: 88,
    dna: { Drama: 60, Romance: 25, Family: 15 },
    dominantColor: '#f59e42',
    sensitiveScenes: [
      { start: "25:09", end: "27:29", description: "Nudity (naked man)" },
      { start: "36:38", end: "38:01", description: "Kissing (passionate)" }
    ]
  },
  {
    imdbID: 'tt1302006',
    tmdbId: 573881,
    title: 'The Irishman',
    director: 'Martin Scorsese',
    genre: 'Crime, Drama',
    year: 2019,
    runtime: '209 min',
    ageRating: 'R',
    rating: 7.8,
    cast: ['Robert De Niro', 'Al Pacino', 'Joe Pesci', 'Harvey Keitel', 'Ray Romano'],
    boxOffice: '$9.5 million',
    budget: '$159 million',
    synopsis: "Martin Scorsese's final crime epic spans decades, aging mobsters, and the ultimate cost of loyalty. Robert De Niro confesses his sins—including a crime that changed America—in a 3.5-hour meditation on violence, regret, and redemption. A career capstone that asks: was any of it worth it? The answer haunts you long after it ends.",
    poster: '/path/to/irishman-poster.jpg',
    backdrop: '/path/to/irishman-backdrop.jpg',
    backdrop_path: '/path/to/irishman-backdrop.jpg',
    poster_path: '/path/to/irishman-poster.jpg',
    scenes: [
      { time: 30, intensity: 35, label: 'First Job', color: '#dc2626' },
      { time: 80, intensity: 65, label: 'Hoffa Meets Frank', color: '#ef4444' },
      { time: 130, intensity: 80, label: 'Hoffa Disappearance', color: '#f87171' },
      { time: 170, intensity: 70, label: 'Reflection & Regret', color: '#fca5a5' },
      { time: 205, intensity: 90, label: 'Final Confession', color: '#fecaca' }
    ],
    emotionalIntensity: 90,
    dna: { Crime: 50, Drama: 40, Thriller: 10 },
    dominantColor: '#717acf',
    sensitiveScenes: []
  },
  {
    imdbID: 'tt9770150',
    tmdbId: 492188,
    title: 'Marriage Story',
    director: 'Noah Baumbach',
    genre: 'Drama, Romance',
    year: 2019,
    runtime: '137 min',
    ageRating: 'R',
    rating: 7.9,
    cast: ['Adam Driver', 'Scarlett Johansson', 'Laura Dern', 'Alan Alda', 'Ray Liotta'],
    boxOffice: '$2.3 million',
    budget: '$18 million',
    synopsis: "A couple navigates the brutal honesty of divorce with devastating performances that strip away all pretense. Adam Driver and Scarlett Johansson wage emotional warfare in one of cinema's most visceral arguments, then find unexpected grace in separation. Raw, tender, brutal, true—heartbreak's most authentic portrayal.",
    poster: '/path/to/marriage-story-poster.jpg',
    backdrop: '/path/to/marriage-story-backdrop.jpg',
    backdrop_path: '/path/to/marriage-story-backdrop.jpg',
    poster_path: '/path/to/marriage-story-poster.jpg',
    scenes: [
      { time: 20, intensity: 30, label: 'Separation Decision', color: '#dc2626' },
      { time: 50, intensity: 55, label: 'Custody Talks', color: '#ef4444' },
      { time: 85, intensity: 80, label: 'The Fight Scene', color: '#f87171' },
      { time: 110, intensity: 88, label: 'Lawyer Confrontation', color: '#fca5a5' },
      { time: 132, intensity: 75, label: 'Final Goodbye', color: '#fecaca' }
    ],
    emotionalIntensity: 88,
    dna: { Drama: 65, Romance: 25, Comedy: 10 },
    dominantColor: '#fbe3a1',
    sensitiveScenes: [
      { start: "1:12:31", end: "1:13:00", description: "Kissing (passionate)" }
    ]
  },
  {
    imdbID: 'tt1677720',
    tmdbId: 37799,
    title: 'The Social Network',
    director: 'David Fincher',
    genre: 'Biography, Drama',
    year: 2010,
    runtime: '120 min',
    ageRating: 'PG-13',
    rating: 7.8,
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake', 'Rooney Mara', 'Armie Hammer'],
    boxOffice: '$224 million',
    budget: '$40 million',
    synopsis: "Two hours of razor-sharp dialogue about ambition, betrayal, and the loneliness at the top. How did a college kid create Facebook—and destroy friendships in the process? Aaron Sorkin's screenplay transforms tech into Shakespeare, proving that genius is often just ego wearing a hoody.",
    poster: '/path/to/socialnetwork-poster.jpg',
    backdrop: '/path/to/socialnetwork-backdrop.jpg',
    backdrop_path: '/path/to/socialnetwork-backdrop.jpg',
    poster_path: '/path/to/socialnetwork-poster.jpg',
    scenes: [
      { time: 15, intensity: 35, label: 'Breakup & Blog', color: '#dc2626' },
      { time: 45, intensity: 55, label: 'Facebook Launch', color: '#ef4444' },
      { time: 75, intensity: 70, label: 'Betrayal Revealed', color: '#f87171' },
      { time: 95, intensity: 82, label: 'Legal Battles', color: '#fca5a5' },
      { time: 115, intensity: 78, label: 'Lonely Success', color: '#fecaca' }
    ],
    emotionalIntensity: 82,
    dna: { Biography: 50, Drama: 35, Thriller: 15 },
    dominantColor: '#005fa3',
    sensitiveScenes: [
      { start: "50:55", end: "51:31", description: "Kissing (passionate)" },
      { start: "57:00", end: "59:33", description: "Suggestive clothing (women in underwear)" }
    ]
  },
  {
    imdbID: 'tt9419184',
    tmdbId: 491480,
    title: 'The Boy Who Harnessed the Wind',
    director: 'Chiwetel Ejiofor',
    genre: 'Drama, Biography',
    year: 2019,
    runtime: '113 min',
    ageRating: 'PG',
    rating: 7.6,
    cast: ['Maxwell Simba', 'Chiwetel Ejiofor', 'Aïssa Maïga', 'Lily Banda'],
    boxOffice: 'N/A',
    budget: 'N/A',
    synopsis: "A Malawian teenager with nothing but determination builds a windmill from scrap metal to save his village from starvation. Inspired by true events, this is hope, innovation, and the power of one person refusing to accept defeat.",
    poster: '/path/to/wind-poster.jpg',
    backdrop: '/path/to/wind-backdrop.jpg',
    backdrop_path: '/path/to/wind-backdrop.jpg',
    poster_path: '/path/to/wind-poster.jpg',
    scenes: [
      { time: 20, intensity: 30, label: 'Drought Begins', color: '#dc2626' },
      { time: 50, intensity: 50, label: 'School Dropout', color: '#ef4444' },
      { time: 75, intensity: 65, label: 'Library Discovery', color: '#f87171' },
      { time: 95, intensity: 80, label: 'Building the Windmill', color: '#fca5a5' },
      { time: 110, intensity: 90, label: 'First Rain', color: '#fecaca' }
    ],
    emotionalIntensity: 90,
    dna: { Drama: 60, Biography: 30, Adventure: 10 },
    dominantColor: '#55c443',
    sensitiveScenes: []
  },
  {
    imdbID: 'tt7291200',
    tmdbId: 600583,
    title: 'The Power of the Dog',
    director: 'Jane Campion',
    genre: 'Western, Drama',
    year: 2021,
    runtime: '126 min',
    ageRating: 'R',
    rating: 6.8,
    cast: ['Benedict Cumberbatch', 'Kirsten Dunst', 'Jesse Plemons', 'Kodi Smit-McPhee'],
    boxOffice: '$1.2 million',
    budget: '$35 million',
    synopsis: "A slow-burning psychological Western where every glance hides violence, every word conceals desire, and beneath civility simmers repression. Jane Campion deconstructs the myth of the West through a tyrant's cruelty and hidden shame. Toxic masculinity has never been so beautifully, terrifyingly subtle.",
    poster: '/path/to/powerofdog-poster.jpg',
    backdrop: '/path/to/powerofdog-backdrop.jpg',
    backdrop_path: '/path/to/powerofdog-backdrop.jpg',
    poster_path: '/path/to/powerofdog-poster.jpg',
    scenes: [
      { time: 20, intensity: 25, label: 'Ranch Tension', color: '#dc2626' },
      { time: 50, intensity: 45, label: 'New Marriage', color: '#ef4444' },
      { time: 80, intensity: 70, label: 'Manipulation Games', color: '#f87171' },
      { time: 105, intensity: 83, label: 'Hidden Desires', color: '#fca5a5' },
      { time: 122, intensity: 92, label: 'Final Revelation', color: '#fecaca' }
    ],
    emotionalIntensity: 92,
    dna: { Western: 45, Drama: 40, Thriller: 15 },
    dominantColor: '#a77a50',
    sensitiveScenes: [
      { start: "43:20", end: "43:49", description: "Nudity (naked man)" },
      { start: "1:11:00", end: "1:11:25", description: "Partial nudity (naked men)" },
      { start: "1:14:00", end: "1:14:08", description: "Masturbating man (not graphic)" },
      { start: "1:16:15", end: "1:16:45", description: "Nudity (naked man)" }
    ]
  },
  {
    imdbID: 'tt2156584',
    tmdbId: 414425,
    title: 'Mudbound',
    director: 'Dee Rees',
    genre: 'Drama, War',
    year: 2017,
    runtime: '134 min',
    ageRating: 'R',
    rating: 7.4,
    cast: ['Carey Mulligan', 'Jason Mitchell', 'Mary J. Blige', 'Rob Morgan', 'Garrett Hedlund'],
    boxOffice: '$85,000',
    budget: '$12 million',
    synopsis: "Two farming families—one Black, one white—struggle with poverty and racism in postwar Mississippi. The film refuses to sanitize American racism; instead, it presents systemic brutality with unflinching honesty. A raw, visually stunning portrait of survival, dignity, and the persistence of injustice.",
    poster: '/path/to/mudbound-poster.jpg',
    backdrop: '/path/to/mudbound-backdrop.jpg',
    backdrop_path: '/path/to/mudbound-backdrop.jpg',
    poster_path: '/path/to/mudbound-poster.jpg',
    scenes: [
      { time: 20, intensity: 30, label: 'Arrival at Farm', color: '#dc2626' },
      { time: 55, intensity: 55, label: 'WWII Service', color: '#ef4444' },
      { time: 85, intensity: 75, label: 'Return Home', color: '#f87171' },
      { time: 110, intensity: 90, label: 'Racial Violence', color: '#fca5a5' },
      { time: 130, intensity: 88, label: 'Aftermath', color: '#fecaca' }
    ],
    emotionalIntensity: 90,
    dna: { Drama: 55, War: 30, Crime: 15 },
    dominantColor: '#988372',
    sensitiveScenes: [
      { start: "08:02", end: "08:08", description: "Kissing" },
      { start: "20:04", end: "20:14", description: "Sex" },
      { start: "55:40", end: "55:50", description: "Nudity (naked woman)" },
      { start: "1:51:13", end: "1:51:34", description: "Kissing (passionate)" },
      { start: "1:56:13", end: "1:57:00", description: "Nudity (naked man)" }
    ]
  },
  {
    imdbID: 'tt0454921',
    tmdbId: 1402,
    title: 'The Pursuit of Happyness',
    director: 'Gabriele Muccino',
    genre: 'Biography, Drama',
    year: 2006,
    runtime: '117 min',
    ageRating: 'PG-13',
    rating: 8.0,
    cast: ['Will Smith', 'Jaden Smith', 'Thandiwe Newton', 'Brian Howe'],
    boxOffice: '$307 million',
    budget: '$55 million',
    synopsis: "A father's fight for dignity as he battles homelessness while pursuing a stockbroker internship, refusing to let poverty steal his love for his son. Will Smith delivers an Oscar-worthy performance of perseverance and hope. Based on true events—proof that the American Dream still requires extraordinary sacrifice.",
    poster: '/path/to/happyness-poster.jpg',
    backdrop: '/path/to/happyness-backdrop.jpg',
    backdrop_path: '/path/to/happyness-backdrop.jpg',
    poster_path: '/path/to/happyness-poster.jpg',
    scenes: [
      { time: 20, intensity: 35, label: 'Financial Struggles', color: '#dc2626' },
      { time: 50, intensity: 60, label: 'Homelessness', color: '#ef4444' },
      { time: 75, intensity: 75, label: 'Bathroom Scene', color: '#f87171' },
      { time: 95, intensity: 85, label: 'Internship Challenges', color: '#fca5a5' },
      { time: 113, intensity: 95, label: 'Job Offer', color: '#fecaca' }
    ],
    emotionalIntensity: 95,
    dna: { Biography: 60, Drama: 35, Comedy: 5 },
    dominantColor: '#c47a4e',
    sensitiveScenes: []
  },
  {
    imdbID: 'tt10118744',
    tmdbId: 615643,
    title: 'Minari',
    director: 'Lee Isaac Chung',
    genre: 'Drama',
    year: 2020,
    runtime: '115 min',
    ageRating: 'PG-13',
    rating: 7.4,
    cast: ['Steven Yeun', 'Han Ye-ri', 'Alan Kim', 'Noel Kate Cho', 'Youn Yuh-jung'],
    boxOffice: '$15.5 million',
    budget: '$2 million',
    synopsis: "A Korean-American family bets everything on an Arkansas farm, chasing the American Dream with cultural heritage in one hand and hope in the other. Grandmother Soon-ja arrives to hold the family together as language barriers, financial ruin, and internal conflict test their bonds. Intimate, heartfelt, and full of quiet soul—cinema at its purest.",
    poster: '/path/to/minari-poster.jpg',
    backdrop: '/path/to/minari-backdrop.jpg',
    backdrop_path: '/path/to/minari-backdrop.jpg',
    poster_path: '/path/to/minari-poster.jpg',
    scenes: [
      { time: 15, intensity: 25, label: 'Arrival in Arkansas', color: '#dc2626' },
      { time: 45, intensity: 50, label: 'Farm Challenges', color: '#ef4444' },
      { time: 70, intensity: 70, label: 'Health Crisis', color: '#f87171' },
      { time: 95, intensity: 85, label: 'Fire Disaster', color: '#fca5a5' },
      { time: 110, intensity: 80, label: 'New Beginnings', color: '#fecaca' }
    ],
    emotionalIntensity: 85,
    dna: { Drama: 70, Family: 20, Romance: 10 },
    dominantColor: '#b5c44f',
    sensitiveScenes: []
  }
];

// ===== BUILD OBJECT FROM ARRAY =====
export const COMPLETE_MOVIE_DATABASE = Object.fromEntries(
  DRAMA_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_MOVIE_DATABASE;
