// utils/heistThrillerMovieData.js - BEST HEIST THRILLER COLLECTION ✅ WITH DNA & SENSITIVE CONTENT

export const HEIST_THRILLER_MOVIES = [
  {
    imdbID: 'tt0113277',
    tmdbId: 949,
    title: 'Heat',
    director: 'Michael Mann',
    genre: 'Crime, Drama, Thriller',
    year: 1995,
    runtime: '170 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Al Pacino', 'Robert De Niro', 'Val Kilmer'],
    boxOffice: '$187.4 million',
    budget: '$60 million',
    synopsis: "A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.",
    poster: '/path/to/heat-poster.jpg',
    backdrop: '/path/to/heat-backdrop.jpg',
    backdrop_path: '/path/to/heat-backdrop.jpg',
    poster_path: '/path/to/heat-poster.jpg',
    scenes: [
      { time: 10, intensity: 50, label: 'Bank Robbery Setup', color: '#b91c1c' },
      { time: 75, intensity: 80, label: 'Cop Confrontation', color: '#f87171' },
      { time: 110, intensity: 85, label: 'Team Division', color: '#fbbf24' },
      { time: 140, intensity: 90, label: 'Downtown Chase', color: '#fde68a' },
      { time: 160, intensity: 95, label: 'Final Shootout', color: '#dc2626' }
    ],
    suspenseIntensity: 95,
    dominantColor: '#6b7280',
    dna: { Crime: 60, Drama: 30, Thriller: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0105236',
    tmdbId: 500,
    title: 'Reservoir Dogs',
    director: 'Quentin Tarantino',
    genre: 'Crime, Thriller',
    year: 1992,
    runtime: '99 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Harvey Keitel', 'Tim Roth', 'Michael Madsen'],
    boxOffice: '$2.8 million',
    budget: '$1.2 million',
    synopsis: "After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
    poster: '/path/to/reservoir-dogs-poster.jpg',
    backdrop: '/path/to/reservoir-dogs-backdrop.jpg',
    backdrop_path: '/path/to/reservoir-dogs-backdrop.jpg',
    poster_path: '/path/to/reservoir-dogs-poster.jpg',
    scenes: [
      { time: 12, intensity: 40, label: 'Heist Planning', color: '#b91c1c' },
      { time: 35, intensity: 55, label: 'Tense Meeting', color: '#f87171' },
      { time: 60, intensity: 75, label: 'Betrayal Suspicion', color: '#fbbf24' },
      { time: 80, intensity: 85, label: 'Interrogations', color: '#fde68a' },
      { time: 90, intensity: 90, label: 'Shootout', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#374151',
    dna: { Crime: 70, Thriller: 25, Drama: 5 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0844708',
    tmdbId: 23168,
    title: 'The Town',
    director: 'Ben Affleck',
    genre: 'Crime, Drama, Thriller',
    year: 2010,
    runtime: '125 min',
    ageRating: 'R',
    rating: 7.5,
    cast: ['Ben Affleck', 'Rebecca Hall', 'Jeremy Renner'],
    boxOffice: '$154.9 million',
    budget: '$37 million',
    synopsis: "A tough bank robber has a change of heart when he falls in love with a hostage–turned–partner, but must navigate his dangerous criminal life to escape with her.",
    poster: '/path/to/the-town-poster.jpg',
    backdrop: '/path/to/the-town-backdrop.jpg',
    backdrop_path: '/path/to/the-town-backdrop.jpg',
    poster_path: '/path/to/the-town-poster.jpg',
    scenes: [
      { time: 15, intensity: 48, label: 'Heist Planning', color: '#b91c1c' },
      { time: 50, intensity: 65, label: 'Hostage Taking', color: '#f87171' },
      { time: 85, intensity: 78, label: 'Police Pursuit', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'Emotional Conflict', color: '#fde68a' },
      { time: 120, intensity: 90, label: 'Final Showdown', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#374151',
    dna: { Crime: 65, Drama: 25, Thriller: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0475304',
    tmdbId: 338766,
    title: 'Hell or High Water',
    director: 'David Mackenzie',
    genre: 'Crime, Drama, Thriller',
    year: 2016,
    runtime: '102 min',
    ageRating: 'R',
    rating: 7.6,
    cast: ['Chris Pine', 'Ben Foster', 'Jeff Bridges'],
    boxOffice: '$37.7 million',
    budget: '$12 million',
    synopsis: "Two brothers resort to bank robberies to save their family ranch while a relentless Texas Ranger closes in.",
    poster: '/path/to/hell-or-high-water-poster.jpg',
    backdrop: '/path/to/hell-or-high-water-backdrop.jpg',
    backdrop_path: '/path/to/hell-or-high-water-backdrop.jpg',
    poster_path: '/path/to/hell-or-high-water-poster.jpg',
    scenes: [
      { time: 10, intensity: 40, label: 'First Robbery', color: '#b91c1c' },
      { time: 40, intensity: 60, label: 'Police Arrival', color: '#f87171' },
      { time: 75, intensity: 78, label: 'Chase', color: '#fbbf24' },
      { time: 90, intensity: 85, label: 'Family Conflict', color: '#fde68a' },
      { time: 100, intensity: 89, label: 'Final Stand', color: '#dc2626' }
    ],
    suspenseIntensity: 89,
    dominantColor: '#8b5cf6',
    dna: { Crime: 55, Drama: 30, Thriller: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0305224',
    tmdbId: 374,
    title: 'The Bank Job',
    director: 'Roger Donaldson',
    genre: 'Crime, Drama, Thriller',
    year: 2008,
    runtime: '104 min',
    ageRating: 'PG-13',
    rating: 6.9,
    cast: ['Jason Statham', 'Saffron Burrows', 'David Suchet'],
    boxOffice: '$64.3 million',
    budget: '$30 million',
    synopsis: "A group of thieves execute a bank heist that unravels political scandals and the dark side of London’s high society.",
    poster: '/path/to/bank-job-poster.jpg',
    backdrop: '/path/to/bank-job-backdrop.jpg',
    backdrop_path: '/path/to/bank-job-backdrop.jpg',
    poster_path: '/path/to/bank-job-poster.jpg',
    scenes: [
      { time: 20, intensity: 35, label: 'Planning', color: '#b91c1c' },
      { time: 50, intensity: 60, label: 'Vault Breach', color: '#f87171' },
      { time: 70, intensity: 75, label: 'Security Alert', color: '#fbbf24' },
      { time: 90, intensity: 80, label: 'Escape Plan', color: '#fde68a' },
      { time: 100, intensity: 85, label: 'Getaway', color: '#dc2626' }
    ],
    suspenseIntensity: 85,
    dominantColor: '#ca8a04',
    dna: { Crime: 60, Drama: 25, Thriller: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0454848',
    tmdbId: 388,
    title: 'Inside Man',
    director: 'Spike Lee',
    genre: 'Crime, Drama, Thriller',
    year: 2006,
    runtime: '129 min',
    ageRating: 'R',
    rating: 7.6,
    cast: ['Denzel Washington', 'Clive Owen', 'Jodie Foster'],
    boxOffice: '$88.4 million',
    budget: '$45 million',
    synopsis: "A perfect bank robbery turns into a tense hostage situation as a detective tries to outsmart the criminals.",
    poster: '/path/to/inside-man-poster.jpg',
    backdrop: '/path/to/inside-man-backdrop.jpg',
    backdrop_path: '/path/to/inside-man-backdrop.jpg',
    poster_path: '/path/to/inside-man-poster.jpg',
    scenes: [
      { time: 18, intensity: 45, label: 'Robbery', color: '#b91c1c' },
      { time: 50, intensity: 65, label: 'Hostage Situation', color: '#f87171' },
      { time: 85, intensity: 75, label: 'Negotiation', color: '#fbbf24' },
      { time: 110, intensity: 80, label: 'Surprise Twist', color: '#fde68a' },
      { time: 125, intensity: 85, label: 'Resolution', color: '#dc2626' }
    ],
    suspenseIntensity: 85,
    dominantColor: '#1f2937',
    dna: { Crime: 55, Drama: 30, Thriller: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0083190',
    tmdbId: 11524,
    title: 'Thief',
    director: 'Michael Mann',
    genre: 'Crime, Thriller',
    year: 11524,
    runtime: '120 min',
    ageRating: 'R',
    rating: 7.5,
    cast: ['James Caan', 'Tuesday Weld', 'William Petersen'],
    boxOffice: '$1.8 million',
    budget: '$6 million',
    synopsis: "A professional safecracker tries to leave his life of crime behind but is pulled into one last heist.",
    poster: '/path/to/thief-poster.jpg',
    backdrop: '/path/to/thief-backdrop.jpg',
    backdrop_path: '/path/to/thief-backdrop.jpg',
    poster_path: '/path/to/thief-poster.jpg',
    scenes: [
      { time: 15, intensity: 40, label: 'Planning', color: '#b91c1c' },
      { time: 50, intensity: 65, label: 'Heist Execution', color: '#f87171' },
      { time: 80, intensity: 75, label: 'Complications', color: '#fbbf24' },
      { time: 95, intensity: 85, label: 'Escape', color: '#fde68a' },
      { time: 110, intensity: 88, label: 'Aftermath', color: '#dc2626' }
    ],
    suspenseIntensity: 88,
    dominantColor: '#6d4c41',
    dna: { Crime: 65, Thriller: 30, Drama: 5 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0073195',
    tmdbId: 1981,
    title: 'Dog Day Afternoon',
    director: 'Sidney Lumet',
    genre: 'Crime, Drama, Thriller',
    year: 1975,
    runtime: '125 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Al Pacino', 'John Cazale', 'Charles Durning'],
    boxOffice: '$50 million',
    budget: '$1.8 million',
    synopsis: "An attempted bank robbery turns into a media circus, as the robbers and hostages form unusual bonds.",
    poster: '/path/to/dog-day-afternoon-poster.jpg',
    backdrop: '/path/to/dog-day-afternoon-backdrop.jpg',
    backdrop_path: '/path/to/dog-day-afternoon-backdrop.jpg',
    poster_path: '/path/to/dog-day-afternoon-poster.jpg',
    scenes: [
      { time: 20, intensity: 50, label: 'Robbery Start', color: '#b91c1c' },
      { time: 55, intensity: 70, label: 'Hostage Negotiation', color: '#f87171' },
      { time: 90, intensity: 80, label: 'Media Frenzy', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'Emotional Conflict', color: '#fde68a' },
      { time: 120, intensity: 85, label: 'Resolution', color: '#dc2626' }
    ],
    suspenseIntensity: 85,
    dominantColor: '#374151',
    dna: { Crime: 55, Drama: 30, Thriller: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0317740',
    tmdbId: 9654,
    title: 'The Italian Job',
    director: 'Peter Collinson',
    genre: 'Action, Crime, Thriller',
    year: 1969,
    runtime: '99 min',
    ageRating: 'PG',
    rating: 7.3,
    cast: ['Michael Caine', 'Noël Coward', 'Benny Hill'],
    boxOffice: '$12 million',
    budget: '$3.2 million',
    synopsis: "A team of thieves plan and execute a gold heist in Italy using Mini Coopers.",
    poster: '/path/to/italian-job-poster.jpg',
    backdrop: '/path/to/italian-job-backdrop.jpg',
    backdrop_path: '/path/to/italian-job-backdrop.jpg',
    poster_path: '/path/to/italian-job-poster.jpg',
    scenes: [
      { time: 15, intensity: 40, label: 'Planning', color: '#b91c1c' },
      { time: 45, intensity: 65, label: 'Mini Cooper Chase', color: '#f87171' },
      { time: 70, intensity: 75, label: 'Gold Heist', color: '#fbbf24' },
      { time: 85, intensity: 80, label: 'Final Showdown', color: '#fde68a' },
      { time: 95, intensity: 85, label: 'Escape', color: '#dc2626' }
    ],
    suspenseIntensity: 85,
    dominantColor: '#f59e0b',
    dna: { Crime: 50, Thriller: 35, Action: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0240772',
    tmdbId: 161,
    title: "Ocean's Eleven",
    director: 'Steven Soderbergh',
    genre: 'Crime, Thriller',
    year: 2001,
    runtime: '116 min',
    ageRating: 'PG-13',
    rating: 7.8,
    cast: ['George Clooney', 'Brad Pitt', 'Matt Damon'],
    boxOffice: '$450.7 million',
    budget: '$85 million',
    synopsis: "Danny Ocean and his eleven accomplices plan to rob three Las Vegas casinos simultaneously.",
    poster: '/path/to/oceans-eleven-poster.jpg',
    backdrop: '/path/to/oceans-eleven-backdrop.jpg',
    backdrop_path: '/path/to/oceans-eleven-backdrop.jpg',
    poster_path: '/path/to/oceans-eleven-poster.jpg',
    scenes: [
      { time: 12, intensity: 45, label: 'Planning the Heist', color: '#b91c1c' },
      { time: 48, intensity: 70, label: 'Recruiting Team', color: '#f87171' },
      { time: 75, intensity: 80, label: 'Casino Infiltration', color: '#fbbf24' },
      { time: 98, intensity: 85, label: 'Robbery Execution', color: '#fde68a' },
      { time: 110, intensity: 90, label: 'Escape', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#111827',
    dna: { Crime: 60, Thriller: 30, Drama: 10 },
    sensitiveScenes: []
  }
];

// Build object map by tmdbId
export const COMPLETE_HEIST_THRILLER_DATABASE = Object.fromEntries(
  HEIST_THRILLER_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_HEIST_THRILLER_DATABASE;
