// utils/interstellarLikeMoviesData.js - TOP 10 MOVIES LIKE INTERSTELLAR ⚡ SPACE SCI-FI MASTERPIECES

export const INTERSTELLAR_LIKE_MOVIES = [
  {
    imdbID: 'tt0062622',
    tmdbId: 329,
    title: '2001: A Space Odyssey',
    director: 'Stanley Kubrick',
    genre: 'Sci-Fi, Adventure, Drama',
    year: 1968,
    runtime: '149 min',
    ageRating: 'G',
    rating: 8.3,
    cast: ['Keir Dullea', 'Gary Lockwood', 'William Sylvester'],
    boxOffice: '$146.4 million',
    budget: '$12 million',
    synopsis: "Humanity’s first steps into deep space collide with the unknown when a mysterious black monolith appears on the Moon, triggering a signal aimed at Jupiter. Astronaut Dave Bowman and the HAL 9000 AI embark on a psychedelic odyssey to investigate, confronting evolution, artificial intelligence, and the infinite mysteries of the cosmos in one of cinema’s most visually groundbreaking and philosophically profound journeys.",
    poster: '/path/to/2001-poster.jpg',
    backdrop: '/path/to/2001-backdrop.jpg',
    backdrop_path: '/path/to/2001-backdrop.jpg',
    poster_path: '/path/to/2001-poster.jpg',
    scenes: [
      { time: 15, intensity: 40, label: 'Moon Discovery', color: '#0f0f23' },
      { time: 45, intensity: 65, label: 'HAL Malfunction', color: '#ff4444' },
      { time: 85, intensity: 80, label: 'Jupiter Approach', color: '#ffaa00' },
      { time: 115, intensity: 92, label: 'Star Gate Sequence', color: '#00aaff' },
      { time: 140, intensity: 98, label: 'Beyond the Infinite', color: '#ffffff' }
    ],
    mysteryComplexity: 96,
    dominantColor: '#000080',
    dna: { SciFi: 70, Mystery: 20, Drama: 10 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt2543164',
    tmdbId: 283145,
    title: 'Arrival',
    director: 'Denis Villeneuve',
    genre: 'Sci-Fi, Drama, Mystery',
    year: 2016,
    runtime: '116 min',
    ageRating: 'PG-13',
    rating: 7.9,
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    boxOffice: '$203.4 million',
    budget: '$47 million',
    synopsis: "Linguist Louise Banks races against global panic to decipher the cryptic language of twelve alien spacecraft hovering silently over Earth. As she communicates with the enigmatic heptapod visitors, profound revelations about time, loss, and human connection unfold, forcing world leaders to confront whether contact means salvation or catastrophe.",
    poster: '/path/to/arrival-poster.jpg',
    backdrop: '/path/to/arrival-backdrop.jpg',
    backdrop_path: '/path/to/arrival-backdrop.jpg',
    poster_path: '/path/to/arrival-poster.jpg',
    scenes: [
      { time: 12, intensity: 35, label: 'First Contact', color: '#1a1a2e' },
      { time: 38, intensity: 62, label: 'Heptapod Language', color: '#16213e' },
      { time: 65, intensity: 78, label: 'Time Visions', color: '#0f3460' },
      { time: 92, intensity: 88, label: 'Global Crisis', color: '#533483' },
      { time: 108, intensity: 95, label: 'Non-Linear Revelation', color: '#e94560' }
    ],
    mysteryComplexity: 98,
    dominantColor: '#0f3460',
    dna: { SciFi: 55, Drama: 25, Mystery: 20 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt0118884',
    tmdbId: 1822,
    title: 'Contact',
    director: 'Robert Zemeckis',
    genre: 'Sci-Fi, Drama, Mystery',
    year: 1997,
    runtime: '150 min',
    ageRating: 'PG',
    rating: 7.5,
    cast: ['Jodie Foster', 'Matthew McConaughey', 'Tom Skerritt'],
    boxOffice: '$171.1 million',
    budget: '$90 million',
    synopsis: "SETI scientist Dr. Ellie Arroway detects the first extraterrestrial signal—a repeating pattern containing blueprints for a cosmic machine. Battling skepticism, religious opposition, and political intrigue, she becomes humanity’s ambassador for first contact, embarking on a mind-altering journey that blurs science, faith, and the search for meaning in the universe.",
    poster: '/path/to/contact-poster.jpg',
    backdrop: '/path/to/contact-backdrop.jpg',
    backdrop_path: '/path/to/contact-backdrop.jpg',
    poster_path: '/path/to/contact-poster.jpg',
    scenes: [
      { time: 22, intensity: 42, label: 'Signal Detection', color: '#001f3f' },
      { time: 58, intensity: 68, label: 'Vega Message', color: '#0074D9' },
      { time: 92, intensity: 82, label: 'Machine Blueprint', color: '#7FDBFF' },
      { time: 120, intensity: 90, label: 'Launch Tension', color: '#39CCCC' },
      { time: 142, intensity: 97, label: 'The Journey', color: '#3D9970' }
    ],
    mysteryComplexity: 94,
    dominantColor: '#001f3f',
    dna: { SciFi: 60, Drama: 25, Mystery: 15 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt0069293',
    tmdbId: 508,
    title: 'Solaris',
    director: 'Andrei Tarkovsky',
    genre: 'Sci-Fi, Drama, Mystery',
    year: 1972,
    runtime: '167 min',
    ageRating: 'PG',
    rating: 8.0,
    cast: ['Donatas Banionis', 'Natalya Bondarchuk', 'Jüri Järvet'],
    boxOffice: '$1 million (est.)',
    budget: '$1 million (est.)',
    synopsis: "Psychologist Kris Kelvin arrives at the orbital station Solaris to investigate why the crew is unraveling amid ghostly apparitions of their deepest memories and regrets. The sentient ocean planet manifests human subconscious desires as physical entities, forcing Kelvin into an existential confrontation with love, guilt, and the limits of rational science.",
    poster: '/path/to/solaris-poster.jpg',
    backdrop: '/path/to/solaris-backdrop.jpg',
    backdrop_path: '/path/to/solaris-backdrop.jpg',
    poster_path: '/path/to/solaris-poster.jpg',
    scenes: [
      { time: 25, intensity: 38, label: 'Station Arrival', color: '#2c1810' },
      { time: 55, intensity: 65, label: 'Hari Appears', color: '#3c2f2f' },
      { time: 90, intensity: 78, label: 'Ocean Contact', color: '#4682b4' },
      { time: 130, intensity: 89, label: 'Memory Flood', color: '#87ceeb' },
      { time: 158, intensity: 96, label: 'Final Communion', color: '#4169e1' }
    ],
    mysteryComplexity: 99,
    dominantColor: '#2c1810',
    dna: { SciFi: 65, Drama: 20, Mystery: 15 },
    sensitiveScenes: [
      { start: "1:45:00", end: "1:46:30", description: "Intimate embrace (non-explicit)" }
    ]
  },
  {
    imdbID: 'tt1213641',
    tmdbId: 338968,
    title: 'First Man',
    director: 'Damien Chazelle',
    genre: 'Drama, History, Biography',
    year: 2018,
    runtime: '141 min',
    ageRating: 'PG-13',
    rating: 7.3,
    cast: ['Ryan Gosling', 'Claire Foy', 'Jason Clarke'],
    boxOffice: '$105.7 million',
    budget: '$59 million',
    synopsis: "Neil Armstrong’s intensely personal, high-risk journey to become the first man on the Moon—from the X-15 test flights through the tragic Apollo 1 fire to the historic Apollo 11 mission. A raw, immersive portrait of sacrifice, grief, and unbreakable resolve amid NASA’s perilous space race.",
    poster: '/path/to/firstman-poster.jpg',
    backdrop: '/path/to/firstman-backdrop.jpg',
    backdrop_path: '/path/to/firstman-backdrop.jpg',
    poster_path: '/path/to/firstman-poster.jpg',
    scenes: [
      { time: 8, intensity: 55, label: 'X-15 Test', color: '#ff6b35' },
      { time: 35, intensity: 72, label: 'Apollo 1 Fire', color: '#e63946' },
      { time: 68, intensity: 85, label: 'Gemini 8', color: '#f77f00' },
      { time: 105, intensity: 92, label: 'Moon Landing', color: '#264653' },
      { time: 135, intensity: 95, label: 'One Small Step', color: '#2a9d8f' }
    ],
    mysteryComplexity: 78,
    dominantColor: '#264653',
    dna: { Drama: 60, History: 25, SciFi: 15 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt3659388',
    tmdbId: 286217,
    title: 'The Martian',
    director: 'Ridley Scott',
    genre: 'Sci-Fi, Adventure, Drama',
    year: 2015,
    runtime: '144 min',
    ageRating: 'PG-13',
    rating: 8.0,
    cast: ['Matt Damon', 'Jessica Chastain', 'Kristen Wiig'],
    boxOffice: '$630.2 million',
    budget: '$108 million',
    synopsis: "Stranded on Mars after a dust storm, botanist Mark Watney must science his way to survival—growing potatoes, hacking satellites, and outsmarting NASA’s best minds 140 million miles away. A triumphant tale of ingenuity, humor, and human resilience against the red planet’s unforgiving isolation.",
    poster: '/path/to/martian-poster.jpg',
    backdrop: '/path/to/martian-backdrop.jpg',
    backdrop_path: '/path/to/martian-backdrop.jpg',
    poster_path: '/path/to/martian-poster.jpg',
    scenes: [
      { time: 10, intensity: 45, label: 'Storm Hits', color: '#d62828' },
      { time: 32, intensity: 60, label: 'Potato Farm', color: '#ffa62b' },
      { time: 70, intensity: 75, label: 'NASA Rescue Plan', color: '#457b9d' },
      { time: 110, intensity: 88, label: 'Slingshot Maneuver', color: '#a8dadc' },
      { time: 138, intensity: 94, label: 'Homecoming', color: '#1d3557' }
    ],
    mysteryComplexity: 82,
    dominantColor: '#e29578',
    dna: { SciFi: 50, Adventure: 30, Drama: 20 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt1454468',
    tmdbId: 76958,
    title: 'Gravity',
    director: 'Alfonso Cuarón',
    genre: 'Sci-Fi, Thriller, Drama',
    year: 2013,
    runtime: '91 min',
    ageRating: 'PG-13',
    rating: 7.7,
    cast: ['Sandra Bullock', 'George Clooney', 'Ed Harris'],
    boxOffice: '$723.2 million',
    budget: '$100 million',
    synopsis: "Medical engineer Ryan Stone and astronaut Matt Kowalski are hurled into the void after satellite debris obliterates their shuttle. In a desperate 90-minute fight for survival, Stone confronts terror, isolation, and her own will to live amid the silent, merciless expanse of space.",
    poster: '/path/to/gravity-poster.jpg',
    backdrop: '/path/to/gravity-backdrop.jpg',
    backdrop_path: '/path/to/gravity-backdrop.jpg',
    poster_path: '/path/to/gravity-poster.jpg',
    scenes: [
      { time: 5, intensity: 50, label: 'Debris Strike', color: '#ff4757' },
      { time: 22, intensity: 70, label: 'ISS Drift', color: '#ffa502' },
      { time: 45, intensity: 85, label: 'Tiangong Panic', color: '#2ed573' },
      { time: 68, intensity: 92, label: 'Reentry Fire', color: '#ff6348' },
      { time: 88, intensity: 96, label: 'Ocean Landing', color: '#3742fa' }
    ],
    mysteryComplexity: 75,
    dominantColor: '#0a2342',
    dna: { SciFi: 55, Thriller: 30, Drama: 15 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt0448134',
    tmdbId: 38626,
    title: 'Sunshine',
    director: 'Danny Boyle',
    genre: 'Sci-Fi, Thriller, Drama',
    year: 2007,
    runtime: '107 min',
    ageRating: 'R',
    rating: 7.2,
    cast: ['Cillian Murphy', 'Rose Byrne', 'Chris Evans'],
    boxOffice: '$29 million',
    budget: '$40 million',
    synopsis: "Eight astronauts on the Icarus II deliver a stellar bomb to reignite the dying Sun and save Earth. When they discover the lost Icarus I, madness, sacrifice, and cosmic horror test the boundaries of science, faith, and sanity in a mission where light itself becomes the enemy.",
    poster: '/path/to/sunshine-poster.jpg',
    backdrop: '/path/to/sunshine-backdrop.jpg',
    backdrop_path: '/path/to/sunshine-backdrop.jpg',
    poster_path: '/path/to/sunshine-poster.jpg',
    scenes: [
      { time: 18, intensity: 42, label: 'Icarus I Signal', color: '#ffd23f' },
      { time: 40, intensity: 68, label: 'Crew Fracture', color: '#ff6b35' },
      { time: 72, intensity: 82, label: 'Payload Breach', color: '#f7931e' },
      { time: 88, intensity: 90, label: 'Solar Glare', color: '#ffffff' },
      { time: 102, intensity: 97, label: 'Final Ignition', color: '#ff4757' }
    ],
    mysteryComplexity: 92,
    dominantColor: '#ffd23f',
    dna: { SciFi: 65, Thriller: 25, Drama: 10 },
    sensitiveScenes: [
      { start: "1:20:00", end: "1:21:30", description: "Nudity (non-sexual, sacrificial)" }
    ]
  },
  {
    imdbID: 'tt1182345',
    tmdbId: 24887,
    title: 'Moon',
    director: 'Duncan Jones',
    genre: 'Sci-Fi, Drama, Mystery',
    year: 2009,
    runtime: '97 min',
    ageRating: 'R',
    rating: 7.8,
    cast: ['Sam Rockwell', 'Kevin Spacey', 'Dominique McElligott'],
    boxOffice: '$9.8 million',
    budget: '$5 million',
    synopsis: "Lunar miner Sam Bell nears the end of his three-year helium-3 contract on the Moon when a rover crash reveals a shattering truth about isolation, identity, and corporate exploitation 384,000 km from Earth.",
    poster: '/path/to/moon-poster.jpg',
    backdrop: '/path/to/moon-backdrop.jpg',
    backdrop_path: '/path/to/moon-backdrop.jpg',
    poster_path: '/path/to/moon-poster.jpg',
    scenes: [
      { time: 12, intensity: 30, label: 'Rover Crash', color: '#a4b0be' },
      { time: 35, intensity: 58, label: 'Clone Discovery', color: '#dfe6e9' },
      { time: 62, intensity: 76, label: 'Memory Upload', color: '#74b9ff' },
      { time: 80, intensity: 88, label: 'Lunar Escape', color: '#0984e3' },
      { time: 92, intensity: 94, label: 'Truth Revealed', color: '#6c5ce7' }
    ],
    mysteryComplexity: 97,
    dominantColor: '#bdc3c7',
    dna: { SciFi: 60, Drama: 25, Mystery: 15 },
    sensitiveScenes: []  // NO SEXUAL CONTENT FOUND
  },
  {
    imdbID: 'tt2935510',
    tmdbId: 530915,
    title: 'Ad Astra',
    director: 'James Gray',
    genre: 'Sci-Fi, Drama, Thriller',
    year: 2019,
    runtime: '123 min',
    ageRating: 'PG-13',
    rating: 6.5,
    cast: ['Brad Pitt', 'Tommy Lee Jones', 'Ruth Negga'],
    boxOffice: '$135 million',
    budget: '$80-90 million',
    synopsis: "Spacecraft commander Roy McBride journeys to Mars and Neptune to find his missing father, a pioneering astronaut whose secret experiments threaten Earth. A meditative odyssey through solitude, legacy, and the cold vastness of space.",
    poster: '/path/to/adastra-poster.jpg',
    backdrop: '/path/to/adastra-backdrop.jpg',
    backdrop_path: '/path/to/adastra-backdrop.jpg',
    poster_path: '/path/to/adastra-poster.jpg',
    scenes: [
      { time: 6, intensity: 52, label: 'Lunar Pirates', color: '#57606f' },
      { time: 28, intensity: 65, label: 'Mars Pit Stop', color: '#dd3e54' },
      { time: 55, intensity: 78, label: 'Cepheus Log', color: '#f18f01' },
      { time: 90, intensity: 87, label: 'Lima Incident', color: '#c44569' },
      { time: 115, intensity: 93, label: 'Nebula Confrontation', color: '#9b59b6' }
    ],
    mysteryComplexity: 89,
    dominantColor: '#2c3e50',
    dna: { SciFi: 55, Drama: 30, Thriller: 15 },
    sensitiveScenes: [
      { start: "0:45:00", end: "0:46:00", description: "Intimate moment (brief)" }
    ]
  }
];

// Build object map by tmdbId
export const COMPLETE_INTERSTELLAR_LIKE_DATABASE = Object.fromEntries(
  INTERSTELLAR_LIKE_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_INTERSTELLAR_LIKE_DATABASE;
