// utils/mysteryThrillerMovieData.js - ULTIMATE MYSTERY THRILLER COLLECTION ✅ WITH DNA & SENSITIVE CONTENT

export const MYSTERY_THRILLER_MOVIES = [
  {
    imdbID: 'tt0114369',
    tmdbId: 807,
    title: 'Se7en',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 1995,
    runtime: '127 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'],
    boxOffice: '$327.3 million',
    budget: '$33 million',
    synopsis: "Dark, relentless serial killer investigation; a psychological nightmare with a groundbreaking twist.",
    poster: '/path/to/se7en-poster.jpg',
    backdrop: '/path/to/se7en-backdrop.jpg',
    backdrop_path: '/path/to/se7en-backdrop.jpg',
    poster_path: '/path/to/se7en-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Sin 1: Gluttony', color: '#b91c1c' },
      { time: 38, intensity: 65, label: 'Sin 3: Greed', color: '#f87171' },
      { time: 77, intensity: 85, label: 'Sin 5: Lust', color: '#fbbf24' },
      { time: 102, intensity: 92, label: 'Desert Confrontation', color: '#fde68a' },
      { time: 120, intensity: 98, label: "What's in the Box?", color: '#dc2626' }
    ],
    mysteryIntensity: 98,
    dominantColor: '#8b1e3f',
    dna: { Mystery: 50, Thriller: 40, Crime: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1130884',
    tmdbId: 11324,
    title: 'Shutter Island',
    director: 'Martin Scorsese',
    genre: 'Mystery, Thriller',
    year: 2010,
    runtime: '138 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley'],
    boxOffice: '$294.8 million',
    budget: '$80 million',
    synopsis: "Intense psychological thriller exploring paranoia and reality; masterful suspense and haunting twists.",
    poster: '/path/to/shutter-poster.jpg',
    backdrop: '/path/to/shutter-backdrop.jpg',
    backdrop_path: '/path/to/shutter-backdrop.jpg',
    poster_path: '/path/to/shutter-poster.jpg',
    scenes: [
      { time: 14, intensity: 38, label: 'Ferry Arrival', color: '#223344' },
      { time: 42, intensity: 60, label: 'First Search', color: '#467ecc' },
      { time: 83, intensity: 71, label: 'Night Storm', color: '#a8e063' },
      { time: 110, intensity: 89, label: "The Lighthouse", color: '#fbbf24' },
      { time: 136, intensity: 97, label: "Truth Revealed", color: '#e94e77' }
    ],
    mysteryIntensity: 97,
    dominantColor: '#1c253d',
    dna: { Mystery: 50, Thriller: 40, Drama: 10 },
    sensitiveScenes: [
      { start: "1:10:43", end: "1:10:47", description: "Nudity (men)" },
      { start: "1:59:03", end: "1:59:06", description: "Casual kissing" }
    ]
  },
  {
    imdbID: 'tt1392214',
    tmdbId: 146233,
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    genre: 'Crime, Drama, Mystery',
    year: 2013,
    runtime: '153 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'],
    boxOffice: '$122.1 million',
    budget: '$46 million',
    synopsis: "Tense, morally complex kidnapping case with gripping investigation and suspense.",
    poster: '/path/to/prisoners-poster.jpg',
    backdrop: '/path/to/prisoners-backdrop.jpg',
    backdrop_path: '/path/to/prisoners-backdrop.jpg',
    poster_path: '/path/to/prisoners-poster.jpg',
    scenes: [
      { time: 20, intensity: 58, label: 'Abduction', color: '#a11515' },
      { time: 49, intensity: 75, label: 'First Search', color: '#f87171' },
      { time: 93, intensity: 82, label: 'Torture', color: '#fbbf24' },
      { time: 120, intensity: 90, label: 'Maze Hints', color: '#fde68a' },
      { time: 145, intensity: 96, label: 'Buried Alive', color: '#dc2626' }
    ],
    mysteryIntensity: 96,
    dominantColor: '#042258ff',
    dna: { Crime: 45, Thriller: 40, Mystery: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0443706',
    tmdbId: 1949,
    title: 'Zodiac',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 2007,
    runtime: '157 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Jake Gyllenhaal', 'Robert Downey Jr.', 'Mark Ruffalo'],
    boxOffice: '$84.8 million',
    budget: '$65 million',
    synopsis: "Obsessive real-life serial killer investigation; atmospheric and slowly mounting tension.",
    poster: '/path/to/zodiac-poster.jpg',
    backdrop: '/path/to/zodiac-backdrop.jpg',
    backdrop_path: '/path/to/zodiac-backdrop.jpg',
    poster_path: '/path/to/zodiac-poster.jpg',
    scenes: [
      { time: 14, intensity: 30, label: 'Lake Berryessa', color: '#7285a5' },
      { time: 67, intensity: 58, label: 'Paul Stine', color: '#9a8e3f' },
      { time: 102, intensity: 71, label: 'Basement', color: '#bcafab' },
      { time: 134, intensity: 87, label: 'Confrontation', color: '#ebc634' },
      { time: 148, intensity: 94, label: "Graysmith's Realization", color: '#b23c65' }
    ],
    mysteryIntensity: 94,
    dominantColor: '#4a6187',
    dna: { Mystery: 60, Thriller: 25, Crime: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt2267998',
    tmdbId: 210577,
    title: 'Gone Girl',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 2014,
    runtime: '149 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
    boxOffice: '$369.3 million',
    budget: '$61 million',
    synopsis: "Dark psychological mystery filled with shocking twists and unreliable narration.",
    poster: '/path/to/gonegirl-poster.jpg',
    backdrop: '/path/to/gonegirl-backdrop.jpg',
    backdrop_path: '/path/to/gonegirl-backdrop.jpg',
    poster_path: '/path/to/gonegirl-poster.jpg',
    scenes: [
      { time: 15, intensity: 38, label: 'Anniversary', color: '#567ccd' },
      { time: 49, intensity: 62, label: 'Detective Arrives', color: '#9bcc56' },
      { time: 93, intensity: 77, label: 'Amy Reveal', color: '#ccb656' },
      { time: 126, intensity: 86, label: 'Plot Twist', color: '#dcbd56' },
      { time: 145, intensity: 95, label: 'Return Home', color: '#c65454' }
    ],
    mysteryIntensity: 95,
    dominantColor: '#a6785d',
    dna: { Mystery: 50, Thriller: 40, Drama: 10 },
    sensitiveScenes: [
      { start: "6:41", end: "6:59", description: "Sex" },
      { start: "20:57", end: "21:04", description: "Sex" },
      { start: "43:20", end: "44:54", description: "Passionate kissing and partial nudity" },
      { start: "45:00", end: "45:10", description: "Sex" },
      { start: "2:00:10", end: "2:00:15", description: "Kissing" },
      { start: "2:03:50", end: "2:04:55", description: "Sex" },
      { start: "2:12:30", end: "2:13:45", description: "Nudity" }
    ]
  },
  {
    imdbID: 'tt0353969',
    tmdbId: 11423,
    title: 'Memories of Murder',
    director: 'Bong Joon Ho',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '132 min',
    ageRating: 'NR',
    rating: 8.1,
    cast: ['Song Kang-ho', 'Kim Sang-kyung', 'Kim Roi-ha'],
    boxOffice: '$20.1 million',
    budget: '$2 million',
    synopsis: "Atmospheric procedural with slow-building mystery and unresolved tension.",
    poster: '/path/to/memories-poster.jpg',
    backdrop: '/path/to/memories-backdrop.jpg',
    backdrop_path: '/path/to/memories-backdrop.jpg',
    poster_path: '/path/to/memories-poster.jpg',
    scenes: [
      { time: 18, intensity: 39, label: 'First Crime Scene', color: '#b91c1c' },
      { time: 50, intensity: 59, label: 'Railroad Interrogation', color: '#f87171' },
      { time: 87, intensity: 70, label: 'Suspect Hunt', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'The Confrontation', color: '#fde68a' },
      { time: 128, intensity: 93, label: 'Haunting End', color: '#dc2626' }
    ],
    mysteryIntensity: 97,
    dominantColor: '#313a35',
    dna: { Mystery: 55, Crime: 25, Thriller: 20 },
    sensitiveScenes: [
      { start: "9:58", end: "10:10", description: "Sex" },
      { start: "54:34", end: "54:55", description: "Nudity (men)" },
      { start: "1:01:12", end: "1:02:40", description: "Masturbating (man)" },
      { start: "1:25:12", end: "1:25:47", description: "Partial nudity (woman)" }
    ]
  },
  {
    imdbID: 'tt4857264',
    tmdbId: 411088,
    title: 'The Invisible Guest',
    director: 'Oriol Paulo',
    genre: 'Mystery, Thriller',
    year: 2016,
    runtime: '106 min',
    ageRating: 'TV-14',
    rating: 8.1,
    cast: ['Mario Casas', 'Ana Wagener', 'Jose Coronado'],
    boxOffice: '$33.5 million',
    budget: '$4 million',
    synopsis: "Fast-paced, clever thriller filled with intricate misdirection.",
    poster: '/path/to/invisibleguest-poster.jpg',
    backdrop: '/path/to/invisibleguest-backdrop.jpg',
    backdrop_path: '/path/to/invisibleguest-backdrop.jpg',
    poster_path: '/path/to/invisibleguest-poster.jpg',
    scenes: [
      { time: 17, intensity: 34, label: 'Lawyer Visit', color: '#756967' },
      { time: 37, intensity: 54, label: 'Flashback', color: '#aeae58' },
      { time: 63, intensity: 70, label: 'Testimony', color: '#5681ae' },
      { time: 85, intensity: 85, label: 'Twist', color: '#a67ca8' },
      { time: 101, intensity: 93, label: "Truth", color: '#1f8a70' }
    ],
    mysteryIntensity: 93,
    dominantColor: '#5d6c8f',
    dna: { Mystery: 60, Thriller: 40 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt7282468',
    tmdbId: 491584,
    title: 'Burning',
    director: 'Lee Chang-dong',
    genre: 'Drama, Mystery, Thriller',
    year: 2018,
    runtime: '148 min',
    ageRating: 'NR',
    rating: 7.5,
    cast: ['Yoo Ah-in', 'Steven Yeun', 'Jeon Jong-seo'],
    boxOffice: '$7.2 million',
    budget: '$4 million',
    synopsis: "Ambiguous, slow-burn psychological mystery layered with subtle tension.",
    poster: '/path/to/burning-poster.jpg',
    backdrop: '/path/to/burning-backdrop.jpg',
    backdrop_path: '/path/to/burning-backdrop.jpg',
    poster_path: '/path/to/burning-poster.jpg',
    scenes: [
      { time: 18, intensity: 23, label: 'Greenhouse', color: '#2ef2a1' },
      { time: 54, intensity: 55, label: 'Vanishing', color: '#dbe039' },
      { time: 102, intensity: 73, label: 'Dinner', color: '#e0d339' },
      { time: 137, intensity: 89, label: 'The Confession', color: '#f94040' },
      { time: 142, intensity: 92, label: "Ending", color: '#b17e56' }
    ],
    mysteryIntensity: 92,
    dominantColor: '#c4377a',
    dna: { Mystery: 65, Drama: 25, Thriller: 10 },
    sensitiveScenes: [
      { start: "15:00", end: "18:20", description: "Passionate kissing + sex" },
      { start: "29:30", end: "30:00", description: "Masturbation not graphic (man)" },
      { start: "35:10", end: "35:39", description: "Masturbation not graphic (man)" },
      { start: "1:08:35", end: "1:11:25", description: "Partial nudity (woman)" },
      { start: "2:13:30", end: "2:14:07", description: "Masturbation not graphic (man)" }
    ]
  },
  {
    imdbID: 'tt0119174',
    tmdbId: 2649,
    title: 'The Game',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 1997,
    runtime: '129 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Michael Douglas', 'Sean Penn', 'Deborah Kara Unger'],
    boxOffice: '$109.4 million',
    budget: '$50 million',
    synopsis: "Paranoia-soaked psychological puzzle with unpredictable and disturbing twists.",
    poster: '/path/to/game-poster.jpg',
    backdrop: '/path/to/game-backdrop.jpg',
    backdrop_path: '/path/to/game-backdrop.jpg',
    poster_path: '/path/to/game-poster.jpg',
    scenes: [
      { time: 13, intensity: 32, label: 'Birthday', color: '#6d4c41' },
      { time: 43, intensity: 58, label: 'Breakdown', color: '#6d8f41' },
      { time: 66, intensity: 73, label: 'Buried Alive', color: '#418f6d' },
      { time: 109, intensity: 80, label: 'Rooftop', color: '#dc8841' },
      { time: 129, intensity: 90, label: 'The End', color: '#d84315' }
    ],
    mysteryIntensity: 90,
    dominantColor: '#0f1423',
    dna: { Mystery: 50, Thriller: 40, Drama: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0119177',
    tmdbId: 2832,
    title: 'Identity',
    director: 'James Mangold',
    genre: 'Mystery, Thriller',
    year: 2003,
    runtime: '90 min',
    ageRating: 'R',
    rating: 7.3,
    cast: ['John Cusack', 'Ray Liotta', 'Amanda Peet'],
    boxOffice: '$90.2 million',
    budget: '$28 million',
    synopsis: "Psychological thriller with strangers trapped and a shocking, unforgettable reveal.",
    poster: '/path/to/identity-poster.jpg',
    backdrop: '/path/to/identity-backdrop.jpg',
    backdrop_path: '/path/to/identity-backdrop.jpg',
    poster_path: '/path/to/identity-poster.jpg',
    scenes: [
      { time: 6, intensity: 29, label: 'Car Accident', color: '#19799a' },
      { time: 31, intensity: 47, label: 'First Murder', color: '#eb4034' },
      { time: 53, intensity: 66, label: 'Storm', color: '#b1a9c6' },
      { time: 78, intensity: 83, label: 'Reveal', color: '#ebae34' },
      { time: 90, intensity: 93, label: 'Final Twist', color: '#6839eb' }
    ],
    mysteryIntensity: 93,
    dominantColor: '#3e464f',
    dna: { Mystery: 65, Thriller: 35 },
    sensitiveScenes: []
  }
];

// Build object map by tmdbId
export const COMPLETE_MYSTERY_THRILLER_DATABASE = Object.fromEntries(
  MYSTERY_THRILLER_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_MYSTERY_THRILLER_DATABASE;
