// utils/psychologicalThrillerMovieData.js - 10 BEST PSYCHOLOGICAL THRILLER MOVIES COLLECTION

export const PSYCH_THRILLER_MOVIES = [
  {
    imdbID: 'tt0102926',
    tmdbId: 274,
    title: 'The Silence of the Lambs',
    director: 'Jonathan Demme',
    genre: 'Crime, Drama, Thriller',
    year: 1991,
    runtime: '118 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    boxOffice: '$272.7 million',
    budget: '$19 million',
    synopsis: "The Silence of the Lambs (1991): A young, determined FBI trainee, Clarice Starling, is forced to seek the horrifyingly brilliant counsel of Dr. Hannibal Lecter, an imprisoned cannibalistic psychiatrist. Her mission: to gain insight into Lecter's mind to track down a new, active serial killer named \"Buffalo Bill.\" This is a definitive, high-stakes psychological chess match where the line between mentor and predator blurs completely.",
    poster: '/path/to/silence-poster.jpg',
    backdrop: '/path/to/silence-backdrop.jpg',
    backdrop_path: '/path/to/silence-backdrop.jpg',
    poster_path: '/path/to/silence-poster.jpg',
    scenes: [
      { time: 10, intensity: 35, label: 'First Interview', color: '#b91c1c' },
      { time: 46, intensity: 67, label: 'Lecter Escapes', color: '#f87171' },
      { time: 82, intensity: 79, label: 'Night Vision Stalk', color: '#fbbf24' },
      { time: 102, intensity: 89, label: 'Buffalo Bill', color: '#fde68a' },
      { time: 113, intensity: 94, label: 'Ending', color: '#dc2626' }
    ],
    suspenseIntensity: 94,
    dominantColor: '#72696e',
    dna: { Thriller: 55, Crime: 30, Horror: 15 },
    sensitiveScenes: [
      { start: '18:50', end: '18:57', description: 'Explicit Scene' },
      { start: '1:36:30', end: '1:36:37', description: 'Nudity (man)' }
    ]
  },
  {
    imdbID: 'tt0137523',
    tmdbId: 550,
    title: 'Fight Club',
    director: 'David Fincher',
    genre: 'Drama',
    year: 1999,
    runtime: '139 min',
    ageRating: 'R',
    rating: 8.8,
    cast: ['Edward Norton', 'Brad Pitt', 'Helena Bonham Carter'],
    boxOffice: '$101.2 million',
    budget: '$63 million',
    synopsis: "Fight Club (1999): An anonymous, insomniac office worker, disillusioned with his mundane consumer life, seeks a way out. He forms an underground fight club with the charismatic, anarchic soap salesman Tyler Durden. What starts as a simple outlet for primal aggression spirals into a dangerous and destructive domestic terrorist organization, all leading up to a famous, mind-bending identity twist.",
    poster: '/path/to/fightclub-poster.jpg',
    backdrop: '/path/to/fightclub-backdrop.jpg',
    backdrop_path: '/path/to/fightclub-backdrop.jpg',
    poster_path: '/path/to/fightclub-poster.jpg',
    scenes: [
      { time: 5, intensity: 40, label: 'Meeting Tyler Durden', color: '#b91c1c' },
      { time: 50, intensity: 70, label: 'Fight Club Formation', color: '#f87171' },
      { time: 100, intensity: 90, label: 'Fight to the End', color: '#fbbf24' },
      { time: 115, intensity: 95, label: 'Chaos Unleashed', color: '#fde68a' },
      { time: 125, intensity: 98, label: 'Final Twist', color: '#dc2626' }
    ],
    suspenseIntensity: 98,
    dominantColor: '#401e15',
    dna: { Drama: 70, Psychological: 20, Thriller: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0209144',
    tmdbId: 1124,
    title: 'Memento',
    director: 'Christopher Nolan',
    genre: 'Mystery, Thriller',
    year: 2000,
    runtime: '113 min',
    ageRating: 'R',
    rating: 8.4,
    cast: ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano'],
    boxOffice: '$39.7 million',
    budget: '$9 million',
    synopsis: "Memento (2000): Leonard Shelby is hunting the man who raped and murdered his wife. However, he suffers from a rare form of anterograde amnesia—he cannot form new memories. To cope, he uses a system of intricate notes, Polaroid photos, and mnemonic tattoos to piece together his life and his investigation, forcing the audience to follow his story in reverse chronological order.",
    poster: '/path/to/memento-poster.jpg',
    backdrop: '/path/to/memento-backdrop.jpg',
    backdrop_path: '/path/to/memento-backdrop.jpg',
    poster_path: '/path/to/memento-poster.jpg',
    scenes: [
      { time: 5, intensity: 40, label: 'Opening Black & White', color: '#b91c1c' },
      { time: 50, intensity: 60, label: 'Tattoos Explanation', color: '#f87171' },
      { time: 80, intensity: 75, label: 'Car Scene', color: '#fbbf24' },
      { time: 105, intensity: 85, label: 'Final Reveal', color: '#fde68a' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#2a2a2a',
    dna: { Mystery: 50, Thriller: 30, Drama: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0114369',
    tmdbId: 807,
    title: 'Se7en',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 1995,
    runtime: '127 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'],
    boxOffice: '$327.3 million',
    budget: '$33 million',
    synopsis: "Se7en (1995): Two disparate detectives—a weary, retiring veteran and an intense, young newcomer—are dropped into a perpetually rain-soaked, morally rotting city to hunt a chillingly methodical serial killer. This killer uses the seven deadly sins as the disturbing inspiration for his gruesome, symbolic murders. It’s a relentless, psychological nightmare that culminates in one of cinema’s most notorious and unforgettable twists.",
    poster: '/path/to/se7en-poster.jpg',
    backdrop: '/path/to/se7en-backdrop.jpg',
    backdrop_path: '/path/to/se7en-backdrop.jpg',
    poster_path: '/path/to/se7en-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Sin 1: Gluttony', color: '#b91c1c' },
      { time: 38, intensity: 65, label: 'Sin 3: Greed', color: '#f87171' },
      { time: 77, intensity: 85, label: 'Sin 5: Lust', color: '#fbbf24' },
      { time: 102, intensity: 92, label: 'Desert Confrontation', color: '#fde68a' },
      { time: 120, intensity: 98, label: "What's in the Box?", color: '#dc2626' }
    ],
    suspenseIntensity: 98,
    dominantColor: '#8b1e3f',
    dna: { Mystery: 50, Thriller: 40, Crime: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1130884',
    tmdbId: 68734,
    title: 'Shutter Island',
    director: 'Martin Scorsese',
    genre: 'Mystery, Thriller',
    year: 2010,
    runtime: '138 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley'],
    boxOffice: '$294 million',
    budget: '$80 million',
    synopsis: "Shutter Island (2010): In 1954, two U.S. Marshals arrive at a remote, foreboding island asylum for the criminally insane to investigate the baffling disappearance of a patient. As a massive hurricane cuts them off from the mainland, the lead investigator begins to unravel, tormented by flashes of his own violent past and growing suspicions about the true nature of the isolated hospital. It is a masterful, reality-bending plunge into paranoia.",
    poster: '/path/to/shutter-poster.jpg',
    backdrop: '/path/to/shutter-backdrop.jpg',
    backdrop_path: '/path/to/shutter-backdrop.jpg',
    poster_path: '/path/to/shutter-poster.jpg',
    scenes: [
      { time: 15, intensity: 40, label: 'Arrival', color: '#b91c1c' },
      { time: 60, intensity: 68, label: 'Interrogation Room', color: '#f87171' },
      { time: 95, intensity: 80, label: 'Storm Breaks', color: '#fbbf24' },
      { time: 110, intensity: 88, label: 'Hospital Secrets', color: '#fde68a' },
      { time: 130, intensity: 93, label: 'Truth Revealed', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#343a40',
    dna: { Mystery: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0947798',
    tmdbId: 15602,
    title: 'Black Swan',
    director: 'Darren Aronofsky',
    genre: 'Drama, Thriller',
    year: 2010,
    runtime: '108 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Natalie Portman', 'Mila Kunis', 'Vincent Cassel'],
    boxOffice: '$106.9 million',
    budget: '$13 million',
    synopsis: "Black Swan (2010): Nina, a painfully dedicated and fragile ballerina, lands the coveted lead role in a production of Swan Lake. As the pressure of perfection mounts and the line between her disciplined existence and the seductive chaos of her performance blurs, Nina descends into a terrifying psychological breakdown. Her obsession with the role threatens to consume her, blurring the lines between reality, competition, and hallucination.",
    poster: '/path/to/blackswan-poster.jpg',
    backdrop: '/path/to/blackswan-backdrop.jpg',
    backdrop_path: '/path/to/blackswan-backdrop.jpg',
    poster_path: '/path/to/blackswan-poster.jpg',
    scenes: [
      { time: 12, intensity: 38, label: 'Audition', color: '#b91c1c' },
      { time: 40, intensity: 62, label: 'Rehearsal Tension', color: '#f87171' },
      { time: 75, intensity: 80, label: 'Performance Panic', color: '#fbbf24' },
      { time: 95, intensity: 85, label: 'Psychological Breakdown', color: '#fde68a' },
      { time: 105, intensity: 90, label: 'Final Performance', color: '#dc2626' }
    ],
    suspenseIntensity: 85,
    dominantColor: '#552d32',
    dna: { Drama: 55, Thriller: 40, Psychological: 5 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0361862',
    tmdbId: 592,
    title: 'The Machinist',
    director: 'Brad Anderson',
    genre: 'Drama, Thriller',
    year: 2004,
    runtime: '101 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Christian Bale', 'Jennifer Jason Leigh', 'Aitana Sánchez-Gijón'],
    boxOffice: '$8.6 million',
    budget: '$5 million',
    synopsis: "The Machinist (2004): Trevor Reznik, a machine factory worker, hasn't slept in a year. Gaunt and mentally deteriorating, he is haunted by paranoia and inexplicable events after a workplace accident. As he frantically tries to uncover a sinister conspiracy against him, the audience is taken on a dizzying journey through insomnia and guilt, desperate to distinguish between objective reality and Trevor's shattered mind.",
    poster: '/path/to/machinist-poster.jpg',
    backdrop: '/path/to/machinist-backdrop.jpg',
    backdrop_path: '/path/to/machinist-backdrop.jpg',
    poster_path: '/path/to/machinist-poster.jpg',
    scenes: [
      { time: 7, intensity: 30, label: 'Sleeplessness', color: '#b91c1c' },
      { time: 35, intensity: 55, label: 'Paranoia', color: '#f87171' },
      { time: 65, intensity: 70, label: 'Conspiracy Reveal', color: '#fbbf24' },
      { time: 90, intensity: 80, label: 'Mental Breakdown', color: '#fde68a' },
      { time: 100, intensity: 85, label: 'Final Revelation', color: '#dc2626' }
    ],
    suspenseIntensity: 82,
    dominantColor: '#3b3b3b',
    dna: { Drama: 40, Thriller: 40, Psychological: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0364569',
    tmdbId: 785,
    title: 'Oldboy',
    director: 'Park Chan-wook',
    genre: 'Action, Drama, Mystery',
    year: 2003,
    runtime: '120 min',
    ageRating: 'R',
    rating: 8.4,
    cast: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung'],
    boxOffice: '$15.5 million',
    budget: '$3 million',
    synopsis: "Oldboy (2003): An ordinary man is kidnapped and inexplicably imprisoned in a dingy, isolated hotel room for fifteen long years without any explanation. Just as suddenly, he is released, given money, a cell phone, and five days to uncover the identity and motive of his tormentor. He embarks on a brutal quest for revenge, only to discover his freedom is part of an elaborate, horrifying, and pre-meditated plot.",
    poster: '/path/to/oldboy-poster.jpg',
    backdrop: '/path/to/oldboy-backdrop.jpg',
    backdrop_path: '/path/to/oldboy-backdrop.jpg',
    poster_path: '/path/to/oldboy-poster.jpg',
    scenes: [
      { time: 10, intensity: 40, label: 'Imprisonment', color: '#b91c1c' },
      { time: 60, intensity: 75, label: 'Revenge Planning', color: '#f87171' },
      { time: 95, intensity: 82, label: 'Escape and Hunt', color: '#fbbf24' },
      { time: 115, intensity: 90, label: 'Showdown', color: '#fde68a' },
      { time: 120, intensity: 93, label: 'Revelation', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#15232f',
    dna: { Drama: 40, Mystery: 30, Thriller: 30 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0075314',
    tmdbId: 2760,
    title: 'Taxi Driver',
    director: 'Martin Scorsese',
    genre: 'Crime, Drama',
    year: 1976,
    runtime: '114 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Robert De Niro', 'Jodie Foster', 'Harvey Keitel'],
    boxOffice: '$28.6 million',
    budget: '$12 million',
    synopsis: "Taxi Driver (1976): Travis Bickle, an isolated and deeply disturbed Vietnam veteran, works as a taxi driver on the sleazy, grimy streets of New York City. Unable to connect with society, he watches the city's moral decay with growing contempt. His loneliness curdles into violent obsession, leading him down a path of desperate political assassination plots and, eventually, a terrifying, righteous rampage.",
    poster: '/path/to/taxidriver-poster.jpg',
    backdrop: '/path/to/taxidriver-backdrop.jpg',
    backdrop_path: '/path/to/taxidriver-backdrop.jpg',
    poster_path: '/path/to/taxidriver-poster.jpg',
    scenes: [
      { time: 15, intensity: 40, label: 'Night Driving', color: '#b91c1c' },
      { time: 48, intensity: 65, label: 'Violent Version', color: '#f87171' },
      { time: 90, intensity: 80, label: 'Rampage', color: '#fbbf24' },
      { time: 110, intensity: 95, label: 'Final Shootout', color: '#fde68a' },
      { time: 113, intensity: 98, label: 'Ending', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#3f3a38',
    dna: { Drama: 50, Crime: 30, Thriller: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0081505',
    tmdbId: 694,
    title: 'The Shining',
    director: 'Stanley Kubrick',
    genre: 'Drama, Horror, Thriller',
    year: 1980,
    runtime: '146 min',
    ageRating: 'R',
    rating: 8.4,
    cast: ['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd'],
    boxOffice: '$44 million',
    budget: '$19 million',
    synopsis: "The Shining (1980): Jack Torrance, a struggling writer and recovering alcoholic, takes a job as the winter caretaker at the isolated Overlook Hotel in the Colorado Rockies. As heavy snow traps Jack and his family inside the immense, empty hotel, malevolent supernatural forces—and his own demons—begin to prey on his sanity, driving him into a terrifying, murderous madness.",
    poster: '/path/to/shining-poster.jpg',
    backdrop: '/path/to/shining-backdrop.jpg',
    backdrop_path: '/path/to/shining-backdrop.jpg',
    poster_path: '/path/to/shining-poster.jpg',
    scenes: [
      { time: 12, intensity: 38, label: 'First Snow', color: '#b91c1c' },
      { time: 50, intensity: 70, label: 'Meeting Grady', color: '#f87171' },
      { time: 95, intensity: 85, label: 'Maze Scenes', color: '#fbbf24' },
      { time: 130, intensity: 90, label: 'Blood Elevator', color: '#fde68a' },
      { time: 140, intensity: 95, label: 'The Finale', color: '#dc2626' }
    ],
    suspenseIntensity: 93,
    dominantColor: '#4b392d',
    dna: { Drama: 50, Horror: 30, Thriller: 20 },
    sensitiveScenes: []
  }
];

export const COMPLETE_PSYCH_THRILLER_DATABASE = Object.fromEntries(
  PSYCH_THRILLER_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_PSYCH_THRILLER_DATABASE;
