// utils/revengeMovieData.js - TOP 10 REVENGE MOVIES OF ALL TIME 🔥🗡️

export const REVENGE_MOVIES = [
  {
    imdbID: 'tt0364569',
    tmdbId: 670,
    title: 'Oldboy',
    director: 'Park Chan-wook',
    genre: 'Action, Drama, Mystery',
    year: 2003,
    runtime: '120 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jeong'],
    boxOffice: '$17.6 million',
    budget: '$3 million',
    synopsis: "Oh Dae-su, an ordinary salary man, is inexplicably kidnapped and imprisoned in a sealed, windowless hotel room for fifteen brutal years with no explanation. When he's suddenly released without warning, he emerges with one singular, all-consuming obsession: to discover who imprisoned him and why. What begins as a straightforward quest for vengeance spirals into a nightmarish, intensely disturbing mystery with one of cinema's most shocking, devastating revelations.",
    poster: '/path/to/oldboy-poster.jpg',
    backdrop: '/path/to/oldboy-backdrop.jpg',
    backdrop_path: '/path/to/oldboy-backdrop.jpg',
    poster_path: '/path/to/oldboy-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Abduction', color: '#2c3e50' },
      { time: 42, intensity: 62, label: 'Release', color: '#34495e' },
      { time: 68, intensity: 89, label: 'Corridor Fight', color: '#c0392b' },
      { time: 95, intensity: 76, label: 'Restaurant Revelation', color: '#e74c3c' },
      { time: 115, intensity: 99, label: 'The Truth', color: '#7f8c8d' }
    ],
    revengeIntensity: 99,
    dominantColor: '#2c3e50',
    dna: { Mystery: 40, Thriller: 35, Action: 25 },
    sensitiveScenes: [
      { start: "23:45", end: "25:12", description: "Sexual content" },
      { start: "1:15:20", end: "1:17:45", description: "Disturbing incestuous revelation" },
      { start: "1:45:30", end: "1:47:00", description: "Intense violence and torture" }
    ]
  },
  {
    imdbID: 'tt0172495',
    tmdbId: 98,
    title: 'Gladiator',
    director: 'Ridley Scott',
    genre: 'Action, Adventure, Drama',
    year: 2000,
    runtime: '155 min',
    ageRating: 'R',
    rating: 8.5,
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    boxOffice: '$465.4 million',
    budget: '$103 million',
    synopsis: "Maximus Decimus Meridius, Rome's most powerful and respected general, is betrayed by the corrupt, power-hungry prince Commodus, who murders Maximus' emperor-father and orders the execution of Maximus' family. Escaping death by the narrowest margin, Maximus is sold into slavery and forced to become a gladiator. Rising from the blood-soaked arenas of provincial Africa to the colossal Colosseum in Rome, he transforms from a broken slave into the people's champion, determined to exact brutal, public vengeance on the emperor who destroyed everything he loved.",
    poster: '/path/to/gladiator-poster.jpg',
    backdrop: '/path/to/gladiator-backdrop.jpg',
    backdrop_path: '/path/to/gladiator-backdrop.jpg',
    poster_path: '/path/to/gladiator-poster.jpg',
    scenes: [
      { time: 18, intensity: 52, label: 'Germania Battle', color: '#8b4513' },
      { time: 45, intensity: 78, label: 'Family Murdered', color: '#dc143c' },
      { time: 92, intensity: 70, label: 'First Colosseum Fight', color: '#ff8c00' },
      { time: 124, intensity: 88, label: 'Tiger Battle', color: '#ff4500' },
      { time: 148, intensity: 97, label: 'Final Duel', color: '#8b0000' }
    ],
    revengeIntensity: 98,
    dominantColor: '#8b4513',
    dna: { Action: 45, Drama: 35, Epic: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0105695',
    tmdbId: 33,
    title: 'Unforgiven',
    director: 'Clint Eastwood',
    genre: 'Drama, Western',
    year: 1992,
    runtime: '130 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Clint Eastwood', 'Gene Hackman', 'Morgan Freeman'],
    boxOffice: '$159.2 million',
    budget: '$14.4 million',
    synopsis: "William Munny, a once-notorious gunslinger turned peaceful pig farmer, is reluctantly pulled back into his violent past when a group of prostitutes offers a substantial bounty for killing two cowboys who brutally disfigured one of their own. Accompanied by his old partner Ned Logan and a young, naive gunslinger, Munny travels to the town of Big Whiskey, where he confronts the ruthless, sadistic sheriff Little Bill Daggett. This dark, morally complex Western strips away Hollywood myth to reveal the brutal, unglamorous reality of violence and the haunting toll revenge takes on the human soul.",
    poster: '/path/to/unforgiven-poster.jpg',
    backdrop: '/path/to/unforgiven-backdrop.jpg',
    backdrop_path: '/path/to/unforgiven-backdrop.jpg',
    poster_path: '/path/to/unforgiven-poster.jpg',
    scenes: [
      { time: 22, intensity: 38, label: 'The Proposition', color: '#8b7355' },
      { time: 56, intensity: 52, label: 'Journey to Big Whiskey', color: '#a0522d' },
      { time: 85, intensity: 68, label: 'Ned Captured', color: '#cd853f' },
      { time: 108, intensity: 82, label: "Ned's Death", color: '#8b4513' },
      { time: 124, intensity: 96, label: 'Saloon Showdown', color: '#2f4f4f' }
    ],
    revengeIntensity: 94,
    dominantColor: '#8b7355',
    dna: { Western: 50, Drama: 35, Action: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0112573',
    tmdbId: 197,
    title: 'Braveheart',
    director: 'Mel Gibson',
    genre: 'Biography, Drama, History',
    year: 1995,
    runtime: '178 min',
    ageRating: 'R',
    rating: 8.3,
    cast: ['Mel Gibson', 'Sophie Marceau', 'Patrick McGoohan'],
    boxOffice: '$213.2 million',
    budget: '$72 million',
    synopsis: "In late 13th-century Scotland, humble farmer William Wallace witnesses the brutal murder of his secret wife by English soldiers. Consumed by grief and rage, he transforms into a legendary warrior who unites the fractured Scottish clans to fight for freedom against the tyrannical rule of King Edward I of England. Leading a ragtag army of common men, Wallace ignites a rebellion that becomes a full-scale war for Scottish independence. This epic tale of courage, sacrifice, and vengeance follows one man's extraordinary fight against impossible odds.",
    poster: '/path/to/braveheart-poster.jpg',
    backdrop: '/path/to/braveheart-backdrop.jpg',
    backdrop_path: '/path/to/braveheart-backdrop.jpg',
    poster_path: '/path/to/braveheart-poster.jpg',
    scenes: [
      { time: 35, intensity: 62, label: "Murron's Murder", color: '#8b0000' },
      { time: 58, intensity: 75, label: 'First Rebellion', color: '#228b22' },
      { time: 95, intensity: 82, label: 'Battle of Stirling', color: '#4169e1' },
      { time: 138, intensity: 88, label: 'Battle of Falkirk', color: '#dc143c' },
      { time: 168, intensity: 97, label: 'Execution', color: '#2f4f4f' }
    ],
    revengeIntensity: 96,
    dominantColor: '#228b22',
    dna: { Epic: 45, War: 35, Drama: 20 },
    sensitiveScenes: [
      { start: "33:15", end: "34:45", description: "Graphic violence - throat slashing" },
      { start: "2:45:30", end: "2:50:00", description: "Torture and execution scene" }
    ]
  },
  {
    imdbID: 'tt0482571',
    tmdbId: 1124,
    title: 'The Prestige',
    director: 'Christopher Nolan',
    genre: 'Drama, Mystery, Sci-Fi',
    year: 2006,
    runtime: '130 min',
    ageRating: 'PG-13',
    rating: 8.5,
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson'],
    boxOffice: '$109.7 million',
    budget: '$40 million',
    synopsis: "In Victorian-era London, two talented stage magicians—Robert Angier and Alfred Borden—begin as friends and collaborators. But after a tragic accident during a performance kills Angier's wife, their relationship shatters into a bitter, all-consuming rivalry. Both men become obsessed with sabotaging each other's acts and discovering the secrets behind each other's greatest illusions. Their dangerous game of one-upmanship escalates to shocking extremes, with each willing to sacrifice everything—their careers, their loved ones, and ultimately their lives—to achieve the perfect trick and destroy the other.",
    poster: '/path/to/prestige-poster.jpg',
    backdrop: '/path/to/prestige-backdrop.jpg',
    backdrop_path: '/path/to/prestige-backdrop.jpg',
    poster_path: '/path/to/prestige-poster.jpg',
    scenes: [
      { time: 12, intensity: 58, label: 'The Drowning', color: '#2c3e50' },
      { time: 42, intensity: 65, label: 'Diary Discovery', color: '#34495e' },
      { time: 78, intensity: 74, label: 'Tesla Machine', color: '#4169e1' },
      { time: 105, intensity: 88, label: 'The Transported Man', color: '#8a2be2' },
      { time: 125, intensity: 97, label: 'The Final Prestige', color: '#191970' }
    ],
    revengeIntensity: 92,
    dominantColor: '#2c3e50',
    dna: { Mystery: 45, Drama: 35, Thriller: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1663202',
    tmdbId: 281957,
    title: 'The Revenant',
    director: 'Alejandro G. Iñárritu',
    genre: 'Action, Adventure, Drama',
    year: 2015,
    runtime: '156 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter'],
    boxOffice: '$533.0 million',
    budget: '$135 million',
    synopsis: "In the harsh, unforgiving wilderness of 1820s America, frontiersman Hugh Glass is mauled nearly to death by a grizzly bear during a fur trapping expedition. His companion, the treacherous John Fitzgerald, murders Glass's young son and leaves him for dead in the frozen landscape. Against all odds, Glass survives and embarks on an epic, grueling 200-mile journey of survival and revenge through brutal terrain, hostile elements, and indigenous conflicts to exact justice on the man who betrayed him.",
    poster: '/path/to/revenant-poster.jpg',
    backdrop: '/path/to/revenant-backdrop.jpg',
    backdrop_path: '/path/to/revenant-backdrop.jpg',
    poster_path: '/path/to/revenant-poster.jpg',
    scenes: [
      { time: 18, intensity: 72, label: 'Bear Attack', color: '#8b7355' },
      { time: 42, intensity: 81, label: 'Son Murdered', color: '#a0522d' },
      { time: 78, intensity: 68, label: 'River Escape', color: '#4682b4' },
      { time: 118, intensity: 85, label: 'Village Massacre', color: '#8b0000' },
      { time: 148, intensity: 94, label: 'Final Confrontation', color: '#2f4f4f' }
    ],
    revengeIntensity: 92,
    dominantColor: '#8b7355',
    dna: { Survival: 45, Drama: 35, Action: 20 },
    sensitiveScenes: [
      { start: "15:30", end: "18:45", description: "Graphic bear attack" },
      { start: "1:38:20", end: "1:40:30", description: "Graphic violence" }
    ]
  },
  {
    imdbID: 'tt0378194',
    tmdbId: 393,
    title: 'Kill Bill: Vol. 2',
    director: 'Quentin Tarantino',
    genre: 'Action, Crime, Thriller',
    year: 2004,
    runtime: '137 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Uma Thurman', 'David Carradine', 'Michael Madsen'],
    boxOffice: '$152.2 million',
    budget: '$30 million',
    synopsis: "The Bride continues her methodical quest of vengeance against the remaining members of the Deadly Viper Assassination Squad: the brutal, reclusive trailer-dwelling Budd and the treacherous, one-eyed California Mountain Snake, Elle Driver. Her journey culminates in a tense, emotional confrontation with Bill himself, the man she once loved and who orchestrated the massacre that nearly killed her and her unborn child. This volume completes her roaring rampage of revenge with psychological depth, shocking revelations, and a bittersweet reckoning.",
    poster: '/path/to/killbill2-poster.jpg',
    backdrop: '/path/to/killbill2-backdrop.jpg',
    backdrop_path: '/path/to/killbill2-backdrop.jpg',
    poster_path: '/path/to/killbill2-poster.jpg',
    scenes: [
      { time: 22, intensity: 62, label: 'Budd Betrayal', color: '#d4a574' },
      { time: 48, intensity: 78, label: 'Buried Alive', color: '#8b4513' },
      { time: 71, intensity: 83, label: 'Pai Mei Training', color: '#ffd700' },
      { time: 99, intensity: 88, label: 'Elle Driver Fight', color: '#dc143c' },
      { time: 129, intensity: 95, label: 'Bill Confrontation', color: '#2f4f4f' }
    ],
    revengeIntensity: 96,
    dominantColor: '#d4a574',
    dna: { Action: 45, Drama: 35, Thriller: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt2911666',
    tmdbId: 245891,
    title: 'John Wick',
    director: 'Chad Stahelski',
    genre: 'Action, Crime, Thriller',
    year: 2014,
    runtime: '101 min',
    ageRating: 'R',
    rating: 7.4,
    cast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'],
    boxOffice: '$86.1 million',
    budget: '$20 million',
    synopsis: "John Wick, a legendary retired hitman living in peaceful mourning after his wife's death, is pulled violently back into the criminal underworld he left behind when a group of foolish Russian mobsters break into his home, steal his prized 1969 Mustang, and kill the puppy his late wife left him as a final gift. This seemingly small act ignites an unstoppable wave of vengeance as Wick systematically dismantles an entire criminal empire with brutal, balletic precision to punish those who took the last symbol of his wife's love.",
    poster: '/path/to/johnwick-poster.jpg',
    backdrop: '/path/to/johnwick-backdrop.jpg',
    backdrop_path: '/path/to/johnwick-backdrop.jpg',
    poster_path: '/path/to/johnwick-poster.jpg',
    scenes: [
      { time: 15, intensity: 68, label: 'Home Invasion', color: '#2c3e50' },
      { time: 32, intensity: 75, label: 'Red Circle Assault', color: '#c0392b' },
      { time: 58, intensity: 82, label: 'Church Shootout', color: '#e74c3c' },
      { time: 78, intensity: 88, label: 'Nightclub Battle', color: '#dc143c' },
      { time: 95, intensity: 94, label: 'Final Showdown', color: '#8b0000' }
    ],
    revengeIntensity: 95,
    dominantColor: '#2c3e50',
    dna: { Action: 70, Thriller: 20, Crime: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1588170',
    tmdbId: 44222,
    title: 'I Saw the Devil',
    director: 'Kim Jee-woon',
    genre: 'Action, Crime, Horror',
    year: 2010,
    runtime: '144 min',
    ageRating: 'NR',
    rating: 7.8,
    cast: ['Lee Byung-hun', 'Choi Min-sik', 'Jeon Gook-hwan'],
    boxOffice: '$13.0 million',
    budget: '$6 million',
    synopsis: "When a sadistic serial killer brutally murders his pregnant fiancée, elite special agent Soo-hyun embarks on a harrowing, personal vendetta that crosses every moral boundary. Rather than simply killing the monster, he chooses to torture him in the most psychologically devastating way possible: capturing him, brutalizing him, releasing him, and hunting him down again in an endless, vicious cycle. This is an unflinching, extraordinarily violent exploration of how the pursuit of revenge can transform a righteous man into the very evil he's hunting.",
    poster: '/path/to/isawthedevil-poster.jpg',
    backdrop: '/path/to/isawthedevil-backdrop.jpg',
    backdrop_path: '/path/to/isawthedevil-backdrop.jpg',
    poster_path: '/path/to/isawthedevil-poster.jpg',
    scenes: [
      { time: 8, intensity: 68, label: 'Brutal Murder', color: '#8b0000' },
      { time: 42, intensity: 77, label: 'First Capture', color: '#b22222' },
      { time: 78, intensity: 86, label: 'Taxi Slaughter', color: '#dc143c' },
      { time: 112, intensity: 91, label: 'Greenhouse Torture', color: '#ff0000' },
      { time: 138, intensity: 98, label: 'Final Reckoning', color: '#4b0000' }
    ],
    revengeIntensity: 99,
    dominantColor: '#8b0000',
    dna: { Thriller: 45, Horror: 35, Action: 20 },
    sensitiveScenes: [
      { start: "3:45", end: "7:30", description: "Graphic violence and sexual assault" },
      { start: "45:20", end: "47:15", description: "Extreme torture and violence" },
      { start: "1:18:30", end: "1:22:00", description: "Graphic murder sequence" }
    ]
  },
  {
    imdbID: 'tt0245844',
    tmdbId: 11362,
    title: 'The Count of Monte Cristo',
    director: 'Kevin Reynolds',
    genre: 'Action, Adventure, Drama',
    year: 2002,
    runtime: '131 min',
    ageRating: 'PG-13',
    rating: 7.7,
    cast: ['Jim Caviezel', 'Guy Pearce', 'Richard Harris'],
    boxOffice: '$75.4 million',
    budget: '$35 million',
    synopsis: "In 1815, naive young sailor Edmond Dantès is on the cusp of marrying the love of his life and earning a prestigious captaincy. But his envious best friend Fernand Mondego and scheming colleague Danglars falsely accuse him of treason, condemning him to rot in the nightmarish island prison fortress of Château d'If. After fourteen years, Dantès escapes, discovers an unimaginable hidden fortune, and transforms himself into the wealthy, mysterious Count of Monte Cristo. He returns to exact meticulous, devastating revenge on every person who destroyed his life.",
    poster: '/path/to/monte-cristo-poster.jpg',
    backdrop: '/path/to/monte-cristo-backdrop.jpg',
    backdrop_path: '/path/to/monte-cristo-backdrop.jpg',
    poster_path: '/path/to/monte-cristo-poster.jpg',
    scenes: [
      { time: 15, intensity: 48, label: 'Betrayal', color: '#34495e' },
      { time: 38, intensity: 55, label: 'Prison Years', color: '#2c3e50' },
      { time: 62, intensity: 68, label: 'Escape & Treasure', color: '#f39c12' },
      { time: 95, intensity: 82, label: 'Systematic Revenge', color: '#e67e22' },
      { time: 125, intensity: 94, label: 'Final Confrontation', color: '#c0392b' }
    ],
    revengeIntensity: 95,
    dominantColor: '#2c3e50',
    dna: { Adventure: 40, Drama: 35, Action: 25 },
    sensitiveScenes: []
  }
];

// Build object map by tmdbId
export const COMPLETE_REVENGE_DATABASE = Object.fromEntries(
  REVENGE_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_REVENGE_DATABASE;
