// utils/thrillerMovieData.js - ULTIMATE SUSPENSE THRILLER COLLECTION ✅ WITH DNA & SENSITIVE CONTENT

export const THRILLER_MOVIES = [
  {
    imdbID: 'tt0114369',
    tmdbId: 807,
    title: 'Se7en',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 1995,
    runtime: '127 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'],
    boxOffice: '$327.3 million',
    budget: '$33 million',
    synopsis: "Two detectives hunt a sadistic killer who uses the seven deadly sins as motives. Suffocating dread, rain-soaked nihilism, and one of cinema's most haunting finales.",
    poster: '/path/to/se7en-poster.jpg',
    backdrop: '/path/to/se7en-backdrop.jpg',
    backdrop_path: '/path/to/se7en-backdrop.jpg',
    poster_path: '/path/to/se7en-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Sin 1: Gluttony', color: '#b91c1c' },
      { time: 38, intensity: 65, label: 'Sin 3: Greed', color: '#f87171' },
      { time: 77, intensity: 85, label: 'Sin 5: Lust', color: '#fbbf24' },
      { time: 102, intensity: 92, label: 'Desert Confrontation', color: '#fde68a' },
      { time: 120, intensity: 98, label: "What's in the Box?", color: '#dc2626' }
    ],
    suspenseIntensity: 98,
    dominantColor: '#8b1e3f',
    dna: { Mystery: 50, Thriller: 40, Crime: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1392214',
    tmdbId: 146233,
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    genre: 'Crime, Drama, Mystery',
    year: 2013,
    runtime: '153 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'],
    boxOffice: '$122.1 million',
    budget: '$46 million',
    synopsis: "When his daughter goes missing, a desperate father takes justice into his own hands. Morality twisted beyond repair; every second feels like an ethical gut punch.",
    poster: '/path/to/prisoners-poster.jpg',
    backdrop: '/path/to/prisoners-backdrop.jpg',
    backdrop_path: '/path/to/prisoners-backdrop.jpg',
    poster_path: '/path/to/prisoners-poster.jpg',
    scenes: [
      { time: 20, intensity: 58, label: 'Abduction', color: '#a11515' },
      { time: 49, intensity: 75, label: 'First Search', color: '#f87171' },
      { time: 93, intensity: 82, label: 'Torture', color: '#fbbf24' },
      { time: 120, intensity: 90, label: 'Maze Hints', color: '#fde68a' },
      { time: 145, intensity: 96, label: 'Buried Alive', color: '#dc2626' }
    ],
    suspenseIntensity: 96,
    dominantColor: '#042258ff',
    dna: { Crime: 45, Thriller: 40, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0477348',
    tmdbId: 6977,
    title: 'No Country for Old Men',
    director: 'Coen Brothers',
    genre: 'Crime, Drama, Thriller',
    year: 2007,
    runtime: '122 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'],
    boxOffice: '$171.6 million',
    budget: '$25 million',
    synopsis: "Evil without emotion—silence, inevitability, and tension as philosophy. Violence erupts after a hunter stumbles upon a drug deal gone wrong.",
    poster: '/path/to/no-country-poster.jpg',
    backdrop: '/path/to/no-country-backdrop.jpg',
    backdrop_path: '/path/to/no-country-backdrop.jpg',
    poster_path: '/path/to/no-country-poster.jpg',
    scenes: [
      { time: 15, intensity: 60, label: 'Coin Toss', color: '#b91c1c' },
      { time: 41, intensity: 73, label: 'Motel Shootout', color: '#f87171' },
      { time: 68, intensity: 82, label: 'Desert Standoff', color: '#fbbf24' },
      { time: 92, intensity: 89, label: 'The Decision', color: '#fde68a' },
      { time: 115, intensity: 95, label: 'Inevitable Fate', color: '#dc2626' }
    ],
    suspenseIntensity: 95,
    dominantColor: '#865c07ff',
    dna: { Thriller: 50, Crime: 35, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0102926',
    tmdbId: 274,
    title: 'The Silence of the Lambs',
    director: 'Jonathan Demme',
    genre: 'Crime, Drama, Thriller',
    year: 1991,
    runtime: '118 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    boxOffice: '$272.7 million',
    budget: '$19 million',
    synopsis: "Terror comes not from screams but from intellect. Precision-built unease; a young FBI cadet seeks advice from imprisoned Hannibal Lecter.",
    poster: '/path/to/silence-poster.jpg',
    backdrop: '/path/to/silence-backdrop.jpg',
    backdrop_path: '/path/to/silence-backdrop.jpg',
    poster_path: '/path/to/silence-poster.jpg',
    scenes: [
      { time: 10, intensity: 35, label: 'First Interview', color: '#b91c1c' },
      { time: 46, intensity: 67, label: 'Lecter Escapes', color: '#f87171' },
      { time: 82, intensity: 79, label: 'Night Vision Stalk', color: '#fbbf24' },
      { time: 102, intensity: 89, label: 'Buffalo Bill', color: '#fde68a' },
      { time: 113, intensity: 94, label: 'Ending', color: '#dc2626' }
    ],
    suspenseIntensity: 94,
    dominantColor: '#72696e',
    dna: { Thriller: 55, Crime: 30, Horror: 15 },
    sensitiveScenes: [
      { start: "18:50", end: "18:57", description: "Explicit Scene" },
      { start: "1:36:30", end: "1:36:37", description: "Nudity (man)" }
    ]
  },
  {
    imdbID: 'tt0353969',
    tmdbId: 11423,
    title: 'Memories of Murder',
    director: 'Bong Joon Ho',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '132 min',
    ageRating: 'NR',
    rating: 8.1,
    cast: ['Song Kang-ho', 'Kim Sang-kyung', 'Kim Roi-ha'],
    boxOffice: '$20.1 million',
    budget: '$2 million',
    synopsis: "The agony of failure wrapped in procedural obsession; every clue a dead end. Based on Korea's first serial killer case.",
    poster: '/path/to/memories-poster.jpg',
    backdrop: '/path/to/memories-backdrop.jpg',
    backdrop_path: '/path/to/memories-backdrop.jpg',
    poster_path: '/path/to/memories-poster.jpg',
    scenes: [
      { time: 18, intensity: 39, label: 'First Crime Scene', color: '#b91c1c' },
      { time: 50, intensity: 59, label: 'Railroad Interrogation', color: '#f87171' },
      { time: 87, intensity: 70, label: 'Suspect Hunt', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'The Confrontation', color: '#fde68a' },
      { time: 128, intensity: 93, label: 'Haunting End', color: '#dc2626' }
    ],
    suspenseIntensity: 93,
    dominantColor: '#313a35',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "9:58", end: "10:10", description: "Sex" },
      { start: "54:34", end: "54:55", description: "Nudity (men)" },
      { start: "1:01:12", end: "1:02:40", description: "Masturbating (man)" },
      { start: "1:25:12", end: "1:25:47", description: "Partial nudity (woman)" }
    ]
  },
  {
    imdbID: 'tt0327056',
    tmdbId: 322,
    title: 'Mystic River',
    director: 'Clint Eastwood',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '138 min',
    ageRating: 'R',
    rating: 7.9,
    cast: ['Sean Penn', 'Tim Robbins', 'Kevin Bacon'],
    boxOffice: '$156.6 million',
    budget: '$30 million',
    synopsis: "Trauma, guilt, and revenge merge into an emotionally annihilating spiral. Three childhood friends reunite after a tragic event.",
    poster: '/path/to/mystic-poster.jpg',
    backdrop: '/path/to/mystic-backdrop.jpg',
    backdrop_path: '/path/to/mystic-backdrop.jpg',
    poster_path: '/path/to/mystic-poster.jpg',
    scenes: [
      { time: 12, intensity: 41, label: 'Abduction', color: '#b91c1c' },
      { time: 48, intensity: 60, label: 'Police Interrogation', color: '#f87171' },
      { time: 91, intensity: 72, label: 'Confession', color: '#fbbf24' },
      { time: 123, intensity: 84, label: 'Revelation', color: '#fde68a' },
      { time: 131, intensity: 91, label: 'Final Loss', color: '#dc2626' }
    ],
    suspenseIntensity: 91,
    dominantColor: '#152c48',
    dna: { Crime: 45, Drama: 40, Thriller: 15 },
    sensitiveScenes: [
      { start: "11:45", end: "12:16", description: "Kissing" },
      { start: "2:09:45", end: "2:10:16", description: "Passionate kissing" }
    ]
  },
  {
    imdbID: 'tt0407887',
    tmdbId: 1422,
    title: 'The Departed',
    director: 'Martin Scorsese',
    genre: 'Crime, Drama, Thriller',
    year: 2006,
    runtime: '151 min',
    ageRating: 'R',
    rating: 8.5,
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    boxOffice: '$291.5 million',
    budget: '$90 million',
    synopsis: "Suspicion and betrayal on every channel; violent, chaotic energy throughout. An undercover cop and a mole in the police attempt to identify each other.",
    poster: '/path/to/departed-poster.jpg',
    backdrop: '/path/to/departed-backdrop.jpg',
    backdrop_path: '/path/to/departed-backdrop.jpg',
    poster_path: '/path/to/departed-poster.jpg',
    scenes: [
      { time: 20, intensity: 55, label: 'Undercover Initiation', color: '#b91c1c' },
      { time: 60, intensity: 73, label: 'First Betrayal', color: '#f87171' },
      { time: 102, intensity: 78, label: 'Roof Scene', color: '#fbbf24' },
      { time: 137, intensity: 82, label: 'Shootout', color: '#fde68a' },
      { time: 149, intensity: 90, label: 'Finale', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#b84f3a',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "1:13:18", end: "1:13:22", description: "Kissing" },
      { start: "1:21:50", end: "1:22:20", description: "Passionate kissing + Undressing" },
      { start: "1:24:40", end: "1:24:47", description: "Implied Sexual Gesture" }
    ]
  },
  {
    imdbID: 'tt5362988',
    tmdbId: 395834,
    title: 'Wind River',
    director: 'Taylor Sheridan',
    genre: 'Crime, Drama, Mystery',
    year: 2017,
    runtime: '107 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Jeremy Renner', 'Elizabeth Olsen', 'Graham Greene'],
    boxOffice: '$45.2 million',
    budget: '$11 million',
    synopsis: "Still, cold, and merciless; grief weaponized by isolation. A wildlife officer teams with an FBI agent to solve a murder on a Native American reservation.",
    poster: '/path/to/windriver-poster.jpg',
    backdrop: '/path/to/windriver-backdrop.jpg',
    backdrop_path: '/path/to/windriver-backdrop.jpg',
    poster_path: '/path/to/windriver-poster.jpg',
    scenes: [
      { time: 9, intensity: 33, label: 'Body Found', color: '#b91c1c' },
      { time: 41, intensity: 58, label: 'FBI Arrival', color: '#f87171' },
      { time: 78, intensity: 74, label: 'Flashbacks', color: '#fbbf24' },
      { time: 90, intensity: 81, label: 'Cabin Showdown', color: '#fde68a' },
      { time: 104, intensity: 89, label: 'Closing', color: '#dc2626' }
    ],
    suspenseIntensity: 89,
    dominantColor: '#a6cef4',
    dna: { Crime: 45, Thriller: 40, Drama: 15 },
    sensitiveScenes: [
      { start: "1:12:05", end: "1:12:10", description: "Kissing" },
      { start: "1:17:50", end: "1:18:20", description: "Sex" }
    ]
  },
  {
    imdbID: 'tt2267998',
    tmdbId: 210577,
    title: 'Gone Girl',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 2014,
    runtime: '149 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
    boxOffice: '$369.3 million',
    budget: '$61 million',
    synopsis: "A media-age thriller of deceit and ego; elegance with a scalpel's edge. A husband becomes the prime suspect in his wife's disappearance.",
    poster: '/path/to/gonegirl-poster.jpg',
    backdrop: '/path/to/gonegirl-backdrop.jpg',
    backdrop_path: '/path/to/gonegirl-backdrop.jpg',
    poster_path: '/path/to/gonegirl-poster.jpg',
    scenes: [
      { time: 23, intensity: 45, label: 'Disappearance', color: '#b91c1c' },
      { time: 54, intensity: 67, label: 'Clue Hunt', color: '#f87171' },
      { time: 92, intensity: 76, label: 'Twist', color: '#fbbf24' },
      { time: 127, intensity: 84, label: 'Media Frenzy', color: '#fde68a' },
      { time: 145, intensity: 88, label: 'Revelation', color: '#dc2626' }
    ],
    suspenseIntensity: 88,
    dominantColor: '#e6c79c',
    dna: { Thriller: 50, Drama: 30, Mystery: 20 },
    sensitiveScenes: [
      { start: "6:41", end: "6:59", description: "Sex" },
      { start: "20:57", end: "21:04", description: "Sex" },
      { start: "43:20", end: "44:54", description: "Passionate kissing and partial nudity" },
      { start: "45:00", end: "45:10", description: "Sex" },
      { start: "2:00:10", end: "2:00:15", description: "Kissing" },
      { start: "2:03:50", end: "2:04:55", description: "Sex" },
      { start: "2:12:30", end: "2:13:45", description: "Nudity" }
    ]
  },
  {
    imdbID: 'tt0119174',
    tmdbId: 2649,
    title: 'The Game',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 1997,
    runtime: '129 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Michael Douglas', 'Sean Penn', 'Deborah Kara Unger'],
    boxOffice: '$109.4 million',
    budget: '$50 million',
    synopsis: "Reality folds in on itself — a perfect descent into confusion and control. A wealthy investment banker receives an invitation that spirals out of control.",
    poster: '/path/to/game-poster.jpg',
    backdrop: '/path/to/game-backdrop.jpg',
    backdrop_path: '/path/to/game-backdrop.jpg',
    poster_path: '/path/to/game-poster.jpg',
    scenes: [
      { time: 13, intensity: 29, label: 'Birthday Offer', color: '#b91c1c' },
      { time: 43, intensity: 52, label: 'First Twist', color: '#f87171' },
      { time: 62, intensity: 70, label: 'Trust Issues', color: '#fbbf24' },
      { time: 101, intensity: 79, label: 'Buried', color: '#fde68a' },
      { time: 120, intensity: 87, label: 'Ultimate Reveal', color: '#dc2626' }
    ],
    suspenseIntensity: 87,
    dominantColor: '#060f1e',
    dna: { Thriller: 55, Mystery: 30, Drama: 15 },
    sensitiveScenes: [
      { start: "52:32", end: "52:42", description: "Suggestive clothing (woman in bra)" }
    ]
  }
];

// Build object map by tmdbId
export const COMPLETE_THRILLER_DATABASE = Object.fromEntries(
  THRILLER_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_THRILLER_DATABASE;
