// utils/thrillerMovieData.js - ULTIMATE SUSPENSE THRILLER COLLECTION ✅ WITH DNA & SENSITIVE CONTENT

export const THRILLER_MOVIES = [
  {
    imdbID: 'tt0114369',
    tmdbId: 807,
    title: 'Se7en',
    director: 'David Fincher',
    genre: 'Crime, Drama, Mystery',
    year: 1995,
    runtime: '127 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'],
    boxOffice: '$327.3 million',
    budget: '$33 million',
    synopsis: "Two disparate detectives—a weary, retiring veteran and an intense, young newcomer—are dropped into a perpetually rain-soaked, morally rotting city to hunt a chillingly methodical serial killer. This killer uses the seven deadly sins as the disturbing inspiration for his gruesome, symbolic murders. It’s a relentless, psychological nightmare that challenges the limits of justice and human endurance, culminating in one of cinema’s most notorious and unforgettable twists.",
    poster: '/path/to/se7en-poster.jpg',
    backdrop: '/path/to/se7en-backdrop.jpg',
    backdrop_path: '/path/to/se7en-backdrop.jpg',
    poster_path: '/path/to/se7en-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Sin 1: Gluttony', color: '#b91c1c' },
      { time: 38, intensity: 65, label: 'Sin 3: Greed', color: '#f87171' },
      { time: 77, intensity: 85, label: 'Sin 5: Lust', color: '#fbbf24' },
      { time: 102, intensity: 92, label: 'Desert Confrontation', color: '#fde68a' },
      { time: 120, intensity: 98, label: "What's in the Box?", color: '#dc2626' }
    ],
    suspenseIntensity: 98,
    dominantColor: '#8b1e3f',
    dna: { Mystery: 50, Thriller: 40, Crime: 10 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt1392214',
    tmdbId: 146233,
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    genre: 'Crime, Drama, Mystery',
    year: 2013,
    runtime: '153 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'],
    boxOffice: '$122.1 million',
    budget: '$46 million',
    synopsis: "When his six-year-old daughter and her friend vanish on Thanksgiving, a desperate father (Hugh Jackman) refuses to wait for the police. Convinced that the strange, frightened man initially arrested holds the key, he makes the morally agonizing decision to take justice into his own violent hands. This deeply tense and complex thriller forces a detective (Jake Gyllenhaal) to race against the clock to find the truth before the desperate father crosses a point of no return.",
    poster: '/path/to/prisoners-poster.jpg',
    backdrop: '/path/to/prisoners-backdrop.jpg',
    backdrop_path: '/path/to/prisoners-backdrop.jpg',
    poster_path: '/path/to/prisoners-poster.jpg',
    scenes: [
      { time: 20, intensity: 58, label: 'Abduction', color: '#a11515' },
      { time: 49, intensity: 75, label: 'First Search', color: '#f87171' },
      { time: 93, intensity: 82, label: 'Torture', color: '#fbbf24' },
      { time: 120, intensity: 90, label: 'Maze Hints', color: '#fde68a' },
      { time: 145, intensity: 96, label: 'Buried Alive', color: '#dc2626' }
    ],
    suspenseIntensity: 96,
    dominantColor: '#042258ff',
    dna: { Crime: 45, Thriller: 40, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0477348',
    tmdbId: 6977,
    title: 'No Country for Old Men',
    director: 'Coen Brothers',
    genre: 'Crime, Drama, Thriller',
    year: 2007,
    runtime: '122 min',
    ageRating: 'R',
    rating: 8.2,
    cast: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'],
    boxOffice: '$171.6 million',
    budget: '$25 million',
    synopsis: "In the desolate landscape of 1980 Texas, a hunter stumbles upon a drug deal gone spectacularly wrong, walking away with a suitcase full of cash. This act sets loose Anton Chigurh (Javier Bardem), a chillingly detached and philosophical hitman who represents pure, relentless, random violence. This Oscar-winning masterpiece is a meditation on fate, aging, and the unstoppable nature of chaos, told with the Coen Brothers' stark, unforgettable cinematic language.",
    poster: '/path/to/no-country-poster.jpg',
    backdrop: '/path/to/no-country-backdrop.jpg',
    backdrop_path: '/path/to/no-country-backdrop.jpg',
    poster_path: '/path/to/no-country-poster.jpg',
    scenes: [
      { time: 15, intensity: 60, label: 'Coin Toss', color: '#b91c1c' },
      { time: 41, intensity: 73, label: 'Motel Shootout', color: '#f87171' },
      { time: 68, intensity: 82, label: 'Desert Standoff', color: '#fbbf24' },
      { time: 92, intensity: 89, label: 'The Decision', color: '#fde68a' },
      { time: 115, intensity: 95, label: 'Inevitable Fate', color: '#dc2626' }
    ],
    suspenseIntensity: 95,
    dominantColor: '#865c07ff',
    dna: { Thriller: 50, Crime: 35, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0102926',
    tmdbId: 274,
    title: 'The Silence of the Lambs',
    director: 'Jonathan Demme',
    genre: 'Crime, Drama, Thriller',
    year: 1991,
    runtime: '118 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    boxOffice: '$272.7 million',
    budget: '$19 million',
    synopsis: "A young, determined FBI trainee, Clarice Starling (Jodie Foster), is forced to seek the help of the brilliant, imprisoned psychopath and former psychiatrist, Dr. Hannibal Lecter (Anthony Hopkins). Her mission: to gain insight into the mind of a new, active serial killer named Buffalo Bill. This film is a definitive masterclass in suspense, featuring one of cinema's most famous and unsettling duels of intellect and will.",
    poster: '/path/to/silence-poster.jpg',
    backdrop: '/path/to/silence-backdrop.jpg',
    backdrop_path: '/path/to/silence-backdrop.jpg',
    poster_path: '/path/to/silence-poster.jpg',
    scenes: [
      { time: 10, intensity: 35, label: 'First Interview', color: '#b91c1c' },
      { time: 46, intensity: 67, label: 'Lecter Escapes', color: '#f87171' },
      { time: 82, intensity: 79, label: 'Night Vision Stalk', color: '#fbbf24' },
      { time: 102, intensity: 89, label: 'Buffalo Bill', color: '#fde68a' },
      { time: 113, intensity: 94, label: 'Ending', color: '#dc2626' }
    ],
    suspenseIntensity: 94,
    dominantColor: '#72696e',
    dna: { Thriller: 55, Crime: 30, Horror: 15 },
    sensitiveScenes: [
      { start: "18:50", end: "18:57", description: "Explicit Scene" },
      { start: "1:36:30", end: "1:36:37", description: "Nudity (man)" }
    ]
  },
  {
    imdbID: 'tt0353969',
    tmdbId: 11423,
    title: 'Memories of Murder',
    director: 'Bong Joon Ho',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '132 min',
    ageRating: 'NR',
    rating: 8.1,
    cast: ['Song Kang-ho', 'Kim Sang-kyung', 'Kim Roi-ha'],
    boxOffice: '$20.1 million',
    budget: '$2 million',
    synopsis: "Set in 1980s South Korea, this slow-burning, dark-humored procedural follows two local detectives with vastly different approaches to investigation—one brutal and instinctual, the other sharp and clinical—as they chase the country's first confirmed serial killer. Against a politically unstable backdrop, the film masterfully captures the frustration, futility, and eventual psychic toll of hunting a ghost in a system ill-equipped to find him.",
    poster: '/path/to/memories-poster.jpg',
    backdrop: '/path/to/memories-backdrop.jpg',
    backdrop_path: '/path/to/memories-backdrop.jpg',
    poster_path: '/path/to/memories-poster.jpg',
    scenes: [
      { time: 18, intensity: 39, label: 'First Crime Scene', color: '#b91c1c' },
      { time: 50, intensity: 59, label: 'Railroad Interrogation', color: '#f87171' },
      { time: 87, intensity: 70, label: 'Suspect Hunt', color: '#fbbf24' },
      { time: 110, intensity: 85, label: 'The Confrontation', color: '#fde68a' },
      { time: 128, intensity: 93, label: 'Haunting End', color: '#dc2626' }
    ],
    suspenseIntensity: 93,
    dominantColor: '#313a35',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "9:58", end: "10:10", description: "Sex" },
      { start: "54:34", end: "54:55", description: "Nudity (men)" },
      { start: "1:01:12", end: "1:02:40", description: "Masturbating (man)" },
      { start: "1:25:12", end: "1:25:47", description: "Partial nudity (woman)" }
    ]
  },
  {
    imdbID: 'tt0327056',
    tmdbId: 322,
    title: 'Mystic River',
    director: 'Clint Eastwood',
    genre: 'Crime, Drama, Mystery',
    year: 2003,
    runtime: '138 min',
    ageRating: 'R',
    rating: 7.9,
    cast: ['Sean Penn', 'Tim Robbins', 'Kevin Bacon'],
    boxOffice: '$156.6 million',
    budget: '$30 million',
    synopsis: "The murder of a daughter reunites three childhood friends—a victim, a detective, and a suspect—leading to a dark, complex investigation saturated with long-held secrets, suspicion, and deep-seated guilt. This intense psychological drama explores how the indelible trauma of a shared past event can catastrophically intersect with a modern tragedy, ultimately questioning the nature of moral consequence and the true meaning of justice.",
    poster: '/path/to/mystic-poster.jpg',
    backdrop: '/path/to/mystic-backdrop.jpg',
    backdrop_path: '/path/to/mystic-backdrop.jpg',
    poster_path: '/path/to/mystic-poster.jpg',
    scenes: [
      { time: 12, intensity: 41, label: 'Abduction', color: '#b91c1c' },
      { time: 48, intensity: 60, label: 'Police Interrogation', color: '#f87171' },
      { time: 91, intensity: 72, label: 'Confession', color: '#fbbf24' },
      { time: 123, intensity: 84, label: 'Revelation', color: '#fde68a' },
      { time: 131, intensity: 91, label: 'Final Loss', color: '#dc2626' }
    ],
    suspenseIntensity: 91,
    dominantColor: '#152c48',
    dna: { Crime: 45, Drama: 40, Thriller: 15 },
    sensitiveScenes: [
      { start: "11:45", end: "12:16", description: "Kissing" },
      { start: "2:09:45", end: "2:10:16", description: "Passionate kissing" }
    ]
  },
  {
    imdbID: 'tt0407887',
    tmdbId: 1422,
    title: 'The Departed',
    director: 'Martin Scorsese',
    genre: 'Crime, Drama, Thriller',
    year: 2006,
    runtime: '151 min',
    ageRating: 'R',
    rating: 8.5,
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    boxOffice: '$291.5 million',
    budget: '$90 million',
    synopsis: "In Boston, the police department plants a young undercover cop (Leonardo DiCaprio) deep within the inner circle of a ruthless Irish mob boss (Jack Nicholson). Simultaneously, the mob boss plants his own loyal mole (Matt Damon) high inside the state police force. This high-octane, violent saga of betrayal and corruption becomes a relentless, heart-pounding race as both men desperately try to expose and eliminate the other before their own identity is revealed.",
    poster: '/path/to/departed-poster.jpg',
    backdrop: '/path/to/departed-backdrop.jpg',
    backdrop_path: '/path/to/departed-backdrop.jpg',
    poster_path: '/path/to/departed-poster.jpg',
    scenes: [
      { time: 20, intensity: 55, label: 'Undercover Initiation', color: '#b91c1c' },
      { time: 60, intensity: 73, label: 'First Betrayal', color: '#f87171' },
      { time: 102, intensity: 78, label: 'Roof Scene', color: '#fbbf24' },
      { time: 137, intensity: 82, label: 'Shootout', color: '#fde68a' },
      { time: 149, intensity: 90, label: 'Finale', color: '#dc2626' }
    ],
    suspenseIntensity: 90,
    dominantColor: '#b84f3a',
    dna: { Crime: 50, Thriller: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "1:13:18", end: "1:13:22", description: "Kissing" },
      { start: "1:21:50", end: "1:22:20", description: "Passionate kissing + Undressing" },
      { start: "1:24:40", end: "1:24:47", description: "Implied Sexual Gesture" }
    ]
  },
  {
    imdbID: 'tt5362988',
    tmdbId: 395834,
    title: 'Wind River',
    director: 'Taylor Sheridan',
    genre: 'Crime, Drama, Mystery',
    year: 2017,
    runtime: '107 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Jeremy Renner', 'Elizabeth Olsen', 'Graham Greene'],
    boxOffice: '$45.2 million',
    budget: '$11 million',
    synopsis: "A U.S. Fish and Wildlife service agent (Jeremy Renner), deeply connected to the local Native American community, discovers the body of a young woman on the isolated, snow-covered Wind River Reservation. He teams up with a rookie FBI agent (Elizabeth Olsen) to solve the murder. This film is a stark, beautifully bleak, and emotionally devastating mystery that shines a necessary light on systemic violence and justice for the forgotten.",
    poster: '/path/to/windriver-poster.jpg',
    backdrop: '/path/to/windriver-backdrop.jpg',
    backdrop_path: '/path/to/windriver-backdrop.jpg',
    poster_path: '/path/to/windriver-poster.jpg',
    scenes: [
      { time: 9, intensity: 33, label: 'Body Found', color: '#b91c1c' },
      { time: 41, intensity: 58, label: 'FBI Arrival', color: '#f87171' },
      { time: 78, intensity: 74, label: 'Flashbacks', color: '#fbbf24' },
      { time: 90, intensity: 81, label: 'Cabin Showdown', color: '#fde68a' },
      { time: 104, intensity: 89, label: 'Closing', color: '#dc2626' }
    ],
    suspenseIntensity: 89,
    dominantColor: '#a6cef4',
    dna: { Crime: 45, Thriller: 40, Drama: 15 },
    sensitiveScenes: [
      { start: "1:12:05", end: "1:12:10", description: "Kissing" },
      { start: "1:17:50", end: "1:18:20", description: "Sex" }
    ]
  },
  {
    imdbID: 'tt2267998',
    tmdbId: 210577,
    title: 'Gone Girl',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 2014,
    runtime: '149 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
    boxOffice: '$369.3 million',
    budget: '$61 million',
    synopsis: "On the morning of his fifth wedding anniversary, Nick Dunne (Ben Affleck) finds his beautiful, brilliant wife, Amy, missing, with signs of a struggle. Under intense media scrutiny and relentless police questioning, Nick's shifty behavior and mounting lies lead everyone to ask the chilling question: Did he murder his wife? This dark, brilliant Fincher mystery is a twisted, cynical examination of marriage and media manipulation that keeps the audience guessing with shocking, unpredictable revelations.",
    poster: '/path/to/gonegirl-poster.jpg',
    backdrop: '/path/to/gonegirl-backdrop.jpg',
    backdrop_path: '/path/to/gonegirl-backdrop.jpg',
    poster_path: '/path/to/gonegirl-poster.jpg',
    scenes: [
      { time: 23, intensity: 45, label: 'Disappearance', color: '#b91c1c' },
      { time: 54, intensity: 67, label: 'Clue Hunt', color: '#f87171' },
      { time: 92, intensity: 76, label: 'Twist', color: '#fbbf24' },
      { time: 127, intensity: 84, label: 'Media Frenzy', color: '#fde68a' },
      { time: 145, intensity: 88, label: 'Revelation', color: '#dc2626' }
    ],
    suspenseIntensity: 88,
    dominantColor: '#e6c79c',
    dna: { Thriller: 50, Drama: 30, Mystery: 20 },
    sensitiveScenes: [
      { start: "6:41", end: "6:59", description: "Sex" },
      { start: "20:57", end: "21:04", description: "Sex" },
      { start: "43:20", end: "44:54", description: "Passionate kissing and partial nudity" },
      { start: "45:00", end: "45:10", description: "Sex" },
      { start: "2:00:10", end: "2:00:15", description: "Kissing" },
      { start: "2:03:50", end: "2:04:55", description: "Sex" },
      { start: "2:12:30", end: "2:13:45", description: "Nudity" }
    ]
  },
  {
    imdbID: 'tt0119174',
    tmdbId: 2649,
    title: 'The Game',
    director: 'David Fincher',
    genre: 'Drama, Mystery, Thriller',
    year: 1997,
    runtime: '129 min',
    ageRating: 'R',
    rating: 7.7,
    cast: ['Michael Douglas', 'Sean Penn', 'Deborah Kara Unger'],
    boxOffice: '$109.4 million',
    budget: '$50 million',
    synopsis: "Nicholas Van Orton (Michael Douglas), a cold, immensely wealthy investment banker, receives a strange birthday gift from his estranged brother: participation in a mysterious, real-life \"Game.\" As the line between the scripted game and his actual life begins to dangerously dissolve, Nicholas is plunged into a terrifying, paranoia-soaked world where he loses control of everything. This is a spectacular, mind-bending thriller that constantly shifts the stakes until the surprising final moment.",
    poster: '/path/to/game-poster.jpg',
    backdrop: '/path/to/game-backdrop.jpg',
    backdrop_path: '/path/to/game-backdrop.jpg',
    poster_path: '/path/to/game-poster.jpg',
    scenes: [
      { time: 13, intensity: 29, label: 'Birthday Offer', color: '#b91c1c' },
      { time: 43, intensity: 52, label: 'First Twist', color: '#f87171' },
      { time: 62, intensity: 70, label: 'Trust Issues', color: '#fbbf24' },
      { time: 101, intensity: 79, label: 'Buried', color: '#fde68a' },
      { time: 120, intensity: 87, label: 'Ultimate Reveal', color: '#dc2626' }
    ],
    suspenseIntensity: 87,
    dominantColor: '#060f1e',
    dna: { Thriller: 55, Mystery: 30, Drama: 15 },
    sensitiveScenes: [
      { start: "52:32", end: "52:42", description: "Suggestive clothing (woman in bra)" }
    ]
  }
];

// Build object map by tmdbId
export const COMPLETE_THRILLER_DATABASE = Object.fromEntries(
  THRILLER_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_THRILLER_DATABASE;
