// utils/timeTravelMovieData.js - TIME TRAVEL COLLECTION WITH SENSITIVE SCENES ✅

export const TIME_TRAVEL_MOVIES = [
  {
    imdbID: 'tt0088763',
    tmdbId: 105,
    title: 'Back to the Future',
    director: 'Robert Zemeckis',
    genre: 'Adventure, Comedy, Sci-Fi',
    year: 1985,
    runtime: '116 min',
    ageRating: 'PG',
    rating: 8.5,
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    boxOffice: '$388.8 million',
    budget: '$19 million',
    synopsis: "Marty McFly is just a typical teenager trying to play guitar and survive high school, until he is accidentally blasted 30 years into the past in a plutonium-powered DeLorean. Trapped in 1955, he inadvertently prevents his parents from meeting, setting off a chain reaction that begins to erase him from existence. Now, with the help of a younger, eccentric Doc Brown, Marty must play matchmaker to his own parents to save his future—before he fades away completely.",
    poster: '/path/to/bttf-poster.jpg',
    backdrop: '/path/to/bttf-backdrop.jpg',
    backdrop_path: '/path/to/bttf-backdrop.jpg',
    poster_path: '/path/to/bttf-poster.jpg',
    scenes: [
      { time: 18, intensity: 40, label: 'Time Machine Reveal', color: '#3b82f6' },
      { time: 33, intensity: 65, label: '1955 Arrival', color: '#60a5fa' },
      { time: 68, intensity: 75, label: 'Enchantment Dance', color: '#93c5fd' },
      { time: 95, intensity: 88, label: 'Clock Tower', color: '#bfdbfe' },
      { time: 110, intensity: 92, label: 'Return to 1985', color: '#dbeafe' }
    ],
    timeTravelIntensity: 92,
    complexityLevel: 'MEDIUM',
    dominantColor: '#f59e0b',
    dna: { Adventure: 50, Comedy: 30, SciFi: 20 },
    sensitiveScenes: [
      { start: '1:19:30', end: '1:19:40', description: 'Kissing' },
      { start: '1:21:49', end: '1:22:13', description: 'Sexual harassment' },
      { start: '1:26:08', end: '1:26:12', description: 'Kissing' }
    ]
  },
  {
    imdbID: 'tt0103064',
    tmdbId: 280,
    title: 'Terminator 2: Judgment Day',
    director: 'James Cameron',
    genre: 'Action, Sci-Fi, Thriller',
    year: 1991,
    runtime: '137 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong'],
    boxOffice: '$520.9 million',
    budget: '$102 million',
    synopsis: "Ten years have passed since the first machine failed to kill Sarah Connor. Now, the future supercomputer Skynet sends a new, terrifyingly advanced liquid-metal Terminator back in time to eliminate her son, John, the future leader of the human resistance. But the resistance has sent back a protector of their own—a reprogrammed version of the very machine that once tried to kill Sarah. It is a race against an unkillable enemy to change the future.",
    poster: '/path/to/t2-poster.jpg',
    backdrop: '/path/to/t2-backdrop.jpg',
    backdrop_path: '/path/to/t2-backdrop.jpg',
    poster_path: '/path/to/t2-poster.jpg',
    scenes: [
      { time: 15, intensity: 50, label: 'T-1000 Arrival', color: '#dc2626' },
      { time: 42, intensity: 72, label: 'Hospital Escape', color: '#ef4444' },
      { time: 78, intensity: 85, label: 'Cyberdyne Systems', color: '#f87171' },
      { time: 110, intensity: 92, label: 'Steel Mill', color: '#fca5a5' },
      { time: 130, intensity: 96, label: 'Final Sacrifice', color: '#fecaca' }
    ],
    timeTravelIntensity: 96,
    complexityLevel: 'HIGH',
    dominantColor: '#1e3a8a',
    dna: { Action: 50, SciFi: 35, Thriller: 15 },
    sensitiveScenes: [
      { start: '6:10', end: '6:20', description: 'Partial Nudity (male, not sexual)' },
      { start: '11:40', end: '11:52', description: 'Partial Nudity (male, not sexual)' }
    ]
  },
  {
    imdbID: 'tt0088247',
    tmdbId: 218,
    title: 'The Terminator',
    director: 'James Cameron',
    genre: 'Action, Sci-Fi, Thriller',
    year: 1984,
    runtime: '107 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Michael Biehn'],
    boxOffice: '$78.4 million',
    budget: '$6.4 million',
    synopsis: "In the ashes of a nuclear future, machines rule the world. To crush the final human resistance, they send an unstoppable cyborg assassin back to 1984 to kill Sarah Connor, the unsuspecting waitress destined to birth humanity's savior. Her only hope lies with Kyle Reese, a lone soldier sent from the future to protect her. A relentless, gritty sci-fi horror where love is born in the shadow of the apocalypse.",
    poster: '/path/to/terminator-poster.jpg',
    backdrop: '/path/to/terminator-backdrop.jpg',
    backdrop_path: '/path/to/terminator-backdrop.jpg',
    poster_path: '/path/to/terminator-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Arrival', color: '#7c2d12' },
      { time: 28, intensity: 68, label: 'Tech Noir', color: '#9a3412' },
      { time: 58, intensity: 78, label: 'Police Station', color: '#c2410c' },
      { time: 82, intensity: 88, label: 'Chase', color: '#ea580c' },
      { time: 101, intensity: 94, label: 'Factory Showdown', color: '#f97316' }
    ],
    timeTravelIntensity: 94,
    complexityLevel: 'HIGH',
    dominantColor: '#ef4444',
    dna: { Action: 45, SciFi: 40, Thriller: 15 },
    sensitiveScenes: [
      { start: '5:00', end: '7:30', description: 'Nudity (man)' },
      { start: '1:21:50', end: '1:23:00', description: 'Passionate kissing + sex' }
    ]
  },
  {
    imdbID: 'tt0816692',
    tmdbId: 157336,
    title: 'Interstellar',
    director: 'Christopher Nolan',
    genre: 'Adventure, Drama, Sci-Fi',
    year: 2014,
    runtime: '169 min',
    ageRating: 'PG-13',
    rating: 8.7,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    boxOffice: '$677.5 million',
    budget: '$165 million',
    synopsis: "With Earth plagued by blight and humanity facing extinction, ex-pilot Cooper is recruited for a desperate mission: to travel through a wormhole in search of a new habitable planet. But the mission comes with a devastating cost—relativity means that for every hour he spends in space, years pass for his children back on Earth. It is a visually spectacular, emotional epic about a father's love stretching across dimensions and time.",
    poster: '/path/to/interstellar-poster.jpg',
    backdrop: '/path/to/interstellar-backdrop.jpg',
    backdrop_path: '/path/to/interstellar-backdrop.jpg',
    poster_path: '/path/to/interstellar-poster.jpg',
    scenes: [
      { time: 45, intensity: 50, label: 'Launch', color: '#0891b2' },
      { time: 82, intensity: 68, label: 'Miller Planet', color: '#06b6d4' },
      { time: 118, intensity: 82, label: 'Mann Planet', color: '#22d3ee' },
      { time: 145, intensity: 90, label: 'Tesseract', color: '#67e8f9' },
      { time: 162, intensity: 95, label: 'Reunion', color: '#a5f3fc' }
    ],
    timeTravelIntensity: 95,
    complexityLevel: 'EXTREME',
    dominantColor: '#0c4a6e',
    dna: { SciFi: 50, Drama: 30, Adventure: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt2397535',
    tmdbId: 206487,
    title: 'Predestination',
    director: 'The Spierig Brothers',
    genre: 'Drama, Mystery, Sci-Fi',
    year: 2014,
    runtime: '97 min',
    ageRating: 'R',
    rating: 7.4,
    cast: ['Ethan Hawke', 'Sarah Snook', 'Noah Taylor'],
    boxOffice: '$5.6 million',
    budget: '$5 million',
    synopsis: "A temporal agent on his final assignment travels through time to catch the one criminal who has always eluded him: the 'Fizzle Bomber.' He poses as a bartender and listens to the tragic, unbelievable life story of a patron. As their narratives intertwine, the film spirals into a dizzying, paradox-laden masterpiece where the snake eats its own tail, and identity is the ultimate mystery.",
    poster: '/path/to/predestination-poster.jpg',
    backdrop: '/path/to/predestination-backdrop.jpg',
    backdrop_path: '/path/to/predestination-backdrop.jpg',
    poster_path: '/path/to/predestination-poster.jpg',
    scenes: [
      { time: 12, intensity: 35, label: 'Bar Meeting', color: '#854d0e' },
      { time: 38, intensity: 62, label: 'Backstory Revealed', color: '#a16207' },
      { time: 68, intensity: 78, label: 'Time Jump', color: '#ca8a04' },
      { time: 82, intensity: 88, label: 'Identity Revelation', color: '#eab308' },
      { time: 92, intensity: 97, label: 'Paradox Complete', color: '#fde047' }
    ],
    timeTravelIntensity: 97,
    complexityLevel: 'EXTREME',
    dominantColor: '#78350f',
    dna: { SciFi: 50, Mystery: 35, Drama: 15 },
    sensitiveScenes: [
      { start: '19:07', end: '19:20', description: 'Sex + Partial Nudity' },
      { start: '42:20', end: '42:50', description: 'Nudity' },
      { start: '1:12:50', end: '1:12:58', description: 'Kissing' }
    ]
  },
  {
    imdbID: 'tt0390384',
    tmdbId: 14337,
    title: 'Primer',
    director: 'Shane Carruth',
    genre: 'Drama, Sci-Fi, Thriller',
    year: 2004,
    runtime: '77 min',
    ageRating: 'PG-13',
    rating: 6.7,
    cast: ['Shane Carruth', 'David Sullivan', 'Casey Gooden'],
    boxOffice: '$841,926',
    budget: '$7,000',
    synopsis: "In a suburban garage, two engineers accidentally discover a side-effect of their error-checking device: it's a time machine. There are no special effects here, only the terrifying realism of what would actually happen if ordinary men discovered god-like power. As they exploit the timeline for stock market gains, their friendship fractures under the weight of paranoia, double-crosses, and the physical toll of rewriting reality.",
    poster: '/path/to/primer-poster.jpg',
    backdrop: '/path/to/primer-backdrop.jpg',
    backdrop_path: '/path/to/primer-backdrop.jpg',
    poster_path: '/path/to/primer-poster.jpg',
    scenes: [
      { time: 15, intensity: 28, label: 'Discovery', color: '#475569' },
      { time: 32, intensity: 52, label: 'First Use', color: '#64748b' },
      { time: 48, intensity: 68, label: 'Overlaps Begin', color: '#94a3b8' },
      { time: 62, intensity: 82, label: 'Paradox Layers', color: '#cbd5e1' },
      { time: 73, intensity: 98, label: 'Timeline Collapse', color: '#e2e8f0' }
    ],
    timeTravelIntensity: 98,
    complexityLevel: 'EXTREME',
    dominantColor: '#94a3b8',
    dna: { SciFi: 60, Thriller: 25, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0114746',
    tmdbId: 63,
    title: '12 Monkeys',
    director: 'Terry Gilliam',
    genre: 'Mystery, Sci-Fi, Thriller',
    year: 1995,
    runtime: '129 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Bruce Willis', 'Madeleine Stowe', 'Brad Pitt'],
    boxOffice: '$168.8 million',
    budget: '$29.5 million',
    synopsis: "By 2035, humanity is forced to live underground after a deadly virus wipes out the population. James Cole, a convict, is volunteered to travel back to the 1990s to locate the virus's source: the Army of the Twelve Monkeys. But Cole is haunted by a recurring dream from his childhood and begins to question his own sanity. Is he a savior from the future, or just a madman lost in time?",
    poster: '/path/to/12monkeys-poster.jpg',
    backdrop: '/path/to/12monkeys-backdrop.jpg',
    backdrop_path: '/path/to/12monkeys-backdrop.jpg',
    poster_path: '/path/to/12monkeys-poster.jpg',
    scenes: [
      { time: 18, intensity: 42, label: 'First Jump', color: '#065f46' },
      { time: 52, intensity: 63, label: 'Psychiatrist', color: '#047857' },
      { time: 85, intensity: 74, label: 'Army of 12', color: '#059669' },
      { time: 108, intensity: 86, label: 'Airport', color: '#10b981' },
      { time: 124, intensity: 93, label: 'Circle Closes', color: '#34d399' }
    ],
    timeTravelIntensity: 93,
    complexityLevel: 'HIGH',
    dominantColor: '#dc2626',
    dna: { SciFi: 45, Thriller: 35, Mystery: 20 },
    sensitiveScenes: [
      { start: '16:00', end: '16:10', description: 'Partial Nudity (Man\'s butt)' },
      { start: '1:54:08', end: '1:54:12', description: 'Kissing' }
    ]
  },
  {
    imdbID: 'tt0246578',
    tmdbId: 141,
    title: 'Donnie Darko',
    director: 'Richard Kelly',
    genre: 'Drama, Mystery, Sci-Fi',
    year: 2001,
    runtime: '113 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Jake Gyllenhaal', 'Jena Malone', 'Mary McDonnell'],
    boxOffice: '$7.6 million',
    budget: '$4.5 million',
    synopsis: "Donnie Darko is a troubled teenager who narrowly escapes death when a jet engine crashes into his bedroom. He begins seeing a demonic rabbit named Frank, who tells him the world will end in 28 days. As Donnie is manipulated into committing crimes by this figure, he discovers he may be living in a Tangent Universe that is collapsing in on itself. A haunting, surreal cult classic about destiny, sacrifice, and time travel.",
    poster: '/path/to/donniedarko-poster.jpg',
    backdrop: '/path/to/donniedarko-backdrop.jpg',
    backdrop_path: '/path/to/donniedarko-backdrop.jpg',
    poster_path: '/path/to/donniedarko-poster.jpg',
    scenes: [
      { time: 8, intensity: 38, label: 'Frank Appears', color: '#581c87' },
      { time: 35, intensity: 58, label: 'Philosophy Class', color: '#6b21a8' },
      { time: 68, intensity: 72, label: 'Cellar Door', color: '#7c3aed' },
      { time: 92, intensity: 84, label: 'Halloween Party', color: '#8b5cf6' },
      { time: 108, intensity: 91, label: 'Sacrifice', color: '#a78bfa' }
    ],
    timeTravelIntensity: 91,
    complexityLevel: 'HIGH',
    dominantColor: '#312e81',
    dna: { Drama: 45, SciFi: 35, Mystery: 20 },
    sensitiveScenes: [
      { start: '1:18:18', end: '1:18:35', description: 'Kissing' },
      { start: '1:27:18', end: '1:27:26', description: 'Kissing' },
      { start: '1:48:10', end: '1:48:39', description: 'Passionate kissing' }
    ]
  },
  {
    imdbID: 'tt0107048',
    tmdbId: 137,
    title: 'Groundhog Day',
    director: 'Harold Ramis',
    genre: 'Comedy, Drama, Fantasy',
    year: 1993,
    runtime: '101 min',
    ageRating: 'PG',
    rating: 8.0,
    cast: ['Bill Murray', 'Andie MacDowell', 'Chris Elliott'],
    boxOffice: '$105 million',
    budget: '$14.6 million',
    synopsis: "Phil Connors is an arrogant, cynical weatherman sent to cover the Groundhog Day festivities in Punxsutawney. But when he wakes up the next morning, it's Groundhog Day again. And again. And again. Trapped in a time loop with no consequences and no escape, Phil moves from hedonism to despair to eventual self-discovery. It is the gold standard of time loop films—funny, philosophical, and deeply redeeming.",
    poster: '/path/to/groundhog-poster.jpg',
    backdrop: '/path/to/groundhog-backdrop.jpg',
    backdrop_path: '/path/to/groundhog-backdrop.jpg',
    poster_path: '/path/to/groundhog-poster.jpg',
    scenes: [
      { time: 12, intensity: 30, label: 'First Loop', color: '#be123c' },
      { time: 38, intensity: 52, label: 'Realization', color: '#e11d48' },
      { time: 58, intensity: 66, label: 'Experimentation', color: '#f43f5e' },
      { time: 78, intensity: 78, label: 'Self-Improvement', color: '#fb7185' },
      { time: 96, intensity: 89, label: 'True Love', color: '#fda4af' }
    ],
    timeTravelIntensity: 89,
    complexityLevel: 'MEDIUM',
    dominantColor: '#0ea5e9',
    dna: { Comedy: 50, Drama: 30, Fantasy: 20 },
    sensitiveScenes: [
      { start: '55:00', end: '56:00', description: 'Kissing' },
      { start: '1:25:00', end: '1:26:16', description: 'Kissing' },
      { start: '1:40:00', end: '1:40:21', description: 'Kissing' }
    ]
  },
  {
    imdbID: 'tt0480669',
    tmdbId: 14139,
    title: 'Timecrimes',
    director: 'Nacho Vigalondo',
    genre: 'Mystery, Sci-Fi, Thriller',
    year: 2007,
    runtime: '92 min',
    ageRating: 'R',
    rating: 7.1,
    cast: ['Karra Elejalde', 'Candela Fernández', 'Bárbara Goenaga'],
    boxOffice: '$574,188',
    budget: '$2.6 million',
    synopsis: "A man relaxing in his garden spots a mysterious woman in the woods and is suddenly attacked by a figure with a pink bandage wrapped around his face. Fleeing to a nearby facility, he stumbles into a scientific experiment and is sent back in time by one hour. What follows is a tightly wound, terrifying puzzle where he becomes the architect of his own nightmare, desperately trying to fix the past only to make it worse.",
    poster: '/path/to/timecrimes-poster.jpg',
    backdrop: '/path/to/timecrimes-backdrop.jpg',
    backdrop_path: '/path/to/timecrimes-backdrop.jpg',
    poster_path: '/path/to/timecrimes-poster.jpg',
    scenes: [
      { time: 8, intensity: 35, label: 'Binoculars', color: '#15803d' },
      { time: 24, intensity: 58, label: 'Machine', color: '#16a34a' },
      { time: 48, intensity: 72, label: 'Second Loop', color: '#22c55e' },
      { time: 68, intensity: 82, label: 'Realization', color: '#4ade80' },
      { time: 86, intensity: 90, label: 'Inevitable End', color: '#86efac' }
    ],
    timeTravelIntensity: 90,
    complexityLevel: 'HIGH',
    dominantColor: '#be185d',
    dna: { Thriller: 50, SciFi: 35, Mystery: 15 },
    sensitiveScenes: [
      { start: '5:05', end: '5:20', description: 'Kissing' },
      { start: '7:07', end: '7:14', description: 'Partial nudity (woman)' },
      { start: '10:20', end: '11:34', description: 'Nudity (woman)' },
      { start: '46:15', end: '47:10', description: 'Suggestive Clothing (woman in underwear)' },
      { start: '49:15', end: '49:50', description: 'Nudity (woman)' }
    ]
  }
];

// Build object map by tmdbId
export const COMPLETE_TIME_TRAVEL_DATABASE = Object.fromEntries(
  TIME_TRAVEL_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_TIME_TRAVEL_DATABASE;
