// utils/timeTravelMovieData.js - ULTIMATE TIME TRAVEL COLLECTION ✅

export const TIME_TRAVEL_MOVIES = [
  {
    imdbID: 'tt0088763',
    tmdbId: 105,
    title: 'Back to the Future',
    director: 'Robert Zemeckis',
    genre: 'Adventure, Comedy, Sci-Fi',
    year: 1985,
    runtime: '116 min',
    ageRating: 'PG',
    rating: 8.5,
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    boxOffice: '$388.8 million',
    budget: '$19 million',
    synopsis: "Marty McFly, a typical American teenager, is accidentally sent back to 1955 in a time-traveling DeLorean invented by his eccentric scientist friend, Doc Brown. While there, he must ensure his teenage parents fall in love—or risk erasing his own existence. The quintessential time travel adventure that perfectly blends humor, heart, and iconic sci-fi storytelling.",
    poster: '/path/to/bttf-poster.jpg',
    backdrop: '/path/to/bttf-backdrop.jpg',
    backdrop_path: '/path/to/bttf-backdrop.jpg',
    poster_path: '/path/to/bttf-poster.jpg',
    scenes: [
      { time: 18, intensity: 40, label: 'Time Machine Reveal', color: '#3b82f6' },
      { time: 33, intensity: 65, label: '1955 Arrival', color: '#60a5fa' },
      { time: 68, intensity: 75, label: 'Enchantment Dance', color: '#93c5fd' },
      { time: 95, intensity: 88, label: 'Clock Tower', color: '#bfdbfe' },
      { time: 110, intensity: 92, label: 'Return to 1985', color: '#dbeafe' }
    ],
    timeTravelIntensity: 92,
    complexityLevel: 'MEDIUM',
    dominantColor: '#3b82f6',
    dna: { Adventure: 50, Comedy: 30, SciFi: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0103064',
    tmdbId: 280,
    title: 'Terminator 2: Judgment Day',
    director: 'James Cameron',
    genre: 'Action, Sci-Fi, Thriller',
    year: 1991,
    runtime: '137 min',
    ageRating: 'R',
    rating: 8.6,
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong'],
    boxOffice: '$520.9 million',
    budget: '$102 million',
    synopsis: "A cyborg (Schwarzenegger) is sent back in time to protect young John Connor—the future leader of the human resistance—from a more advanced liquid-metal Terminator. Epic action sequences meet emotionally resonant storytelling in this groundbreaking sequel that redefined sci-fi cinema and time travel stakes.",
    poster: '/path/to/t2-poster.jpg',
    backdrop: '/path/to/t2-backdrop.jpg',
    backdrop_path: '/path/to/t2-backdrop.jpg',
    poster_path: '/path/to/t2-poster.jpg',
    scenes: [
      { time: 15, intensity: 50, label: 'T-1000 Arrival', color: '#dc2626' },
      { time: 42, intensity: 72, label: 'Hospital Escape', color: '#ef4444' },
      { time: 78, intensity: 85, label: 'Cyberdyne Systems', color: '#f87171' },
      { time: 110, intensity: 92, label: 'Steel Mill', color: '#fca5a5' },
      { time: 130, intensity: 96, label: 'Final Sacrifice', color: '#fecaca' }
    ],
    timeTravelIntensity: 96,
    complexityLevel: 'HIGH',
    dominantColor: '#dc2626',
    dna: { Action: 50, SciFi: 35, Thriller: 15 },
    sensitiveScenes: [
      { start: "1:32:45", end: "1:33:10", description: "Partial nudity (man)" }
    ]
  },
  {
    imdbID: 'tt0088247',
    tmdbId: 218,
    title: 'The Terminator',
    director: 'James Cameron',
    genre: 'Action, Sci-Fi, Thriller',
    year: 1984,
    runtime: '107 min',
    ageRating: 'R',
    rating: 8.1,
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Michael Biehn'],
    boxOffice: '$78.4 million',
    budget: '$6.4 million',
    synopsis: "A relentless cyborg assassin is sent from 2029 to 1984 to kill Sarah Connor, whose unborn son will one day lead humanity's resistance against machines. A soldier from the future follows to protect her. Groundbreaking sci-fi classic that launched one of cinema's most iconic franchises with pure time travel stakes.",
    poster: '/path/to/terminator-poster.jpg',
    backdrop: '/path/to/terminator-backdrop.jpg',
    backdrop_path: '/path/to/terminator-backdrop.jpg',
    poster_path: '/path/to/terminator-poster.jpg',
    scenes: [
      { time: 8, intensity: 45, label: 'Arrival', color: '#7c2d12' },
      { time: 28, intensity: 68, label: 'Tech Noir', color: '#9a3412' },
      { time: 58, intensity: 78, label: 'Police Station', color: '#c2410c' },
      { time: 82, intensity: 88, label: 'Chase', color: '#ea580c' },
      { time: 101, intensity: 94, label: 'Factory Showdown', color: '#f97316' }
    ],
    timeTravelIntensity: 94,
    complexityLevel: 'HIGH',
    dominantColor: '#7c2d12',
    dna: { Action: 45, SciFi: 40, Thriller: 15 },
    sensitiveScenes: [
      { start: "52:20", end: "53:15", description: "Sex scene" },
      { start: "1:12:30", end: "1:12:45", description: "Partial nudity" }
    ]
  },
  {
    imdbID: 'tt0816692',
    tmdbId: 157336,
    title: 'Interstellar',
    director: 'Christopher Nolan',
    genre: 'Adventure, Drama, Sci-Fi',
    year: 2014,
    runtime: '169 min',
    ageRating: 'PG-13',
    rating: 8.7,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    boxOffice: '$677.5 million',
    budget: '$165 million',
    synopsis: "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival. Mind-bending exploration of relativity, time dilation, and the emotional cost of time travel across dimensions. Visually stunning and deeply moving examination of love transcending space and time.",
    poster: '/path/to/interstellar-poster.jpg',
    backdrop: '/path/to/interstellar-backdrop.jpg',
    backdrop_path: '/path/to/interstellar-backdrop.jpg',
    poster_path: '/path/to/interstellar-poster.jpg',
    scenes: [
      { time: 45, intensity: 50, label: 'Launch', color: '#0891b2' },
      { time: 82, intensity: 68, label: 'Miller Planet', color: '#06b6d4' },
      { time: 118, intensity: 82, label: 'Mann Planet', color: '#22d3ee' },
      { time: 145, intensity: 90, label: 'Tesseract', color: '#67e8f9' },
      { time: 162, intensity: 95, label: 'Reunion', color: '#a5f3fc' }
    ],
    timeTravelIntensity: 95,
    complexityLevel: 'EXTREME',
    dominantColor: '#0891b2',
    dna: { SciFi: 50, Drama: 30, Adventure: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt2397535',
    tmdbId: 206487,
    title: 'Predestination',
    director: 'The Spierig Brothers',
    genre: 'Drama, Mystery, Sci-Fi',
    year: 2014,
    runtime: '97 min',
    ageRating: 'R',
    rating: 7.4,
    cast: ['Ethan Hawke', 'Sarah Snook', 'Noah Taylor'],
    boxOffice: '$5.6 million',
    budget: '$5 million',
    synopsis: "A temporal agent embarks on his final time-traveling mission to prevent an elusive criminal known as the 'Fizzle Bomber' from launching an attack that kills thousands. Paradox-heavy cerebral thriller that's one of the smartest, most intricately plotted time travel films ever made with a stunning twist.",
    poster: '/path/to/predestination-poster.jpg',
    backdrop: '/path/to/predestination-backdrop.jpg',
    backdrop_path: '/path/to/predestination-backdrop.jpg',
    poster_path: '/path/to/predestination-poster.jpg',
    scenes: [
      { time: 12, intensity: 35, label: 'Bar Meeting', color: '#854d0e' },
      { time: 38, intensity: 62, label: 'Backstory Revealed', color: '#a16207' },
      { time: 68, intensity: 78, label: 'Time Jump', color: '#ca8a04' },
      { time: 82, intensity: 88, label: 'Identity Revelation', color: '#eab308' },
      { time: 92, intensity: 97, label: 'Paradox Complete', color: '#fde047' }
    ],
    timeTravelIntensity: 97,
    complexityLevel: 'EXTREME',
    dominantColor: '#854d0e',
    dna: { SciFi: 50, Mystery: 35, Drama: 15 },
    sensitiveScenes: [
      { start: "1:02:15", end: "1:03:20", description: "Sex scene" }
    ]
  },
  {
    imdbID: 'tt0390384',
    tmdbId: 14337,
    title: 'Primer',
    director: 'Shane Carruth',
    genre: 'Drama, Sci-Fi, Thriller',
    year: 2004,
    runtime: '77 min',
    ageRating: 'PG-13',
    rating: 6.7,
    cast: ['Shane Carruth', 'David Sullivan', 'Casey Gooden'],
    boxOffice: '$841,926',
    budget: '$7,000',
    synopsis: "Two engineers accidentally discover a means of time travel. Ultra-complex indie masterpiece filmed on a shoestring budget. Technical, cerebral, and highly respected by time travel enthusiasts for its commitment to scientific plausibility and layered narrative complexity requiring multiple viewings.",
    poster: '/path/to/primer-poster.jpg',
    backdrop: '/path/to/primer-backdrop.jpg',
    backdrop_path: '/path/to/primer-backdrop.jpg',
    poster_path: '/path/to/primer-poster.jpg',
    scenes: [
      { time: 15, intensity: 28, label: 'Discovery', color: '#475569' },
      { time: 32, intensity: 52, label: 'First Use', color: '#64748b' },
      { time: 48, intensity: 68, label: 'Overlaps Begin', color: '#94a3b8' },
      { time: 62, intensity: 82, label: 'Paradox Layers', color: '#cbd5e1' },
      { time: 73, intensity: 98, label: 'Timeline Collapse', color: '#e2e8f0' }
    ],
    timeTravelIntensity: 98,
    complexityLevel: 'EXTREME',
    dominantColor: '#475569',
    dna: { SciFi: 60, Thriller: 25, Drama: 15 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0114746',
    tmdbId: 63,
    title: '12 Monkeys',
    director: 'Terry Gilliam',
    genre: 'Mystery, Sci-Fi, Thriller',
    year: 1995,
    runtime: '129 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Bruce Willis', 'Madeleine Stowe', 'Brad Pitt'],
    boxOffice: '$168.8 million',
    budget: '$29.5 million',
    synopsis: "In a future devastated by disease, a convict is sent back in time to gather information about the man-made virus that wiped out most of humanity. Dark, psychological, and dystopian with time travel central to its haunting, circular story about fate and madness.",
    poster: '/path/to/12monkeys-poster.jpg',
    backdrop: '/path/to/12monkeys-backdrop.jpg',
    backdrop_path: '/path/to/12monkeys-backdrop.jpg',
    poster_path: '/path/to/12monkeys-poster.jpg',
    scenes: [
      { time: 18, intensity: 42, label: 'First Jump', color: '#065f46' },
      { time: 52, intensity: 63, label: 'Psychiatrist', color: '#047857' },
      { time: 85, intensity: 74, label: 'Army of 12', color: '#059669' },
      { time: 108, intensity: 86, label: 'Airport', color: '#10b981' },
      { time: 124, intensity: 93, label: 'Circle Closes', color: '#34d399' }
    ],
    timeTravelIntensity: 93,
    complexityLevel: 'HIGH',
    dominantColor: '#065f46',
    dna: { SciFi: 45, Thriller: 35, Mystery: 20 },
    sensitiveScenes: [
      { start: "1:23:40", end: "1:24:15", description: "Partial nudity" }
    ]
  },
  {
    imdbID: 'tt0246578',
    tmdbId: 141,
    title: 'Donnie Darko',
    director: 'Richard Kelly',
    genre: 'Drama, Mystery, Sci-Fi',
    year: 2001,
    runtime: '113 min',
    ageRating: 'R',
    rating: 8.0,
    cast: ['Jake Gyllenhaal', 'Jena Malone', 'Mary McDonnell'],
    boxOffice: '$7.6 million',
    budget: '$4.5 million',
    synopsis: "A troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes. Surreal cult classic exploring deep time loop paradoxes, parallel universes, and existential themes with haunting atmosphere.",
    poster: '/path/to/donniedarko-poster.jpg',
    backdrop: '/path/to/donniedarko-backdrop.jpg',
    backdrop_path: '/path/to/donniedarko-backdrop.jpg',
    poster_path: '/path/to/donniedarko-poster.jpg',
    scenes: [
      { time: 8, intensity: 38, label: 'Frank Appears', color: '#581c87' },
      { time: 35, intensity: 58, label: 'Philosophy Class', color: '#6b21a8' },
      { time: 68, intensity: 72, label: 'Cellar Door', color: '#7c3aed' },
      { time: 92, intensity: 84, label: 'Halloween Party', color: '#8b5cf6' },
      { time: 108, intensity: 91, label: 'Sacrifice', color: '#a78bfa' }
    ],
    timeTravelIntensity: 91,
    complexityLevel: 'HIGH',
    dominantColor: '#581c87',
    dna: { Drama: 45, SciFi: 35, Mystery: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0107048',
    tmdbId: 137,
    title: 'Groundhog Day',
    director: 'Harold Ramis',
    genre: 'Comedy, Drama, Fantasy',
    year: 1993,
    runtime: '101 min',
    ageRating: 'PG',
    rating: 8.0,
    cast: ['Bill Murray', 'Andie MacDowell', 'Chris Elliott'],
    boxOffice: '$105 million',
    budget: '$14.6 million',
    synopsis: "A cynical TV weatherman finds himself reliving the same day over and over again during an assignment in Punxsutawney, Pennsylvania. Iconic time loop comedy that's emotional, existential, and widely loved for its storytelling influence on the entire time loop genre.",
    poster: '/path/to/groundhog-poster.jpg',
    backdrop: '/path/to/groundhog-backdrop.jpg',
    backdrop_path: '/path/to/groundhog-backdrop.jpg',
    poster_path: '/path/to/groundhog-poster.jpg',
    scenes: [
      { time: 12, intensity: 30, label: 'First Loop', color: '#be123c' },
      { time: 38, intensity: 52, label: 'Realization', color: '#e11d48' },
      { time: 58, intensity: 66, label: 'Experimentation', color: '#f43f5e' },
      { time: 78, intensity: 78, label: 'Self-Improvement', color: '#fb7185' },
      { time: 96, intensity: 89, label: 'True Love', color: '#fda4af' }
    ],
    timeTravelIntensity: 89,
    complexityLevel: 'MEDIUM',
    dominantColor: '#be123c',
    dna: { Comedy: 50, Drama: 30, Fantasy: 20 },
    sensitiveScenes: []
  },
  {
    imdbID: 'tt0480669',
    tmdbId: 13014,
    title: 'Timecrimes',
    director: 'Nacho Vigalondo',
    genre: 'Mystery, Sci-Fi, Thriller',
    year: 2007,
    runtime: '92 min',
    ageRating: 'R',
    rating: 7.1,
    cast: ['Karra Elejalde', 'Candela Fernández', 'Bárbara Goenaga'],
    boxOffice: '$574,188',
    budget: '$2.6 million',
    synopsis: "A man accidentally gets into a time machine and travels back an hour. Tight, suspenseful Spanish indie thriller with clever plotting and perfect pacing for fans of mind-bending time loops and causality paradoxes.",
    poster: '/path/to/timecrimes-poster.jpg',
    backdrop: '/path/to/timecrimes-backdrop.jpg',
    backdrop_path: '/path/to/timecrimes-backdrop.jpg',
    poster_path: '/path/to/timecrimes-poster.jpg',
    scenes: [
      { time: 8, intensity: 35, label: 'Binoculars', color: '#15803d' },
      { time: 24, intensity: 58, label: 'Machine', color: '#16a34a' },
      { time: 48, intensity: 72, label: 'Second Loop', color: '#22c55e' },
      { time: 68, intensity: 82, label: 'Realization', color: '#4ade80' },
      { time: 86, intensity: 90, label: 'Inevitable End', color: '#86efac' }
    ],
    timeTravelIntensity: 90,
    complexityLevel: 'HIGH',
    dominantColor: '#15803d',
    dna: { Thriller: 50, SciFi: 35, Mystery: 15 },
    sensitiveScenes: [
      { start: "18:45", end: "19:20", description: "Nudity (woman)" }
    ]
  }
];

// Build object map by tmdbId
export const COMPLETE_TIME_TRAVEL_DATABASE = Object.fromEntries(
  TIME_TRAVEL_MOVIES.map(m => [m.tmdbId, m])
);

export default COMPLETE_TIME_TRAVEL_DATABASE;
